// inject-scanner: scan HTTP request payloads for SQL injection and XSS threats.
// Uses two independent pattern sets compiled into one WASM module.
// stub.ts is auto-generated by: regexped generate --config=regexped.yaml
import { scan_sqli, scan_xss, patternName } from "./stub";

function check(label: string, payload: string): void {
  const buf = String.UTF8.encode(payload);
  console.log("[" + label + "] payload: " + payload);

  const sqli = scan_sqli(buf);
  if (sqli) {
    console.log("  [SQLI] " + patternName(sqli.patternId) + " at " + sqli.start.toString() + ".." + sqli.end.toString());
  } else {
    console.log("  [SQLI] clean");
  }

  const xss = scan_xss(buf);
  if (xss) {
    console.log("  [XSS]  detected at " + xss.start.toString() + ".." + xss.end.toString());
  } else {
    console.log("  [XSS]  clean");
  }
}

check("normal",        "SELECT name FROM users WHERE id = 42");
check("sqli",          "GET /api?id=1 UNION SELECT * FROM passwords");
check("xss",           "POST /comment body=<script>alert(1)</script>");
check("both",          "GET /search?q=<script>x</script>&id=1 UNION SELECT 1");
check("clean",         "GET /index.html HTTP/1.1");
check("union-no-sel",  "The UNION of two sets is not always a SELECT operation");
check("drop-table",    "DROP TABLE users; -- dangerous DDL injection");
