// inject-scanner: scan HTTP request payloads for SQL injection and XSS threats.
// Uses two independent pattern sets compiled into one WASM module.
// stub.ts is auto-generated by: regexped generate --config=regexped.yaml
import { scan_sqli, scan_xss, patternName, RX_ERR_BT_OVERFLOW } from "./stub";

function check(label: string, payload: string): void {
  const buf = String.UTF8.encode(payload);
  console.log("[" + label + "] payload: " + payload);

  // scan_any reports ONE pattern id that matches somewhere at or after
  // `offset`, or -1. It reports no position and no extent — which is what
  // makes it the cheap capability: with a start to report it would need an
  // anchored probe at every position, and without one it compiles to a single
  // union-automaton pass.
  // Test RX_ERR_BT_OVERFLOW *exactly*, not as "negative": -1 is a real answer
  // (nothing matched) while the sentinel means the engine gave up and the
  // answer is UNKNOWN. Folding the two would report "unknown" as "clean".
  // AssemblyScript uses sentinels rather than exceptions because asc cannot
  // catch — a throw there compiles to an uncatchable abort.
  const sqli = scan_sqli(buf, 0);
  if (sqli == RX_ERR_BT_OVERFLOW) {
    console.log("  [SQLI] cannot decide: backtracking budget exhausted");
  } else if (sqli >= 0) {
    console.log("  [SQLI] " + patternName(sqli));
  } else {
    console.log("  [SQLI] clean");
  }

  const xss = scan_xss(buf, 0);
  if (xss == RX_ERR_BT_OVERFLOW) {
    console.log("  [XSS]  cannot decide: backtracking budget exhausted");
  } else if (xss >= 0) {
    console.log("  [XSS]  detected: " + patternName(xss));
  } else {
    console.log("  [XSS]  clean");
  }
}

check("normal",        "SELECT name FROM users WHERE id = 42");
check("sqli",          "GET /api?id=1 UNION SELECT * FROM passwords");
check("xss",           "POST /comment body=<script>alert(1)</script>");
check("both",          "GET /search?q=<script>x</script>&id=1 UNION SELECT 1");
check("clean",         "GET /index.html HTTP/1.1");
check("union-no-sel",  "The UNION of two sets is not always a SELECT operation");
check("drop-table",    "DROP TABLE users; -- dangerous DDL injection");
