// url-ipv6 example: validate an IPv6-addressed URL (anchored match).
// stub.rs is auto-generated by: regexped generate
include!("stub.rs");

fn main() {
    let args: Vec<String> = std::env::args().collect();
    if args.len() < 2 {
        eprintln!("Usage: url_ipv6 <url>");
        std::process::exit(1);
    }
    let input = args[1].as_bytes();

    match url_ipv6::match_ipv6_url(input) {
        Some(end) => println!("Valid IPv6 URL (matched {} bytes)", end),
        None      => println!("Not a valid IPv6 URL"),
    }
}
