// Stubs are auto-generated by: regexped generate
include!("stubs.rs");

use proxy_wasm::traits::*;
use proxy_wasm::types::*;

proxy_wasm::main! {{
    proxy_wasm::set_log_level(LogLevel::Trace);
    proxy_wasm::set_root_context(|_| -> Box<dyn RootContext> { Box::new(Root) });
}}

struct Root;
impl Context for Root {}
impl RootContext for Root {
    fn create_http_context(&self, _: u32) -> Option<Box<dyn HttpContext>> {
        Some(Box::new(Guard))
    }
    fn get_type(&self) -> Option<ContextType> {
        Some(ContextType::HttpContext)
    }
}

struct Guard;
impl Context for Guard {}

impl HttpContext for Guard {
    fn on_http_request_headers(&mut self, _: usize, _: bool) -> Action {
        // Scan the request URL (path + query string).
        let url = match self.get_property(vec!["request.path"]) {
            Some(v) => v,
            None => return Action::Continue,
        };

        // scan_url returns an iterator; the first match is enough to block.
        if let Some(m) = patterns::scan_url(&url).next() {
            let attack = patterns::pattern_name(m.pattern_id);
            self.send_http_response(
                403,
                vec![("Content-Type", "text/plain")],
                Some(format!("Forbidden: {} detected", attack).as_bytes()),
            );
            return Action::Pause;
        }

        Action::Continue
    }
}
