// make_adjusted reads re2-exhaustive.txt, extracts sections that contain
// patterns with capture groups, rewrites col0 expectations using Go stdlib
// (LF semantics), and writes re2-adjusted.txt.
//
// Usage: go run ./make_adjusted re2-exhaustive.txt re2-adjusted.txt
//
// With -unicode-variants it instead reads re2-adjusted.txt and writes a
// Unicode-mode corpus: every section's strings replaced by variants carrying
// 2- to 4-byte characters and invalid UTF-8, and every column — col0 and col1
// as above, col4 every match — computed by Go over the pattern with U+FFFD
// taken out of its classes and `.` (noReplacement), so an invalid byte matches
// nothing, as in Unicode mode, and the columns are Unicode mode's own answers.
// The harness reads such a file with -unicode -unicode-oracle.
//
// Usage: go run ./make_adjusted -unicode-variants re2-adjusted.txt re2-unicode.txt
package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"regexp"
	"regexp/syntax"
	"strconv"
	"strings"
	"unicode/utf8"

	"github.com/qrdl/regexped/compile"
)

// maxDFAStates mirrors tools/re2test/main.go's own constant of the same
// name — SelectEngine's result (and therefore which of matchFn/groupsFn
// main.go actually tests col0 against) depends on it.
const maxDFAStates = 100000

type regexpEntry struct {
	pattern string
	results []string
}

type section struct {
	name    string
	strings []string
	regexps []regexpEntry
}

func isSectionName(line string) bool {
	if line == "" || strings.HasPrefix(line, "#") {
		return false
	}
	if line == "strings" || line == "regexps" {
		return false
	}
	if strings.HasPrefix(line, `"`) {
		return false
	}
	if strings.Contains(line, ";") {
		return false
	}
	if line == "-" {
		return false
	}
	return true
}

func parseSections(path string) ([]section, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	var sections []section
	var cur *section
	var inStrings, inRegexps bool
	var curPattern string
	var curResults []string

	flushPattern := func() {
		if cur != nil && curPattern != "" {
			cur.regexps = append(cur.regexps, regexpEntry{curPattern, curResults})
			curPattern = ""
			curResults = nil
		}
	}

	scanner := bufio.NewScanner(f)
	scanner.Buffer(make([]byte, 4*1024*1024), 4*1024*1024)
	for scanner.Scan() {
		line := scanner.Text()
		if strings.HasPrefix(line, "#") {
			continue
		}

		if line == "strings" {
			flushPattern()
			inStrings = true
			inRegexps = false
			continue
		}
		if line == "regexps" {
			inStrings = false
			inRegexps = true
			continue
		}

		// Detect new section name
		if isSectionName(line) {
			flushPattern()
			sections = append(sections, section{name: line})
			cur = &sections[len(sections)-1]
			inStrings = false
			inRegexps = false
			continue
		}

		if inStrings {
			s, err := strconv.Unquote(line)
			if err != nil {
				s = line
			}
			if cur != nil {
				cur.strings = append(cur.strings, s)
			}
			continue
		}
		if inRegexps {
			if strings.HasPrefix(line, `"`) {
				flushPattern()
				p, err := strconv.Unquote(line)
				if err != nil {
					p = line
				}
				curPattern = p
			} else {
				curResults = append(curResults, line)
			}
		}
	}
	flushPattern()
	return sections, scanner.Err()
}

func main() {
	variants := flag.Bool("unicode-variants", false, "read re2-adjusted.txt and write its Unicode-mode variant corpus")
	flag.Parse()
	if flag.NArg() != 2 {
		fmt.Fprintf(os.Stderr, "usage: make_adjusted [-unicode-variants] <input> <output>\n")
		os.Exit(1)
	}

	sections, err := parseSections(flag.Arg(0))
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if *variants {
		if err := writeUnicodeVariants(sections, flag.Arg(1)); err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
		return
	}

	out, err := os.Create(flag.Arg(1))
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	defer out.Close()
	w := bufio.NewWriter(out)

	nSections, nPatterns, nSkipped := 0, 0, 0

	fmt.Fprintf(w, "# re2-adjusted.txt — RE2 exhaustive patterns with capture groups,\n")
	fmt.Fprintf(w, "# col0 recomputed using Go stdlib (LF semantics).\n")
	fmt.Fprintf(w, "# Generated by: go run ./make_adjusted re2-exhaustive.txt re2-adjusted.txt\n")

	for _, sec := range sections {
		// Keep only sections that have at least one pattern with capture groups.
		hasCapture := false
		for _, rp := range sec.regexps {
			re, err := syntax.Parse(rp.pattern, syntax.Perl)
			if err != nil {
				continue
			}
			if re.MaxCap() > 0 {
				hasCapture = true
				break
			}
		}
		if !hasCapture {
			continue
		}

		fmt.Fprintf(w, "%s\n", sec.name)
		fmt.Fprintf(w, "strings\n")
		for _, s := range sec.strings {
			fmt.Fprintf(w, "%s\n", strconv.Quote(s))
		}
		fmt.Fprintf(w, "regexps\n")
		nSections++

		for _, rp := range sec.regexps {
			if _, parseErr := syntax.Parse(rp.pattern, syntax.Perl); parseErr != nil {
				nSkipped++
				continue
			}

			goRe, compErr := regexp.Compile(rp.pattern)
			if compErr != nil {
				nSkipped++
				continue
			}

			// Which of matchFn/groupsFn tools/re2test/main.go actually tests
			// col0 against is NOT determined by whether the pattern
			// syntactically has capture groups (numGroups) — it's determined
			// by which engine compile.SelectEngine actually picks for it
			// (main.go only wires up groupsFn when the selected engine is
			// Backtrack or TDFA; e.g. `(?:(a){4,5}){0}` has a syntactic
			// capture group but its body is provably unreachable, so the
			// compiler still picks a non-capturing DFA engine and main.go
			// tests it via matchFn instead). Mirror that decision exactly,
			// not the syntactic capture count.
			engineType, selErr := compile.SelectEngine(rp.pattern, compile.CompileOptions{MaxDFAStates: maxDFAStates, ForceByteMode: true})
			testedViaGroups := selErr == nil && (engineType == compile.EngineBacktrack || engineType == compile.EngineTDFA)

			// col0 for a matchFn-tested pattern requires full-input-
			// consumption with leftmost-longest priority (compile/compile.go's
			// needMatch path) — NOT "does the plain leftmost-first match
			// happen to span the whole string". \A(?:...)\z forces the
			// search to consider every full-consuming derivation, matching
			// that contract; a plain unanchored FindStringIndex would miss
			// full-consuming derivations that leftmost-first priority alone
			// wouldn't reach (e.g. lazy quantifiers).
			var goReFull *regexp.Regexp
			if !testedViaGroups {
				var fullErr error
				goReFull, fullErr = regexp.Compile(`\A(?:` + rp.pattern + `)\z`)
				if fullErr != nil {
					nSkipped++
					continue
				}
			}

			fmt.Fprintf(w, "%s\n", strconv.Quote(rp.pattern))
			nPatterns++

			for i, s := range sec.strings {
				// Compute both col0 and col1 using Go stdlib.
				_ = i

				// col1: first find (non-anchored)
				col1 := "-"
				if m := goRe.FindStringIndex(s); m != nil {
					col1 = fmt.Sprintf("%d-%d", m[0], m[1])
				}

				// Recompute col0 using Go stdlib.
				var col0 string
				if testedViaGroups {
					// col0 here is tested against regexped's groupsFn, a
					// non-anchored find-with-captures filtered only by
					// start==0 (NOT also end==len(s) — groupsFn has no
					// full-consumption requirement).
					m := goRe.FindStringSubmatchIndex(s)
					if m == nil || m[0] != 0 {
						col0 = "-"
					} else {
						var slots []string
						for k := 0; k+1 < len(m); k += 2 {
							if m[k] < 0 {
								slots = append(slots, "-")
							} else {
								slots = append(slots, fmt.Sprintf("%d-%d", m[k], m[k+1]))
							}
						}
						col0 = strings.Join(slots, " ")
					}
				} else {
					if m := goReFull.FindStringIndex(s); m == nil {
						col0 = "-"
					} else {
						col0 = fmt.Sprintf("0-%d", m[1])
					}
				}
				fmt.Fprintf(w, "%s;%s;-;-\n", col0, col1)
			}
		}
	}
	w.Flush()
	fmt.Fprintf(os.Stderr, "wrote %d sections, %d patterns (%d skipped)\n",
		nSections, nPatterns, nSkipped)
}

// unicodeVariants returns the inputs one corpus string becomes: a two-byte
// character after its first byte, a three- and a four-byte character around
// it, and invalid UTF-8 — a stray 0xFF in its middle and a sequence cut short
// at its end. An input holding a real U+FFFD gets none: noReplacement's
// oracle cannot judge it.
func unicodeVariants(s string) []string {
	if strings.Contains(s, "\uFFFD") {
		return nil
	}
	mid := len(s) / 2
	first := min(1, len(s))
	return []string{
		s[:first] + "é" + s[first:],
		"日" + s + "😀",
		s[:mid] + "\xff" + s[mid:] + "\xe2\x82",
	}
}

// noReplacement returns pat with U+FFFD taken out of every class and of `.`,
// so Go matches an invalid byte — which it decodes as U+FFFD — with nothing,
// as Unicode mode does.
func noReplacement(pat string) (string, bool) {
	re, err := syntax.Parse(pat, syntax.Perl)
	if err != nil {
		return "", false
	}
	without := func(rs []rune) []rune {
		var out []rune
		for i := 0; i+1 < len(rs); i += 2 {
			lo, hi := rs[i], rs[i+1]
			if lo <= utf8.RuneError && utf8.RuneError <= hi {
				if lo < utf8.RuneError {
					out = append(out, lo, utf8.RuneError-1)
				}
				if hi > utf8.RuneError {
					out = append(out, utf8.RuneError+1, hi)
				}
				continue
			}
			out = append(out, lo, hi)
		}
		return out
	}
	var walk func(*syntax.Regexp)
	walk = func(r *syntax.Regexp) {
		switch r.Op {
		case syntax.OpAnyChar:
			r.Op, r.Rune = syntax.OpCharClass, without([]rune{0, utf8.MaxRune})
		case syntax.OpAnyCharNotNL:
			r.Op, r.Rune = syntax.OpCharClass, without([]rune{0, '\n' - 1, '\n' + 1, utf8.MaxRune})
		case syntax.OpCharClass:
			r.Rune = without(r.Rune)
		}
		for _, sub := range r.Sub {
			walk(sub)
		}
	}
	walk(re)
	return re.String(), true
}

// writeUnicodeVariants writes the -unicode-variants corpus (see the file
// comment): col0 as main writes it — groups or full-consumption match by the
// engine Unicode mode selects — col1 the first match, col4 every match.
func writeUnicodeVariants(sections []section, path string) error {
	out, err := os.Create(path)
	if err != nil {
		return err
	}
	defer out.Close()
	w := bufio.NewWriter(out)
	fmt.Fprintf(w, "# re2-unicode.txt — re2-adjusted.txt's patterns over Unicode variants of its\n")
	fmt.Fprintf(w, "# strings, every column computed by Go without U+FFFD (Unicode mode's answers).\n")
	fmt.Fprintf(w, "# Generated by: go run ./make_adjusted -unicode-variants re2-adjusted.txt re2-unicode.txt\n")
	nPatterns, nRows := 0, 0
	for _, sec := range sections {
		var strs []string
		for _, s := range sec.strings {
			strs = append(strs, unicodeVariants(s)...)
		}
		if len(strs) == 0 {
			continue
		}
		type pat struct {
			src             string
			re, full        *regexp.Regexp
			testedViaGroups bool
		}
		var pats []pat
		for _, rp := range sec.regexps {
			oracle, ok := noReplacement(rp.pattern)
			if !ok {
				continue
			}
			re, err := regexp.Compile(oracle)
			if err != nil {
				continue
			}
			eng, selErr := compile.SelectEngine(rp.pattern, compile.CompileOptions{MaxDFAStates: maxDFAStates, Unicode: true})
			if selErr != nil {
				continue
			}
			p := pat{src: rp.pattern, re: re, testedViaGroups: eng == compile.EngineBacktrack || eng == compile.EngineTDFA}
			if !p.testedViaGroups {
				if p.full, err = regexp.Compile(`\A(?:` + oracle + `)\z`); err != nil {
					continue
				}
			}
			pats = append(pats, p)
		}
		if len(pats) == 0 {
			continue
		}
		fmt.Fprintf(w, "%s\nstrings\n", sec.name)
		for _, s := range strs {
			fmt.Fprintf(w, "%s\n", strconv.Quote(s))
		}
		fmt.Fprintf(w, "regexps\n")
		for _, p := range pats {
			fmt.Fprintf(w, "%s\n", strconv.Quote(p.src))
			nPatterns++
			for _, s := range strs {
				col1 := "-"
				if m := p.re.FindStringIndex(s); m != nil {
					col1 = fmt.Sprintf("%d-%d", m[0], m[1])
				}
				col0 := "-"
				if p.testedViaGroups {
					if m := p.re.FindStringSubmatchIndex(s); m != nil && m[0] == 0 {
						var slots []string
						for k := 0; k+1 < len(m); k += 2 {
							if m[k] < 0 {
								slots = append(slots, "-")
							} else {
								slots = append(slots, fmt.Sprintf("%d-%d", m[k], m[k+1]))
							}
						}
						col0 = strings.Join(slots, " ")
					}
				} else if m := p.full.FindStringIndex(s); m != nil {
					col0 = fmt.Sprintf("0-%d", m[1])
				}
				col4 := "-"
				if all := p.re.FindAllStringIndex(s, -1); len(all) > 0 {
					parts := make([]string, len(all))
					for i, m := range all {
						parts[i] = fmt.Sprintf("%d-%d", m[0], m[1])
					}
					col4 = strings.Join(parts, ",")
				}
				fmt.Fprintf(w, "%s;%s;-;-;%s\n", col0, col1, col4)
				nRows++
			}
		}
	}
	if err := w.Flush(); err != nil {
		return err
	}
	fmt.Fprintf(os.Stderr, "wrote %d patterns, %d rows\n", nPatterns, nRows)
	return nil
}
