// make_adjusted reads re2-exhaustive.txt, extracts sections that contain
// patterns with capture groups, rewrites col0 expectations using Go stdlib
// (LF semantics), and writes re2-adjusted.txt.
//
// Usage: go run ./make_adjusted re2-exhaustive.txt re2-adjusted.txt
package main

import (
	"bufio"
	"fmt"
	"os"
	"regexp"
	"regexp/syntax"
	"strconv"
	"strings"
)

type regexpEntry struct {
	pattern string
	results []string
}

type section struct {
	name    string
	strings []string
	regexps []regexpEntry
}

func isSectionName(line string) bool {
	if line == "" || strings.HasPrefix(line, "#") {
		return false
	}
	if line == "strings" || line == "regexps" {
		return false
	}
	if strings.HasPrefix(line, `"`) {
		return false
	}
	if strings.Contains(line, ";") {
		return false
	}
	if line == "-" {
		return false
	}
	return true
}

func parseSections(path string) ([]section, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	var sections []section
	var cur *section
	var inStrings, inRegexps bool
	var curPattern string
	var curResults []string

	flushPattern := func() {
		if cur != nil && curPattern != "" {
			cur.regexps = append(cur.regexps, regexpEntry{curPattern, curResults})
			curPattern = ""
			curResults = nil
		}
	}

	scanner := bufio.NewScanner(f)
	scanner.Buffer(make([]byte, 4*1024*1024), 4*1024*1024)
	for scanner.Scan() {
		line := scanner.Text()
		if strings.HasPrefix(line, "#") {
			continue
		}

		if line == "strings" {
			flushPattern()
			inStrings = true
			inRegexps = false
			continue
		}
		if line == "regexps" {
			inStrings = false
			inRegexps = true
			continue
		}

		// Detect new section name
		if isSectionName(line) {
			flushPattern()
			sections = append(sections, section{name: line})
			cur = &sections[len(sections)-1]
			inStrings = false
			inRegexps = false
			continue
		}

		if inStrings {
			s, err := strconv.Unquote(line)
			if err != nil {
				s = line
			}
			if cur != nil {
				cur.strings = append(cur.strings, s)
			}
			continue
		}
		if inRegexps {
			if strings.HasPrefix(line, `"`) {
				flushPattern()
				p, err := strconv.Unquote(line)
				if err != nil {
					p = line
				}
				curPattern = p
			} else {
				curResults = append(curResults, line)
			}
		}
	}
	flushPattern()
	return sections, scanner.Err()
}

func main() {
	if len(os.Args) != 3 {
		fmt.Fprintf(os.Stderr, "usage: make_adjusted <input> <output>\n")
		os.Exit(1)
	}

	sections, err := parseSections(os.Args[1])
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	out, err := os.Create(os.Args[2])
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	defer out.Close()
	w := bufio.NewWriter(out)

	nSections, nPatterns, nSkipped := 0, 0, 0

	fmt.Fprintf(w, "# re2-adjusted.txt — RE2 exhaustive patterns with capture groups,\n")
	fmt.Fprintf(w, "# col0 recomputed using Go stdlib (LF semantics).\n")
	fmt.Fprintf(w, "# Generated by: go run ./make_adjusted re2-exhaustive.txt re2-adjusted.txt\n")

	for _, sec := range sections {
		// Keep only sections that have at least one pattern with capture groups.
		hasCapture := false
		for _, rp := range sec.regexps {
			re, err := syntax.Parse(rp.pattern, syntax.Perl)
			if err != nil {
				continue
			}
			if re.MaxCap() > 0 {
				hasCapture = true
				break
			}
		}
		if !hasCapture {
			continue
		}

		fmt.Fprintf(w, "%s\n", sec.name)
		fmt.Fprintf(w, "strings\n")
		for _, s := range sec.strings {
			fmt.Fprintf(w, "%s\n", strconv.Quote(s))
		}
		fmt.Fprintf(w, "regexps\n")
		nSections++

		for _, rp := range sec.regexps {
			re, parseErr := syntax.Parse(rp.pattern, syntax.Perl)
			if parseErr != nil {
				nSkipped++
				continue
			}
			numGroups := re.MaxCap() + 1

			goRe, compErr := regexp.Compile(rp.pattern)
			if compErr != nil {
				nSkipped++
				continue
			}

			fmt.Fprintf(w, "%s\n", strconv.Quote(rp.pattern))
			nPatterns++

			for i, s := range sec.strings {
				// Compute both col0 and col1 using Go stdlib.
				_ = i

				// col1: first find (non-anchored)
				col1 := "-"
				if m := goRe.FindStringIndex(s); m != nil {
					col1 = fmt.Sprintf("%d-%d", m[0], m[1])
				}

				// Recompute col0 using Go stdlib.
				var col0 string
				if numGroups > 1 {
					m := goRe.FindStringSubmatchIndex(s)
					if m == nil || m[0] != 0 || m[1] != len(s) {
						col0 = "-"
					} else {
						var slots []string
						for k := 0; k+1 < len(m); k += 2 {
							if m[k] < 0 {
								slots = append(slots, "-")
							} else {
								slots = append(slots, fmt.Sprintf("%d-%d", m[k], m[k+1]))
							}
						}
						col0 = strings.Join(slots, " ")
					}
				} else {
					m := goRe.FindStringIndex(s)
					if m == nil || m[0] != 0 || m[1] != len(s) {
						col0 = "-"
					} else {
						col0 = fmt.Sprintf("0-%d", m[1])
					}
				}
				fmt.Fprintf(w, "%s;%s;-;-\n", col0, col1)
			}
		}
	}
	w.Flush()
	fmt.Fprintf(os.Stderr, "wrote %d sections, %d patterns (%d skipped)\n",
		nSections, nPatterns, nSkipped)
}
