// Auto-generated by regexped. Do not edit.

//go:build wasip1

package main

import (
	"iter"
	"unsafe"
)

//go:wasmimport sqli is_sqli
//go:noescape
func ffi_is_sqli(ptr unsafe.Pointer, length uint32) int32

// IsSqli returns the end position of the match (exclusive), or (0, false) if no match.
// The match is anchored: it starts at the beginning of input.
func IsSqli(input []byte) (int, bool) {
	var ptr unsafe.Pointer
	if len(input) > 0 {
		ptr = unsafe.Pointer(&input[0])
	}
	r := ffi_is_sqli(ptr, uint32(len(input)))
	if r < 0 {
		return 0, false
	}
	return int(r), true
}

//go:wasmimport sqli find_sqli
//go:noescape
func ffi_find_sqli(ptr unsafe.Pointer, length uint32) int64

// FindSqli returns an iterator over all non-overlapping matches in input.
// Each iteration yields (start, end) absolute byte positions.
func FindSqli(input []byte) iter.Seq2[int, int] {
	return func(yield func(int, int) bool) {
		pos := 0
		for pos <= len(input) {
			var ptr unsafe.Pointer
			if pos < len(input) {
				ptr = unsafe.Pointer(&input[pos])
			}
			r := ffi_find_sqli(ptr, uint32(len(input)-pos))
			if r < 0 {
				break
			}
			start := pos + int(uint64(r)>>32)
			end := pos + int(uint32(r))
			if !yield(start, end) {
				break
			}
			if end > pos {
				pos = end
			} else {
				pos++
			}
		}
	}
}

//go:wasmimport sqli parse_sqli
//go:noescape
func ffi_parse_sqli(ptr unsafe.Pointer, length uint32, outPtr unsafe.Pointer) int32

// ParseSqli returns an iterator over named capture groups of all non-overlapping matches.
// Each iteration yields a map of group name → [start,end] absolute byte offsets.
func ParseSqli(input []byte) iter.Seq[map[string][]int] {
	return func(yield func(map[string][]int) bool) {
		pos := 0
		for pos <= len(input) {
			var ptr unsafe.Pointer
			if pos < len(input) {
				ptr = unsafe.Pointer(&input[pos])
			}
			buf := make([]int32, 6)
			r := ffi_parse_sqli(ptr, uint32(len(input)-pos), unsafe.Pointer(&buf[0]))
			if r < 0 {
				if pos == len(input) {
					break
				}
				pos++
				continue
			}
			named := make(map[string][]int, 2)
			if buf[2] >= 0 { named["type"] = []int{int(buf[2]) + pos, int(buf[3]) + pos} }
			if buf[4] >= 0 { named["payload"] = []int{int(buf[4]) + pos, int(buf[5]) + pos} }
			matchEnd := 0
			if buf[1] >= 0 {
				matchEnd = int(buf[1])
			}
			if matchEnd > 0 {
				pos += matchEnd
			} else {
				pos++
			}
			if !yield(named) {
				break
			}
		}
	}
}

