/* url-parts example: find and parse all URLs in text.
 * stub.h is auto-generated by: regexped generate */
#include "stub.h"

/* ---- minimal WASI glue (no libc needed) --------------------------------- */

__attribute__((import_module("wasi_snapshot_preview1"), import_name("args_sizes_get")))
extern int wasi_args_sizes_get(unsigned int *argc, unsigned int *argv_buf_size);

__attribute__((import_module("wasi_snapshot_preview1"), import_name("args_get")))
extern int wasi_args_get(char **argv, char *argv_buf);

__attribute__((import_module("wasi_snapshot_preview1"), import_name("fd_write")))
extern int wasi_fd_write(int fd, const void *iovs, int iovs_len, int *nwritten);

__attribute__((import_module("wasi_snapshot_preview1"), import_name("proc_exit")))
__attribute__((noreturn))
extern void wasi_proc_exit(int code);

struct iov { const void *buf; unsigned int len; };

static unsigned int my_strlen(const char *s) {
    unsigned int n = 0;
    while (s[n]) n++;
    return n;
}

static void my_write(const char *s, unsigned int len) {
    int nw;
    struct iov v = { s, len };
    wasi_fd_write(1, &v, 1, &nw);
}

static void my_puts(const char *s) {
    my_write(s, my_strlen(s));
    my_write("\n", 1);
}

static void my_write_slice(const char *s, int start, int end) {
    my_write(s + start, (unsigned int)(end - start));
}

/* ---- main ---------------------------------------------------------------- */

__attribute__((export_name("_start")))
void _start(void) {
    unsigned int argc, buf_size;
    wasi_args_sizes_get(&argc, &buf_size);
    char *argv_buf = __builtin_alloca(buf_size + 1);
    char **argv = __builtin_alloca(argc * sizeof(char *));
    wasi_args_get(argv, argv_buf);

    if (argc < 2) {
        my_puts("Usage: url_parts <text>");
        wasi_proc_exit(1);
    }

    const char *text = argv[1];
    unsigned int len = my_strlen(text);
    const unsigned char *input = (const unsigned char *)text;

    static const char *names[] = { "scheme", "host", "port", "path", "query", "fragment" };
    static const int nnames = 6;

    int found = 0;
    int slots[PARSE_URL_SLOTS];
    parse_url_reset();
    while (parse_url_next(input, len, slots)) {
        found = 1;
        my_puts("URL:");
        for (int i = 0; i < nnames; i++) {
            int s, e;
            my_write("  ", 2);
            my_write(names[i], my_strlen(names[i]));
            /* pad to 10 chars */
            unsigned int nlen = my_strlen(names[i]);
            for (unsigned int p = nlen; p < 10; p++) my_write(" ", 1);
            my_write(" = ", 3);
            if (parse_url_get(slots, names[i], &s, &e)) {
                my_write_slice(text, s, e);
                my_write("\n", 1);
            } else {
                my_puts("(absent)");
            }
        }
    }
    if (!found) {
        my_puts("No URLs found");
    }
    wasi_proc_exit(0);
}
