/* url-parts example: find and parse all URLs in text.
 * stub.h and stub.c are auto-generated by: regexped generate
 *
 * Both the ITERATOR and the group array are YOURS (TODO tasks 59 and 62), so
 * two scans can be in flight and nothing is overwritten behind your back:
 *
 *   rx_parse_url_iter_t iter;
 *   parse_url_init(&iter, text, len, 0);
 *   rx_group_t groups[PARSE_URL_GROUPS];
 *   while (parse_url_next(&iter, groups) == 1) { ... }
 *
 * The iterator also owns the advance and the empty-match rule, which this file
 * used to hand-roll. Named groups are index CONSTANTS now — parse_url_scheme,
 * parse_url_host and so on — rather than a name pointer inside rx_group_t.
 */
#include "stub.h"

/* ---- minimal WASI glue (no libc needed) --------------------------------- */

__attribute__((import_module("wasi_snapshot_preview1"), import_name("args_sizes_get")))
extern int wasi_args_sizes_get(unsigned int *argc, unsigned int *argv_buf_size);

__attribute__((import_module("wasi_snapshot_preview1"), import_name("args_get")))
extern int wasi_args_get(char **argv, char *argv_buf);

__attribute__((import_module("wasi_snapshot_preview1"), import_name("fd_write")))
extern int wasi_fd_write(int fd, const void *iovs, int iovs_len, int *nwritten);

__attribute__((import_module("wasi_snapshot_preview1"), import_name("proc_exit")))
__attribute__((noreturn))
extern void wasi_proc_exit(int code);

struct iov { const void *buf; unsigned int len; };

static size_t my_strlen(const char *s) {
    size_t n = 0;
    while (s[n]) n++;
    return n;
}

static void my_write(const char *s, size_t len) {
    int nw;
    struct iov v = { s, (unsigned int)len };
    wasi_fd_write(1, &v, 1, &nw);
}

static void my_puts(const char *s) {
    my_write(s, my_strlen(s));
    my_write("\n", 1);
}

static void my_write_slice(const char *s, ptrdiff_t start, ptrdiff_t end) {
    my_write(s + start, (size_t)(end - start));
}

/* ---- main ---------------------------------------------------------------- */

__attribute__((export_name("_start")))
void _start(void) {
    unsigned int argc, buf_size;
    wasi_args_sizes_get(&argc, &buf_size);
    char *argv_buf = __builtin_alloca(buf_size + 1);
    char **argv = __builtin_alloca(argc * sizeof(char *));
    wasi_args_get(argv, argv_buf);

    if (argc < 2) {
        my_puts("Usage: url_parts <text>");
        wasi_proc_exit(1);
    }

    const char *text = argv[1];
    size_t len = my_strlen(text);

    rx_parse_url_iter_t iter;
    parse_url_init(&iter, text, len, 0);

    /* The index-aligned name table: entry i names the group at index i, and is
       "" where it has no name. Same shape as Go's regexp.SubexpNames. */
    const char *const *group_names = parse_url_names();

    rx_group_t groups[PARSE_URL_GROUPS];
    int found = 0;
    int status;
    while ((status = parse_url_next(&iter, groups)) == 1) {
        found = 1;
        my_puts("URL:");
        for (int group_num = 1; group_num < PARSE_URL_GROUPS; group_num++) {
            const char *name = group_names[group_num];
            if (!name[0] || groups[group_num].start < 0) continue;
            my_write("  ", 2);
            size_t name_len = my_strlen(name);
            my_write(name, name_len);
            /* pad to 10 chars */
            for (size_t pad = name_len; pad < 10; pad++) my_write(" ", 1);
            my_write(" = ", 3);
            my_write_slice(text, groups[group_num].start, groups[group_num].end);
            my_write("\n", 1);
        }
    }
    if (status == RX_ERR_BT_OVERFLOW) {
        /* The engine gave up: what remains is UNKNOWN, not "no more URLs". */
        my_puts("cannot decide: backtracking budget exhausted");
        wasi_proc_exit(2);
    }
    if (!found) {
        my_puts("No URLs found");
    }
    wasi_proc_exit(0);
}
