package generate

import (
	"fmt"
	"sort"
	"strings"

	"github.com/qrdl/regexped/config"
)

// asStub generates an AssemblyScript stub file for all regex entries in cfg.
// out is the full output path or "-" for stdout.
func asStub(cfg config.BuildConfig, out string) error {
	content, err := genASStubFile(cfg.Regexes, cfg.ImportModule)
	if err != nil {
		return fmt.Errorf("generate AS stub: %w", err)
	}
	if content == "" {
		return nil
	}
	if out == "-" {
		_, err := fmt.Print(content)
		return err
	}
	return writeStub(out, []byte(content))
}

// genASStubFile generates the content of an AssemblyScript stub file.
func genASStubFile(entries []config.RegexEntry, importModule string) (string, error) {
	if len(entries) == 0 {
		return "", nil
	}

	var parts []string
	for _, re := range entries {
		part, err := genASStubsForEntry(re, importModule)
		if err != nil {
			return "", err
		}
		if part != "" {
			parts = append(parts, part)
		}
	}
	if len(parts) == 0 {
		return "", nil
	}

	var sb strings.Builder
	sb.WriteString("// Auto-generated by regexped. Do not edit.\n\n")
	sb.WriteString(strings.Join(parts, ""))
	return sb.String(), nil
}

// genASStubsForEntry generates the AS stub content for a single regex entry.
func genASStubsForEntry(re config.RegexEntry, importModule string) (string, error) {
	var out string
	written := false

	if re.MatchFunc != "" {
		out += genASMatchStub(importModule, re.MatchFunc)
		written = true
	}
	if re.FindFunc != "" {
		out += genASFindStub(importModule, re.FindFunc)
		written = true
	}
	if re.GroupsFunc != "" || re.NamedGroupsFunc != "" {
		numGroups, namedGroups, err := extractGroupInfo(re.Pattern)
		if err != nil {
			return "", err
		}
		exportName := re.GroupsExportName()
		if re.GroupsFunc != "" {
			out += genASGroupsStub(importModule, re.GroupsFunc, exportName, true, numGroups)
			written = true
		}
		if re.NamedGroupsFunc != "" {
			declareFFI := re.GroupsFunc == ""
			out += genASNamedGroupsStub(importModule, re.NamedGroupsFunc, exportName, declareFFI, numGroups, namedGroups)
			written = true
		}
	}

	if !written {
		return "", nil
	}
	return out, nil
}

// genASMatchStub generates an anchored-match AS stub.
func genASMatchStub(importModule, funcName string) string {
	ffi := "_ffi_" + funcName
	var sb strings.Builder
	fmt.Fprintf(&sb, "@external(\"%s\", \"%s\")\n", importModule, funcName)
	fmt.Fprintf(&sb, "declare function %s(ptr: usize, len: usize): i32;\n\n", ffi)
	fmt.Fprintf(&sb, "/** Returns true if input matches anchored at the start. */\n")
	fmt.Fprintf(&sb, "export function %s(input: ArrayBuffer): bool {\n", funcName)
	fmt.Fprintf(&sb, "  return %s(changetype<usize>(input), <usize>input.byteLength) >= 0;\n", ffi)
	sb.WriteString("}\n\n")
	return sb.String()
}

// genASFindStub generates a find iterator AS stub with module-level offset state.
func genASFindStub(importModule, funcName string) string {
	ffi := "_ffi_" + funcName
	off := "_" + funcName + "_off"
	var sb strings.Builder
	fmt.Fprintf(&sb, "@external(\"%s\", \"%s\")\n", importModule, funcName)
	fmt.Fprintf(&sb, "declare function %s(ptr: usize, len: usize): i64;\n\n", ffi)
	fmt.Fprintf(&sb, "let %s: i32 = 0;\n\n", off)
	fmt.Fprintf(&sb, "/** Resets the %s iterator. Call before the first %s_next(). */\n", funcName, funcName)
	fmt.Fprintf(&sb, "export function %s_reset(): void { %s = 0; }\n\n", funcName, off)
	fmt.Fprintf(&sb, "/** Advances to the next match.\n")
	fmt.Fprintf(&sb, " *  Returns packed (absStart << 32 | absEnd) as i64, or -1 when exhausted. */\n")
	fmt.Fprintf(&sb, "export function %s_next(input: ArrayBuffer): i64 {\n", funcName)
	fmt.Fprintf(&sb, "  const len = input.byteLength;\n")
	fmt.Fprintf(&sb, "  while (%s <= len) {\n", off)
	fmt.Fprintf(&sb, "    const r = %s(changetype<usize>(input) + <usize>%s, <usize>(len - %s));\n", ffi, off, off)
	fmt.Fprintf(&sb, "    if (r < 0) { %s = len + 1; return -1; }\n", off)
	sb.WriteString("    const relStart = i32(<u64>r >> 32);\n")
	sb.WriteString("    const relEnd   = i32(<u32>r);\n")
	fmt.Fprintf(&sb, "    const absStart = %s + relStart;\n", off)
	fmt.Fprintf(&sb, "    const absEnd   = %s + relEnd;\n", off)
	fmt.Fprintf(&sb, "    %s += relEnd > relStart ? relEnd : relStart + 1;\n", off)
	sb.WriteString("    return (i64(absStart) << 32) | i64(absEnd);\n")
	sb.WriteString("  }\n")
	sb.WriteString("  return -1;\n")
	sb.WriteString("}\n\n")
	return sb.String()
}

// genASGroupsStub generates a capture-groups iterator AS stub.
// declareFFI controls whether the @external declaration is emitted.
func genASGroupsStub(importModule, funcName, exportName string, declareFFI bool, numGroups int) string {
	ffi := "_ffi_" + exportName
	off := "_" + funcName + "_off"
	slotsVar := "_" + funcName + "_slots"
	slotCount := numGroups * 2

	var sb strings.Builder
	if declareFFI {
		fmt.Fprintf(&sb, "@external(\"%s\", \"%s\")\n", importModule, exportName)
		fmt.Fprintf(&sb, "declare function %s(ptr: usize, len: usize, out_ptr: usize): i32;\n\n", ffi)
	}
	fmt.Fprintf(&sb, "const %s = new Int32Array(%d);\n", slotsVar, slotCount)
	fmt.Fprintf(&sb, "let %s: i32 = 0;\n\n", off)
	fmt.Fprintf(&sb, "/** Resets the %s iterator. Call before the first %s_next(). */\n", funcName, funcName)
	fmt.Fprintf(&sb, "export function %s_reset(): void { %s = 0; }\n\n", funcName, off)
	fmt.Fprintf(&sb, "/** Advances to the next match; fills the slot buffer.\n")
	fmt.Fprintf(&sb, " *  Use %s_group(i) to read group i (0 = full match). Returns false when exhausted. */\n", funcName)
	fmt.Fprintf(&sb, "export function %s_next(input: ArrayBuffer): bool {\n", funcName)
	fmt.Fprintf(&sb, "  const len = input.byteLength;\n")
	fmt.Fprintf(&sb, "  while (%s <= len) {\n", off)
	fmt.Fprintf(&sb, "    %s.fill(-1);\n", slotsVar)
	fmt.Fprintf(&sb, "    const r = %s(changetype<usize>(input) + <usize>%s, <usize>(len - %s), %s.dataStart);\n", ffi, off, off, slotsVar)
	fmt.Fprintf(&sb, "    if (r < 0) {\n")
	fmt.Fprintf(&sb, "      if (%s == len) { %s = len + 1; return false; }\n", off, off)
	fmt.Fprintf(&sb, "      %s++; continue;\n", off)
	sb.WriteString("    }\n")
	fmt.Fprintf(&sb, "    const matchOff = %s;\n", off)
	fmt.Fprintf(&sb, "    for (let i = 0; i < %d; i++) {\n", slotCount)
	fmt.Fprintf(&sb, "      if (%s[i] >= 0) %s[i] += matchOff;\n", slotsVar, slotsVar)
	sb.WriteString("    }\n")
	fmt.Fprintf(&sb, "    const end = %s[1] >= 0 ? %s[1] : matchOff + 1;\n", slotsVar, slotsVar)
	fmt.Fprintf(&sb, "    %s = end > matchOff ? end : matchOff + 1;\n", off)
	sb.WriteString("    return true;\n")
	sb.WriteString("  }\n")
	sb.WriteString("  return false;\n")
	sb.WriteString("}\n\n")
	fmt.Fprintf(&sb, "/** Returns packed (start << 32 | end) for group i (0 = full match), or -1 if absent. */\n")
	fmt.Fprintf(&sb, "export function %s_group(i: i32): i64 {\n", funcName)
	fmt.Fprintf(&sb, "  const s = %s[i * 2];\n", slotsVar)
	sb.WriteString("  if (s < 0) return -1;\n")
	fmt.Fprintf(&sb, "  return (i64(s) << 32) | i64(%s[i * 2 + 1]);\n", slotsVar)
	sb.WriteString("}\n\n")
	return sb.String()
}

// genASNamedGroupsStub generates a named-capture-groups iterator AS stub.
// declareFFI controls whether the @external declaration is emitted.
func genASNamedGroupsStub(importModule, funcName, exportName string, declareFFI bool, numGroups int, namedGroups map[string]int) string {
	// Iterator body is identical to groups; reuse it.
	out := genASGroupsStub(importModule, funcName, exportName, declareFFI, numGroups)

	type entry struct {
		name  string
		index int
	}
	var entries []entry
	for name, idx := range namedGroups {
		entries = append(entries, entry{name, idx})
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].index < entries[j].index })

	slotsVar := "_" + funcName + "_slots"
	var sb strings.Builder
	for _, e := range entries {
		fmt.Fprintf(&sb, "/** Returns packed (start << 32 | end) for group %q, or -1 if absent. */\n", e.name)
		fmt.Fprintf(&sb, "export function %s_get_%s(): i64 {\n", funcName, e.name)
		fmt.Fprintf(&sb, "  const s = %s[%d];\n", slotsVar, e.index*2)
		sb.WriteString("  if (s < 0) return -1;\n")
		fmt.Fprintf(&sb, "  return (i64(s) << 32) | i64(%s[%d]);\n", slotsVar, e.index*2+1)
		sb.WriteString("}\n\n")
	}
	return out + sb.String()
}
