package generate

import (
	"fmt"
	"strings"

	"github.com/qrdl/regexped/config"
)

// asStub generates an AssemblyScript stub file for all regexp entries in cfg.
// out is the full output path or "-" for stdout.
func asStub(cfg config.BuildConfig, out string) error {
	content, err := genASStubFile(cfg)
	if err != nil {
		return fmt.Errorf("generate AS stub: %w", err)
	}
	if content == "" {
		return nil
	}
	if out == "-" {
		_, err := fmt.Print(content)
		return err
	}
	return writeStub(out, []byte(content))
}

// genASStubFile generates the content of an AssemblyScript stub file.
func genASStubFile(cfg config.BuildConfig) (string, error) {
	var parts []string
	for _, re := range cfg.Regexps {
		part, err := genASStubsForEntry(re, cfg.ImportModule)
		if err != nil {
			return "", err
		}
		if part != "" {
			parts = append(parts, part)
		}
	}
	setSection := genASSetSection(cfg)
	if len(parts) == 0 && setSection == "" {
		return "", nil
	}

	var sb strings.Builder
	sb.WriteString("// Auto-generated by regexped. Do not edit.\n\n")
	sb.WriteString(strings.Join(parts, ""))
	sb.WriteString(setSection)
	return sb.String(), nil
}

// genASSetSection generates AssemblyScript set wrappers.
func genASSetSection(cfg config.BuildConfig) string {
	if !hasSetExports(cfg) {
		return ""
	}
	var out strings.Builder
	out.WriteString("\n// ---- set composition wrappers ----\n\n")
	out.WriteString("class SetMatch { constructor(public patternId: i32, public start: i32, public end: i32) {} }\n")
	out.WriteString("class SetAnchorMatch { constructor(public patternId: i32, public end: i32) {} }\n\n")
	for _, s := range cfg.Sets {
		bs := batchSize(s, cfg)
		if s.FindAll != "" || s.FindAny != "" {
			wasmExport := s.FindAll
			if wasmExport == "" {
				wasmExport = s.FindAny
			}
			fmt.Fprintf(&out, "@external(\"%s\", \"%s\")\ndeclare function ffi_%s(ptr: usize, len: i32, out: usize, cap: i32, start: i32): i32;\n\n",
				cfg.ImportModule, wasmExport, wasmExport)
			if s.FindAll != "" {
				// cap must be >= number of buckets so that all patterns matching
				// the same start position fit in one WASM call (same-start fan-out).
				// 64 is a safe floor — realistic sets have far fewer buckets.
				cap := max(bs, 64)
				fn := s.FindAll
				fmt.Fprintf(&out, `const _buf_%[1]s = new StaticArray<i32>(%[2]d*3);
let _start_%[1]s: i32 = 0; let _bufN_%[1]s: i32 = 0; let _bufI_%[1]s: i32 = 0;
/** Returns next match tuple or null when exhausted. Call %[1]s_reset() before reusing on a new input. */
export function %[1]s_next(input: ArrayBuffer): SetMatch | null {
    if (_bufI_%[1]s >= _bufN_%[1]s) {
        // _start_<fn> < 0 is a sentinel meaning "input exhausted on the previous
        // call" — when ffi returned n < cap. Do not call ffi again.
        if (_start_%[1]s < 0) { _bufN_%[1]s = 0; _bufI_%[1]s = 0; return null; }
        const n = ffi_%[3]s(changetype<usize>(input), input.byteLength, changetype<usize>(_buf_%[1]s), %[2]d, _start_%[1]s);
        if (n <= 0) { _bufN_%[1]s = 0; _bufI_%[1]s = 0; return null; }
        _bufN_%[1]s = n; _bufI_%[1]s = 0;
        // find_all returns when EITHER the buffer is full (n == cap) OR the
        // input has been fully scanned (n < cap). Only the buffer-full case
        // needs a resume; otherwise mark this iterator exhausted.
        if (n < %[2]d) {
            _start_%[1]s = -1;
        } else {
            const last = (n - 1) * 3;
            // Advance by exactly one position past the last reported start: the WASM
            // scan is position-by-position and only positions <= last.start have been
            // visited when the buffer fills, regardless of last.length.
            _start_%[1]s = _buf_%[1]s[last + 1] + 1;
        }
    }
    const i = _bufI_%[1]s++ * 3;
    return new SetMatch(_buf_%[1]s[i], _buf_%[1]s[i + 1], _buf_%[1]s[i + 1] + _buf_%[1]s[i + 2]);
}
export function %[1]s_reset(): void { _start_%[1]s = 0; _bufN_%[1]s = 0; _bufI_%[1]s = 0; }
`,
					fn, cap, wasmExport)
			}
			if s.FindAny != "" {
				anyFFI := "ffi_" + s.FindAny
				if s.FindAll != "" {
					anyFFI = "ffi_" + s.FindAll
				}
				fmt.Fprintf(&out, `export function %s(input: ArrayBuffer): SetMatch | null {
    const buf = new StaticArray<i32>(3);
    if (%s(changetype<usize>(input), input.byteLength, changetype<usize>(buf), 1, 0) <= 0) return null;
    return new SetMatch(buf[0], buf[1], buf[1]+buf[2]);
}
`, s.FindAny, anyFFI)
			}
		}
		if s.Match != "" {
			fmt.Fprintf(&out, "@external(\"%s\", \"%s\")\ndeclare function ffi_%s(ptr: usize, len: i32, out: usize, cap: i32): i32;\n\n",
				cfg.ImportModule, s.Match, s.Match)
			fmt.Fprintf(&out, `export function %s(input: ArrayBuffer): SetAnchorMatch | null {
    const buf = new StaticArray<i32>(3);
    if (ffi_%s(changetype<usize>(input), input.byteLength, changetype<usize>(buf), 1) <= 0) return null;
    return new SetAnchorMatch(buf[0], buf[1] + buf[2]);
}
`, s.Match, s.Match)
		}
	}
	if hasEmitNameMap(cfg) {
		names := make([]string, len(cfg.Regexps))
		for i, re := range cfg.Regexps {
			names[i] = fmt.Sprintf("%q", re.Name)
		}
		fmt.Fprintf(&out, "const _patternNames: string[] = [%s];\n", strings.Join(names, ", "))
		out.WriteString("export function patternName(id: i32): string { return id >= 0 && id < _patternNames.length ? _patternNames[id] : ''; }\n")
	}
	return out.String()
}

// genASStubsForEntry generates the AS stub content for a single regexp entry.
func genASStubsForEntry(re config.RegexEntry, importModule string) (string, error) {
	if re.NamedGroupsFunc != "" {
		return "", fmt.Errorf("named_groups_func is not supported for AS stubs; use groups_func instead")
	}

	var out string
	written := false

	if re.MatchFunc != "" {
		out += genASMatchStub(importModule, re.MatchFunc)
		written = true
	}
	if re.FindFunc != "" {
		out += genASFindStub(importModule, re.FindFunc)
		written = true
	}
	if re.GroupsFunc != "" {
		numGroups, _, err := extractGroupInfo(re.Pattern)
		if err != nil {
			return "", err
		}
		exportName := re.GroupsExportName()
		out += genASGroupsStub(importModule, re.GroupsFunc, exportName, numGroups)
		written = true
	}

	if !written {
		return "", nil
	}
	return out, nil
}

// genASMatchStub generates an anchored-match AS stub.
// Returns end position (≥0) or -1 if no match — mirrors Go and C API.
func genASMatchStub(importModule, funcName string) string {
	ffi := "_ffi_" + funcName
	var sb strings.Builder
	fmt.Fprintf(&sb, "@external(\"%s\", \"%s\")\n", importModule, funcName)
	fmt.Fprintf(&sb, "declare function %s(ptr: usize, len: usize): i32;\n\n", ffi)
	fmt.Fprintf(&sb, "/** Returns end position (≥0) or -1 if no match. */\n")
	fmt.Fprintf(&sb, "export function %s(input: ArrayBuffer): i32 {\n", funcName)
	fmt.Fprintf(&sb, "  return %s(changetype<usize>(input), <usize>input.byteLength);\n", ffi)
	sb.WriteString("}\n\n")
	return sb.String()
}

// genASFindStub generates a stateless find AS stub.
// The caller passes an offset and receives packed (absStart<<32|absEnd) or -1.
func genASFindStub(importModule, funcName string) string {
	ffi := "_ffi_" + funcName
	var sb strings.Builder
	fmt.Fprintf(&sb, "@external(\"%s\", \"%s\")\n", importModule, funcName)
	fmt.Fprintf(&sb, "declare function %s(ptr: usize, len: usize): i64;\n\n", ffi)
	fmt.Fprintf(&sb, "/** Finds match starting from offset.\n")
	fmt.Fprintf(&sb, " *  Returns packed (absStart << 32 | absEnd) as i64, or -1 if not found. */\n")
	fmt.Fprintf(&sb, "export function %s(input: ArrayBuffer, offset: i32): i64 {\n", funcName)
	sb.WriteString("  const len = input.byteLength;\n")
	sb.WriteString("  if (offset > len) return -1;\n")
	fmt.Fprintf(&sb, "  const r = %s(changetype<usize>(input) + <usize>offset, <usize>(len - offset));\n", ffi)
	sb.WriteString("  if (r < 0) return -1;\n")
	sb.WriteString("  const relStart = i32(<u64>r >> 32);\n")
	sb.WriteString("  const relEnd   = i32(<u32>r);\n")
	sb.WriteString("  return (i64(offset + relStart) << 32) | i64(offset + relEnd);\n")
	sb.WriteString("}\n\n")
	return sb.String()
}

// genASGroupsStub generates a stateless capture-groups AS stub.
// Returns the dataStart pointer of a static Int32Array slots buffer, or 0 on no match.
// Slot layout: [g0_start, g0_end, g1_start, g1_end, ...] as i32 values (absolute offsets).
func genASGroupsStub(importModule, funcName, exportName string, numGroups int) string {
	ffi := "_ffi_" + exportName
	slotsVar := "_" + funcName + "_slots"
	slotCount := numGroups * 2

	var sb strings.Builder
	fmt.Fprintf(&sb, "@external(\"%s\", \"%s\")\n", importModule, exportName)
	fmt.Fprintf(&sb, "declare function %s(ptr: usize, len: usize, out_ptr: usize): i32;\n\n", ffi)
	fmt.Fprintf(&sb, "const %s = new Int32Array(%d);\n\n", slotsVar, slotCount)
	fmt.Fprintf(&sb, "/** Finds capture match starting from offset.\n")
	fmt.Fprintf(&sb, " *  Returns dataStart pointer to slots buffer (pairs: start,end per group), or 0 on no match.\n")
	fmt.Fprintf(&sb, " *  Group 0 is the full match. Unmatched optional groups have start=-1, end=-1.\n")
	fmt.Fprintf(&sb, " *  Slot layout: [g0_start, g0_end, g1_start, g1_end, ...] as i32 values. */\n")
	fmt.Fprintf(&sb, "export function %s(input: ArrayBuffer, offset: i32): i32 {\n", funcName)
	sb.WriteString("  const len = input.byteLength;\n")
	sb.WriteString("  if (offset > len) return 0;\n")
	fmt.Fprintf(&sb, "  %s.fill(-1);\n", slotsVar)
	fmt.Fprintf(&sb, "  const r = %s(\n", ffi)
	sb.WriteString("    changetype<usize>(input) + <usize>offset,\n")
	sb.WriteString("    <usize>(len - offset),\n")
	fmt.Fprintf(&sb, "    %s.dataStart,\n", slotsVar)
	sb.WriteString("  );\n")
	sb.WriteString("  if (r < 0) return 0;\n")
	fmt.Fprintf(&sb, "  for (let i = 0; i < %d; i++) {\n", slotCount)
	fmt.Fprintf(&sb, "    if (%s[i] >= 0) %s[i] += offset;\n", slotsVar, slotsVar)
	sb.WriteString("  }\n")
	fmt.Fprintf(&sb, "  return i32(%s.dataStart);\n", slotsVar)
	sb.WriteString("}\n\n")
	return sb.String()
}
