package generate

import (
	"fmt"
	"strings"

	"github.com/qrdl/regexped/config"
)

// asStub generates an AssemblyScript stub file for all regex entries in cfg.
// out is the full output path or "-" for stdout.
func asStub(cfg config.BuildConfig, out string) error {
	content, err := genASStubFile(cfg)
	if err != nil {
		return fmt.Errorf("generate AS stub: %w", err)
	}
	if content == "" {
		return nil
	}
	if out == "-" {
		_, err := fmt.Print(content)
		return err
	}
	return writeStub(out, []byte(content))
}

// genASStubFile generates the content of an AssemblyScript stub file.
func genASStubFile(cfg config.BuildConfig) (string, error) {
	var parts []string
	for _, re := range cfg.Regexes {
		part, err := genASStubsForEntry(re, cfg.ImportModule)
		if err != nil {
			return "", err
		}
		if part != "" {
			parts = append(parts, part)
		}
	}
	setSection := genASSetSection(cfg)
	if len(parts) == 0 && setSection == "" {
		return "", nil
	}

	var sb strings.Builder
	sb.WriteString("// Auto-generated by regexped. Do not edit.\n\n")
	sb.WriteString(strings.Join(parts, ""))
	sb.WriteString(setSection)
	return sb.String(), nil
}

// genASSetSection generates AssemblyScript set wrappers.
func genASSetSection(cfg config.BuildConfig) string {
	if !hasSetExports(cfg) {
		return ""
	}
	var out strings.Builder
	out.WriteString("\n// ---- set composition wrappers ----\n\n")
	out.WriteString("class SetMatch { constructor(public patternId: i32, public start: i32, public end: i32) {} }\n")
	out.WriteString("class SetAnchorMatch { constructor(public patternId: i32, public end: i32) {} }\n\n")
	for _, s := range cfg.Sets {
		bs := batchSize(s)
		if s.FindAll != "" || s.FindAny != "" {
			wasmExport := s.FindAll
			if wasmExport == "" {
				wasmExport = s.FindAny
			}
			fmt.Fprintf(&out, "@external(\"%s\", \"%s\")\ndeclare function ffi_%s(ptr: usize, len: i32, out: usize, cap: i32, start: i32): i32;\n\n",
				cfg.ImportModule, wasmExport, wasmExport)
			if s.FindAll != "" {
				fmt.Fprintf(&out, `export function* %s(input: ArrayBuffer): Generator<SetMatch> {
    const buf = new StaticArray<i32>(%d*3);
    let startPos: i32 = 0;
    while (true) {
        const n = ffi_%s(changetype<usize>(input), input.byteLength, changetype<usize>(buf), %d, startPos);
        if (n <= 0) break;
        for (let i: i32 = 0; i < n; i++) {
            yield new SetMatch(buf[i*3], buf[i*3+1], buf[i*3+1]+buf[i*3+2]);
        }
        const l = buf[(n-1)*3+2]; startPos = buf[(n-1)*3+1] + (l > 0 ? l : 1);
    }
}
`, s.FindAll, bs, wasmExport, bs)
			}
			if s.FindAny != "" {
				anyFFI := "ffi_" + s.FindAny
				if s.FindAll != "" {
					anyFFI = "ffi_" + s.FindAll
				}
				fmt.Fprintf(&out, `export function %s(input: ArrayBuffer): SetMatch | null {
    const buf = new StaticArray<i32>(3);
    if (%s(changetype<usize>(input), input.byteLength, changetype<usize>(buf), 1, 0) <= 0) return null;
    return new SetMatch(buf[0], buf[1], buf[1]+buf[2]);
}
`, s.FindAny, anyFFI)
			}
		}
		if s.Match != "" {
			fmt.Fprintf(&out, "@external(\"%s\", \"%s\")\ndeclare function ffi_%s(ptr: usize, len: i32, out: usize, cap: i32): i32;\n\n",
				cfg.ImportModule, s.Match, s.Match)
			fmt.Fprintf(&out, `export function %s(input: ArrayBuffer): SetAnchorMatch | null {
    const buf = new StaticArray<i32>(2);
    if (ffi_%s(changetype<usize>(input), input.byteLength, changetype<usize>(buf), 1) <= 0) return null;
    return new SetAnchorMatch(buf[0], buf[1]);
}
`, s.Match, s.Match)
		}
	}
	if hasEmitNameMap(cfg) {
		names := make([]string, len(cfg.Regexes))
		for i, re := range cfg.Regexes {
			names[i] = fmt.Sprintf("%q", re.Name)
		}
		fmt.Fprintf(&out, "const _patternNames: string[] = [%s];\n", strings.Join(names, ", "))
		out.WriteString("export function patternName(id: i32): string { return id >= 0 && id < _patternNames.length ? _patternNames[id] : ''; }\n")
	}
	return out.String()
}

// genASStubsForEntry generates the AS stub content for a single regex entry.
func genASStubsForEntry(re config.RegexEntry, importModule string) (string, error) {
	if re.NamedGroupsFunc != "" {
		return "", fmt.Errorf("named_groups_func is not supported for AS stubs; use groups_func instead")
	}

	var out string
	written := false

	if re.MatchFunc != "" {
		out += genASMatchStub(importModule, re.MatchFunc)
		written = true
	}
	if re.FindFunc != "" {
		out += genASFindStub(importModule, re.FindFunc)
		written = true
	}
	if re.GroupsFunc != "" {
		numGroups, _, err := extractGroupInfo(re.Pattern)
		if err != nil {
			return "", err
		}
		exportName := re.GroupsExportName()
		out += genASGroupsStub(importModule, re.GroupsFunc, exportName, numGroups)
		written = true
	}

	if !written {
		return "", nil
	}
	return out, nil
}

// genASMatchStub generates an anchored-match AS stub.
// Returns end position (≥0) or -1 if no match — mirrors Go and C API.
func genASMatchStub(importModule, funcName string) string {
	ffi := "_ffi_" + funcName
	var sb strings.Builder
	fmt.Fprintf(&sb, "@external(\"%s\", \"%s\")\n", importModule, funcName)
	fmt.Fprintf(&sb, "declare function %s(ptr: usize, len: usize): i32;\n\n", ffi)
	fmt.Fprintf(&sb, "/** Returns end position (≥0) or -1 if no match. */\n")
	fmt.Fprintf(&sb, "export function %s(input: ArrayBuffer): i32 {\n", funcName)
	fmt.Fprintf(&sb, "  return %s(changetype<usize>(input), <usize>input.byteLength);\n", ffi)
	sb.WriteString("}\n\n")
	return sb.String()
}

// genASFindStub generates a stateless find AS stub.
// The caller passes an offset and receives packed (absStart<<32|absEnd) or -1.
func genASFindStub(importModule, funcName string) string {
	ffi := "_ffi_" + funcName
	var sb strings.Builder
	fmt.Fprintf(&sb, "@external(\"%s\", \"%s\")\n", importModule, funcName)
	fmt.Fprintf(&sb, "declare function %s(ptr: usize, len: usize): i64;\n\n", ffi)
	fmt.Fprintf(&sb, "/** Finds match starting from offset.\n")
	fmt.Fprintf(&sb, " *  Returns packed (absStart << 32 | absEnd) as i64, or -1 if not found. */\n")
	fmt.Fprintf(&sb, "export function %s(input: ArrayBuffer, offset: i32): i64 {\n", funcName)
	sb.WriteString("  const len = input.byteLength;\n")
	sb.WriteString("  if (offset > len) return -1;\n")
	fmt.Fprintf(&sb, "  const r = %s(changetype<usize>(input) + <usize>offset, <usize>(len - offset));\n", ffi)
	sb.WriteString("  if (r < 0) return -1;\n")
	sb.WriteString("  const relStart = i32(<u64>r >> 32);\n")
	sb.WriteString("  const relEnd   = i32(<u32>r);\n")
	sb.WriteString("  return (i64(offset + relStart) << 32) | i64(offset + relEnd);\n")
	sb.WriteString("}\n\n")
	return sb.String()
}

// genASGroupsStub generates a stateless capture-groups AS stub.
// Returns the dataStart pointer of a static Int32Array slots buffer, or 0 on no match.
// Slot layout: [g0_start, g0_end, g1_start, g1_end, ...] as i32 values (absolute offsets).
func genASGroupsStub(importModule, funcName, exportName string, numGroups int) string {
	ffi := "_ffi_" + exportName
	slotsVar := "_" + funcName + "_slots"
	slotCount := numGroups * 2

	var sb strings.Builder
	fmt.Fprintf(&sb, "@external(\"%s\", \"%s\")\n", importModule, exportName)
	fmt.Fprintf(&sb, "declare function %s(ptr: usize, len: usize, out_ptr: usize): i32;\n\n", ffi)
	fmt.Fprintf(&sb, "const %s = new Int32Array(%d);\n\n", slotsVar, slotCount)
	fmt.Fprintf(&sb, "/** Finds capture match starting from offset.\n")
	fmt.Fprintf(&sb, " *  Returns dataStart pointer to slots buffer (pairs: start,end per group), or 0 on no match.\n")
	fmt.Fprintf(&sb, " *  Group 0 is the full match. Unmatched optional groups have start=-1, end=-1.\n")
	fmt.Fprintf(&sb, " *  Slot layout: [g0_start, g0_end, g1_start, g1_end, ...] as i32 values. */\n")
	fmt.Fprintf(&sb, "export function %s(input: ArrayBuffer, offset: i32): i32 {\n", funcName)
	sb.WriteString("  const len = input.byteLength;\n")
	sb.WriteString("  if (offset > len) return 0;\n")
	fmt.Fprintf(&sb, "  %s.fill(-1);\n", slotsVar)
	fmt.Fprintf(&sb, "  const r = %s(\n", ffi)
	sb.WriteString("    changetype<usize>(input) + <usize>offset,\n")
	sb.WriteString("    <usize>(len - offset),\n")
	fmt.Fprintf(&sb, "    %s.dataStart,\n", slotsVar)
	sb.WriteString("  );\n")
	sb.WriteString("  if (r < 0) return 0;\n")
	fmt.Fprintf(&sb, "  for (let i = 0; i < %d; i++) {\n", slotCount)
	fmt.Fprintf(&sb, "    if (%s[i] >= 0) %s[i] += offset;\n", slotsVar, slotsVar)
	sb.WriteString("  }\n")
	fmt.Fprintf(&sb, "  return i32(%s.dataStart);\n", slotsVar)
	sb.WriteString("}\n\n")
	return sb.String()
}
