package generate

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/qrdl/regexped/config"
)

// The C stub for `wasm_format: component`.
//
// The HEADER is generated by the module-format code, unchanged: `cTypesPreamble`
// plus `genCPartsForEntry`'s `.h` half. That is deliberate — the header is the
// API, so sharing the generator makes the two formats API-identical by
// construction rather than by assertion.
//
// Only the `.c` differs, and C differs from Rust here. A Rust guest cannot
// declare its imports by hand, because `wasm32-wasip2` links the component in
// one step and demands component-type metadata. C builds a plain core module
// with clang, so the metadata can be attached AFTERWARDS by
// `wasm-tools component embed` — which means the C stub needs no binding
// generator and no third-party dependency at all. Verified end to end.
//
// Two things the module-format C stub does not need:
//
//   - the LOWERED import signature. A component import takes
//     `(ptr, len, start, retptr)` and returns void, with the CALLER supplying a
//     4-aligned return area; the result is read out of that area rather than
//     unpacked from an i64.
//   - `cabi_realloc`. A returned `list` is allocated in the CALLER's memory by
//     the composition glue, so a guest that receives one must export an
//     allocator. Only the groups shape returns a list, so it is emitted only
//     when some pattern exports groups.

// cComponentStub writes the component-flavoured C stub, plus the WIT directory
// the build needs.
func cComponentStub(cfg config.BuildConfig, out string) error {
	hBase := "stub.h"
	if out != "-" {
		hBase = filepath.Base(strings.TrimSuffix(out, filepath.Ext(out)) + ".h")
	}
	hContent, cContent, err := genCComponentStubFiles(cfg, hBase)
	if err != nil {
		return fmt.Errorf("generate C component stub: %w", err)
	}
	if hContent == "" {
		return nil
	}
	hContent = applyNamespace(cfg, "c", hContent)
	cContent = applyNamespace(cfg, "c", cContent)
	if out == "-" {
		_, err := os.Stdout.WriteString(hContent + cContent)
		return err
	}
	base := strings.TrimSuffix(out, filepath.Ext(out))
	if err := writeStub(base+".h", []byte(hContent)); err != nil {
		return err
	}
	if err := writeStub(base+".c", []byte(cContent)); err != nil {
		return err
	}
	// The WIT directory. `wasm-tools component embed` resolves `deps/` only when
	// given a DIRECTORY, so the layout matters, not just the contents.
	return writeComponentWitDir(cfg, filepath.Join(filepath.Dir(base), "wit"))
}

// writeComponentWitDir lays out the WIT the consumer's build needs:
//
//	<dir>/consumer.wit            a world importing our interface
//	<dir>/deps/<pkg>/matcher.wit  our interface, with the export world stripped
func writeComponentWitDir(cfg config.BuildConfig, dir string) error {
	witText, _, _, err := ComponentArtifacts(cfg)
	if err != nil {
		return err
	}
	pkg, err := cfg.WitPackageName()
	if err != nil {
		return err
	}
	world, err := cfg.WitWorldName()
	if err != nil {
		return err
	}
	iface := "regexped:" + pkg + "/matcher"
	if cfg.WitVersion != "" {
		iface += "@" + cfg.WitVersion
	}

	consumer := fmt.Sprintf(`// Auto-generated by regexped. Do not edit.
//
// The world the CONSUMER declares. Its own package, so it cannot collide with
// the interface package under deps/. Add your own exports to it — a component
// with no exports can be composed but not run.

package regexped-consumer:%s;

world %s {
    import %s;
}
`, pkg, consumerWorld(world), iface)

	if err := writeStub(filepath.Join(dir, "consumer.wit"), []byte(consumer)); err != nil {
		return err
	}
	// A dependency package supplies the INTERFACE only: an exporting world in it
	// would describe a component rather than a dependency.
	depDir := filepath.Join(dir, "deps", "regexped-"+pkg)
	return writeStub(filepath.Join(depDir, "matcher.wit"), []byte(stripExportWorld(witText)))
}

// stripExportWorld removes the `world … { export … }` block from generated WIT.
func stripExportWorld(witText string) string {
	var out []string
	depth := 0
	inWorld := false
	for _, l := range strings.Split(witText, "\n") {
		t := strings.TrimSpace(l)
		if !inWorld && strings.HasPrefix(t, "world ") {
			inWorld = true
			depth = strings.Count(t, "{") - strings.Count(t, "}")
			if depth <= 0 {
				inWorld = false
			}
			continue
		}
		if inWorld {
			depth += strings.Count(t, "{") - strings.Count(t, "}")
			if depth <= 0 {
				inWorld = false
			}
			continue
		}
		out = append(out, l)
	}
	return strings.TrimRight(strings.Join(out, "\n"), "\n") + "\n"
}

// genCComponentStubFiles renders both halves.
func genCComponentStubFiles(cfg config.BuildConfig, hBasename string) (hContent, cContent string, err error) {
	// The KEBAB name, not the snake_case one: a WASM import_name is the WIT
	// function name verbatim. Rust's macro does the kebab-to-snake mapping
	// itself, so the Rust stub wants the other form — using that here produced
	// "import interface … is missing function parse_url".
	names, err := componentKebabNames(cfg)
	if err != nil {
		return "", "", err
	}
	pkg, err := cfg.WitPackageName()
	if err != nil {
		return "", "", err
	}
	importModule := "regexped:" + pkg + "/matcher"
	if cfg.WitVersion != "" {
		importModule += "@" + cfg.WitVersion
	}

	var hb, cb strings.Builder
	var anyH bool
	var cparts []string
	needAlloc := false

	for _, re := range cfg.Regexps {
		// The HEADER comes from the module-format generator, unchanged: same API,
		// generated by the same code. Its .c half is discarded on purpose.
		h, _, e := genCPartsForEntry(re, importModule)
		if e != nil {
			return "", "", e
		}
		if h == "" {
			continue
		}
		anyH = true
		hb.WriteString(h)

		if re.MatchFunc != "" {
			cparts = append(cparts, genCComponentMatch(importModule, re.MatchFunc, names[re.MatchFunc]))
		}
		if re.FindFunc != "" {
			cparts = append(cparts, genCComponentFind(importModule, re.FindFunc, names[re.FindFunc]))
		}
		if re.GroupsFunc != "" {
			numGroups, namedGroups, e := extractGroupInfo(re.Pattern)
			if e != nil {
				return "", "", fmt.Errorf("regexp %q: %w", re.Pattern, e)
			}
			needAlloc = true
			cparts = append(cparts, genCComponentGroups(importModule, re.GroupsFunc, names[re.GroupsFunc], numGroups, namedGroups))
		}
	}
	if !anyH {
		return "", "", nil
	}

	header := cTypesPreamble()
	hContent = "/* Auto-generated by regexped. Do not edit.\n" +
		"   COMPONENT stub (wasm_format: component). The API below is identical to the\n" +
		"   module-format stub's, so switching formats changes no calling code.\n\n" +
		"   Build:\n" +
		"     clang --target=wasm32-wasi -nostdlib -Wl,--no-entry -o core.wasm your.c " + strings.TrimSuffix(hBasename, ".h") + ".c\n" +
		"     wasm-tools component embed wit core.wasm --world " + consumerWorldFor(cfg) + " -o embedded.wasm\n" +
		"     wasm-tools component new embedded.wasm -o guest.wasm\n" +
		"     wac plug guest.wasm --plug " + filepath.Base(cfg.WasmFile) + " -o composed.wasm\n\n" +
		"   The `wit` directory beside this header is generated too, and\n" +
		"   `component embed` needs the DIRECTORY, not one file: it resolves deps/\n" +
		"   from it. */\n" +
		"#pragma once\n\n" + strings.TrimPrefix(header, "/* Auto-generated by regexped. Do not edit. */\n#pragma once\n\n") + hb.String()

	cb.WriteString("/* Auto-generated by regexped. Do not edit. */\n")
	fmt.Fprintf(&cb, "#include \"%s\"\n\n", hBasename)
	if needAlloc {
		cb.WriteString(cComponentAllocator())
	}
	for _, p := range cparts {
		cb.WriteString(p)
	}
	return hContent, cb.String(), nil
}

func consumerWorldFor(cfg config.BuildConfig) string {
	world, err := cfg.WitWorldName()
	if err != nil {
		return "app"
	}
	return consumerWorld(world)
}

// cComponentAllocator emits the guest-side allocator the canonical ABI requires
// of anything that RECEIVES a list: the composition glue allocates the returned
// list in this component's memory by calling `cabi_realloc`.
//
// Three properties this has to get right, each learned from a failure:
//
//   - it is the COMPONENT'S allocator, not the stub's. The wasip1 adapter calls
//     it too (its `allocate_stack` does), so a heap sized for a group list alone
//     traps the moment the example is built as a command component.
//   - it therefore must NOT be reset globally. An earlier version zeroed the
//     bump pointer at the head of each groups call, which would hand out memory
//     the adapter was already using. The wrappers instead SAVE the mark before
//     their call and restore it after, rewinding only their own allocation.
//   - it is WEAK, so a program that already defines `cabi_realloc` — or links
//     something that does — wins. wit-bindgen's C output does the same.
func cComponentAllocator() string {
	return `/* Canonical-ABI allocator. A returned list lives in OUR memory, so the
   composition glue calls this to make room for it — and so does the wasip1
   adapter, if this component is built as a command. It is therefore the
   COMPONENT'S allocator, not this stub's private scratch: it is never reset
   wholesale. The generated wrappers save the mark before their call and restore
   it afterwards, which rewinds their own allocation and nothing else.

   WEAK, so your own cabi_realloc wins if you have one. */
#ifndef REGEXPED_CABI_REALLOC_DEFINED
#define REGEXPED_CABI_REALLOC_DEFINED

#ifndef REGEXPED_CABI_HEAP_BYTES
/* 256 KB. Sized by MEASUREMENT, not taste: the wasip1 adapter's allocate_stack
   takes the bulk of it when this component is built as a command, and 128 KB was
   observed to leave too little for a group list afterwards. A component with no
   adapter needs only 12 bytes per group and can define this much smaller; one
   that composes something hungrier can raise it. The allocator TRAPS rather than
   overrun, so a wrong value fails loudly. */
#define REGEXPED_CABI_HEAP_BYTES 262144
#endif

static unsigned char _rx_cabi_heap[REGEXPED_CABI_HEAP_BYTES];
static unsigned _rx_cabi_used = 0;

/* Save/restore the bump mark. Called by the generated wrappers, not by user
   code: only allocations made between the two calls are reclaimed. */
unsigned _rx_cabi_mark(void) { return _rx_cabi_used; }
void _rx_cabi_release(unsigned mark) { _rx_cabi_used = mark; }

__attribute__((__weak__, export_name("cabi_realloc")))
void *cabi_realloc(void *old_ptr, unsigned old_size, unsigned align, unsigned new_size) {
    (void)old_ptr;
    (void)old_size;
    unsigned p = (_rx_cabi_used + align - 1) & ~(align - 1);
    if (p + new_size > sizeof _rx_cabi_heap) {
        /* Out of scratch. Trapping is the only honest answer: returning a bad
           pointer would corrupt the caller's read of the list. Raise
           REGEXPED_CABI_HEAP_BYTES. */
        __builtin_trap();
    }
    _rx_cabi_used = p + new_size;
    return &_rx_cabi_heap[p];
}
#endif

`
}

// cComponentImport declares one lowered import.
func cComponentImport(importModule, witFunc, ffi string) string {
	return fmt.Sprintf(`__attribute__((__import_module__("%s"), __import_name__("%s")))
extern void %s(const unsigned char *ptr, unsigned int len, unsigned int start,
               unsigned char *ret);

`, importModule, witFunc, ffi)
}

func genCComponentMatch(importModule, funcName, witFunc string) string {
	ffi := "_ffi_" + funcName
	var sb strings.Builder
	// The anchored shape takes no `start`, so its lowered signature is one
	// argument shorter than the others.
	fmt.Fprintf(&sb, `__attribute__((__import_module__("%s"), __import_name__("%s")))
extern void %s(const unsigned char *ptr, unsigned int len, unsigned char *ret);

`, importModule, witFunc, ffi)
	fmt.Fprintf(&sb, `ptrdiff_t %s(const char *input, size_t len) {
    /* result<option<u32>, error-code>: @0 result disc, @4 option disc, @8 end */
    __attribute__((aligned(4))) unsigned char area[12] = {0};
    %s((const unsigned char *)input, (unsigned int)len, area);
    if (area[0] != 0) return RX_ERR_BT_OVERFLOW;   /* UNKNOWN, not "no match" */
    if (area[4] == 0) return -1;
    return (ptrdiff_t)(*(unsigned int *)(area + 8));
}

`, funcName, ffi)
	return sb.String()
}

func genCComponentFind(importModule, funcName, witFunc string) string {
	ffi := "_ffi_" + funcName
	iterType := cIterTypeName(funcName)
	var sb strings.Builder
	sb.WriteString(cComponentImport(importModule, witFunc, ffi))
	fmt.Fprintf(&sb, `int %[1]s_init(%[2]s *iter, const char *input, size_t len, size_t offset) {
    if (!iter || !input) return RX_ERR_NULL_ARG;
    iter->input = input;
    iter->len = len;
    iter->offset = offset;
    iter->prev_end = (size_t)-1;
    iter->done = (offset > len);
    return 0;
}

int %[1]s_next(%[2]s *iter, rx_match_t *out_match) {
    if (!iter || !out_match) return RX_ERR_NULL_ARG;
    while (!iter->done && iter->offset <= iter->len) {
        /* result<option<tuple<u32,u32>>, error-code>:
           @0 result disc, @4 option disc, @8 start, @12 end.
           The WHOLE input plus a start position: offset bounds where the search
           begins, it does not truncate what the engine can see behind it. */
        __attribute__((aligned(4))) unsigned char area[16] = {0};
        %[3]s((const unsigned char *)iter->input, (unsigned int)iter->len,
              (unsigned int)iter->offset, area);
        if (area[0] != 0) { iter->done = 1; return RX_ERR_BT_OVERFLOW; }
        if (area[4] == 0) { iter->done = 1; return 0; }
        size_t start = (size_t)(*(unsigned int *)(area + 8));
        size_t end   = (size_t)(*(unsigned int *)(area + 12));
        /* Advance first, so an empty match cannot spin the scan. */
        iter->offset = (end > start) ? end : start + 1;
        /* Go's FindAllIndex rule: an EMPTY match beginning exactly where the
           previous REPORTED match ended is suppressed. Only whether it is
           reported changes; the advance above is unchanged. */
        if (start == end && iter->prev_end == start) continue;
        iter->prev_end = end;
        out_match->start = (ptrdiff_t)start;
        out_match->end   = (ptrdiff_t)end;
        return 1;
    }
    iter->done = 1;
    return 0;
}

`, funcName, iterType, ffi)
	return sb.String()
}

func genCComponentGroups(importModule, funcName, witFunc string, numGroups int, namedGroups map[string]int) string {
	ffi := "_ffi_" + funcName
	iterType := cIterTypeName(funcName)
	funcUpper := toUpperIdent(funcName)
	var sb strings.Builder
	sb.WriteString(cComponentImport(importModule, witFunc, ffi))

	// The index-aligned name table and lookup are IDENTICAL to the module
	// format's, so they are generated by the same code path.
	sb.WriteString(cGroupsNameTable(funcName, numGroups, namedGroups))

	fmt.Fprintf(&sb, `int %[1]s_init(%[2]s *iter, const char *input, size_t len, size_t offset) {
    if (!iter || !input) return RX_ERR_NULL_ARG;
    iter->input = input;
    iter->len = len;
    iter->offset = offset;
    iter->prev_end = (size_t)-1;
    iter->done = (offset > len);
    return 0;
}

int %[1]s_next(%[2]s *iter, rx_group_t out_groups[static %[4]s_GROUPS]) {
    if (!iter || !out_groups) return RX_ERR_NULL_ARG;
    while (!iter->done && iter->offset <= iter->len) {
        /* result<option<list<option<tuple<u32,u32>>>>, error-code>:
           @0 result disc, @4 option disc, @8 list ptr, @12 list len.
           Each element is 12 bytes: @0 option disc, @4 start, @8 end. */
        __attribute__((aligned(4))) unsigned char area[16] = {0};
        /* Rewind only what THIS call allocates: cabi_realloc is the whole
           component's allocator, and a wholesale reset would hand out memory
           something else is still using. */
        unsigned _mark = _rx_cabi_mark();
        %[3]s((const unsigned char *)iter->input, (unsigned int)iter->len,
              (unsigned int)iter->offset, area);
        if (area[0] != 0) { iter->done = 1; _rx_cabi_release(_mark); return RX_ERR_BT_OVERFLOW; }
        if (area[4] == 0) { iter->done = 1; _rx_cabi_release(_mark); return 0; }
        const unsigned char *elems = *(const unsigned char **)(area + 8);
        unsigned int n = *(unsigned int *)(area + 12);
        if (!elems || n == 0) { iter->done = 1; _rx_cabi_release(_mark); return 0; }
        /* Group 0 is the whole match and is always set when the engine reported
           one; its extent drives the advance. */
        if (elems[0] == 0) { iter->done = 1; _rx_cabi_release(_mark); return 0; }
        size_t start = (size_t)(*(unsigned int *)(elems + 4));
        size_t end   = (size_t)(*(unsigned int *)(elems + 8));
        iter->offset = (end > start) ? end : start + 1;
        if (start == end && iter->prev_end == start) { _rx_cabi_release(_mark); continue; }
        iter->prev_end = end;
        for (unsigned int i = 0; i < %[4]s_GROUPS; i++) {
            if (i >= n) {
                /* Shorter list than the pattern's group count cannot happen, but
                   a caller's array must never be left uninitialised. */
                out_groups[i].start = -1;
                out_groups[i].end   = -1;
                continue;
            }
            const unsigned char *g = elems + (size_t)i * 12;
            if (g[0] == 0) {
                out_groups[i].start = -1;
                out_groups[i].end   = -1;
            } else {
                out_groups[i].start = (ptrdiff_t)(*(unsigned int *)(g + 4));
                out_groups[i].end   = (ptrdiff_t)(*(unsigned int *)(g + 8));
            }
        }
        /* The groups are copied into the CALLER's array, so the list is dead. */
        _rx_cabi_release(_mark);
        return 1;
    }
    iter->done = 1;
    return 0;
}

`, funcName, iterType, ffi, funcUpper)
	return sb.String()
}
