package generate

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/qrdl/regexped/config"
)

func cComponentCfg() config.BuildConfig {
	return config.BuildConfig{
		WasmFormat:   "component",
		ImportModule: "urlparts",
		WasmFile:     "/somewhere/urlparts.wasm",
		Regexps: []config.RegexEntry{
			{Pattern: `(?P<scheme>https?)://(?P<host>[^/:?#\s]+)`, GroupsFunc: "parse_url"},
			{Pattern: `AKIA[A-Z0-9]{16}`, FindFunc: "find_aws_key"},
			{Pattern: `[a-z]+`, MatchFunc: "lower_match"},
		},
		// A SET too, so the header-parity check covers every capability and the
		// find scanner — the one place the component mechanism differs most
		// (a resource handle rather than a caller-owned drive), and therefore
		// the most likely to leak into the API.
		Sets: []config.SetConfig{{
			Name:     "secrets",
			Patterns: config.PatternSelector{All: true},
			MatchAny: "which_secret",
			MatchAll: "all_secrets",
			ScanAny:  "any_secret",
			ScanAll:  "all_secret_hits",
			Find:     "scan_secrets",
		}},
	}
}

// The HEADER is the API, and it is generated by the module-format code for both
// formats. Asserting equality here is what makes "same API" a fact rather than an
// intention: a change to either generator that moved the surface would fail.
func TestCComponentHeaderIsIdenticalToModuleHeader(t *testing.T) {
	component := cComponentCfg()
	module := component
	module.WasmFormat = ""

	componentH, _, err := genCComponentStubFiles(component, "stub.h")
	if err != nil {
		t.Fatal(err)
	}
	moduleH, _, err := genCStubFilesWithSets(module, "stub.h")
	if err != nil {
		t.Fatal(err)
	}
	// The lead comment differs by design — the component one documents a
	// different build — so compare from the include guard onwards.
	const anchor = "#ifndef REGEXPED_TYPES_DEFINED"
	ci, mi := strings.Index(componentH, anchor), strings.Index(moduleH, anchor)
	if ci < 0 || mi < 0 {
		t.Fatal("could not locate the shared preamble in one of the headers")
	}
	got, want := stripCFFIImports(componentH[ci:]), stripCFFIImports(moduleH[mi:])
	if got != want {
		t.Errorf("headers differ below the lead comment.\n--- component ---\n%s\n--- module ---\n%s", got, want)
	}
}

// stripCFFIImports removes the raw WASM import declarations from a header.
//
// They are NOT API: they are how one stub reaches the module it was generated
// for, and the two formats import different things from different modules under
// different signatures — a module build imports `ffi_scan_secrets(ptr, len, from,
// gates, out, cap)` from the config's import_module, a component build imports
// `[method]scan-it.next(handle, retptr)` from a WIT interface. Neither could
// carry the other's, so requiring them to match would be requiring the wrong
// thing.
//
// Everything a CALLER touches — the constants, the types, the function
// declarations — is compared. The set declarations are the only place the module
// generator puts import lines in the header at all; the per-pattern ones already
// live in the .c.
func stripCFFIImports(h string) string {
	var out []string
	lines := strings.Split(h, "\n")
	for i := 0; i < len(lines); i++ {
		if strings.HasPrefix(lines[i], "__attribute__((import_module(") {
			i++ // and the declaration it applies to
			continue
		}
		out = append(out, lines[i])
	}
	return strings.Join(out, "\n")
}

// A WASM import_name carries the WIT function name verbatim, which is KEBAB.
// Using the snake_case form produced "import interface … is missing function
// parse_url" at `component new` — a failure the generator can prevent.
func TestCComponentImportsUseKebabNames(t *testing.T) {
	_, cContent, err := genCComponentStubFiles(cComponentCfg(), "stub.h")
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{
		`__import_module__("regexped:urlparts/matcher")`,
		`__import_name__("parse-url")`,
		`__import_name__("find-aws-key")`,
		`__import_name__("lower-match")`,
	} {
		if !strings.Contains(cContent, want) {
			t.Errorf("missing %q", want)
		}
	}
	for _, bad := range []string{`__import_name__("parse_url")`, `__import_name__("find_aws_key")`} {
		if strings.Contains(cContent, bad) {
			t.Errorf("snake_case import name %q must not appear", bad)
		}
	}
}

// A returned list is allocated in the CONSUMER's memory, so a stub that receives
// one must export an allocator — and one that never does must not carry it.
func TestCComponentAllocatorOnlyWhenGroupsExist(t *testing.T) {
	_, withGroups, err := genCComponentStubFiles(cComponentCfg(), "stub.h")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(withGroups, `export_name("cabi_realloc")`) {
		t.Error("a groups export needs cabi_realloc: the returned list lives in our memory")
	}
	// Save/restore, NOT a wholesale reset: cabi_realloc is the whole component's
	// allocator — the wasip1 adapter calls it too — so resetting it would hand
	// out memory something else is still using. That trapped in
	// `adapter!allocate_stack` when the C example was first built as a command.
	if !strings.Contains(withGroups, "_rx_cabi_mark()") ||
		!strings.Contains(withGroups, "_rx_cabi_release(_mark)") {
		t.Error("the groups wrapper must save and restore the bump mark")
	}
	if strings.Contains(withGroups, "_rx_cabi_reset") {
		t.Error("a wholesale reset is unsafe: the adapter's allocations live in the same heap")
	}
	// Weak, so a program with its own allocator wins.
	if !strings.Contains(withGroups, "__weak__") {
		t.Error("cabi_realloc must be weak")
	}
	// Every exit from the loop body must release, or a suppressed empty match
	// leaks the list it allocated.
	if strings.Count(withGroups, "_rx_cabi_release(_mark)") < 5 {
		t.Errorf("only %d release sites; every exit from the loop body needs one",
			strings.Count(withGroups, "_rx_cabi_release(_mark)"))
	}

	cfg := cComponentCfg()
	cfg.Regexps = []config.RegexEntry{{Pattern: `abc`, FindFunc: "f"}}
	cfg.Sets = nil // a set's `_all` and `find` return lists too
	_, noGroups, err := genCComponentStubFiles(cfg, "stub.h")
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(noGroups, "cabi_realloc") {
		t.Error("no list is ever returned here, so no allocator should be emitted")
	}

	// A SET capability that returns a list needs the allocator just as much: the
	// `_all` pair hands back a list of ids and the scanner a list of tuples, and
	// the canonical ABI lowers both into the CALLER's memory. Getting this wrong
	// fails late, at `component new`, with "module does not export a function
	// named cabi_realloc".
	setOnly := cComponentCfg()
	setOnly.Regexps = []config.RegexEntry{{Pattern: `abc`}, {Pattern: `def`}}
	_, setC, err := genCComponentStubFiles(setOnly, "stub.h")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(setC, `export_name("cabi_realloc")`) {
		t.Error("a set returning lists needs cabi_realloc")
	}
}

// The lowered signatures differ per shape: the anchored one takes no start.
func TestCComponentLoweredSignatures(t *testing.T) {
	_, cContent, err := genCComponentStubFiles(cComponentCfg(), "stub.h")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(cContent, "extern void _ffi_lower_match(const unsigned char *ptr, unsigned int len, unsigned char *ret);") {
		t.Error("the anchored import must take (ptr, len, retptr)")
	}
	if !strings.Contains(cContent, "unsigned int start,\n               unsigned char *ret);") {
		t.Error("the non-anchored imports must take a start and a retptr")
	}
	// The result areas are read, not unpacked from an i64 as the module stub does.
	if strings.Contains(cContent, "long long") {
		t.Error("a component stub has no packed i64 return")
	}
	for _, want := range []string{"area[12]", "area[16]"} {
		if !strings.Contains(cContent, want) {
			t.Errorf("missing result area %s", want)
		}
	}
}

// Both drive rules must survive into the component implementation.
func TestCComponentKeepsTheDriveRules(t *testing.T) {
	_, cContent, err := genCComponentStubFiles(cComponentCfg(), "stub.h")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(cContent, "iter->offset = (end > start) ? end : start + 1;") {
		t.Error("the advance rule is missing; a zero-length match would spin")
	}
	if !strings.Contains(cContent, "if (start == end && iter->prev_end == start) continue;") {
		t.Error("Go's adjacent-empty rule is missing")
	}
}

// The WIT directory layout is load-bearing: `component embed` resolves deps/ only
// when given the DIRECTORY, and a dependency package must not carry an exporting
// world.
func TestCComponentWritesWitDirectory(t *testing.T) {
	dir := t.TempDir()
	out := filepath.Join(dir, "stub.h")
	if err := cComponentStub(cComponentCfg(), out); err != nil {
		t.Fatal(err)
	}
	for _, f := range []string{"stub.h", "stub.c", "wit/consumer.wit", "wit/deps/regexped-urlparts/matcher.wit"} {
		if _, err := os.Stat(filepath.Join(dir, f)); err != nil {
			t.Errorf("missing generated file %s: %v", f, err)
		}
	}
	consumer, err := os.ReadFile(filepath.Join(dir, "wit", "consumer.wit"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(consumer), "world urlparts-consumer {") ||
		!strings.Contains(string(consumer), "import regexped:urlparts/matcher;") {
		t.Errorf("consumer world is wrong:\n%s", consumer)
	}
	dep, err := os.ReadFile(filepath.Join(dir, "wit", "deps", "regexped-urlparts", "matcher.wit"))
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(dep), "world ") {
		t.Errorf("the export world leaked into the dependency package:\n%s", dep)
	}
	if !strings.Contains(string(dep), "interface matcher {") {
		t.Errorf("the dependency lost its interface:\n%s", dep)
	}
}

func TestCComponentVersioned(t *testing.T) {
	cfg := cComponentCfg()
	cfg.WitVersion = "2.3.0"
	_, cContent, err := genCComponentStubFiles(cfg, "stub.h")
	if err != nil {
		t.Fatal(err)
	}
	// The version follows the INTERFACE name in the import module.
	if !strings.Contains(cContent, `__import_module__("regexped:urlparts/matcher@2.3.0")`) {
		t.Error("the version is missing from, or misplaced in, the import module")
	}
}

func TestCComponentDispatchAndEmpty(t *testing.T) {
	dir := t.TempDir()
	out := filepath.Join(dir, "stub.h")
	cfg := cComponentCfg()
	cfg.StubType = "c"
	cfg.StubFile = out
	if err := CmdGenerateStub(cfg, out); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(filepath.Join(dir, "stub.c"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(data), "__import_module__(\"regexped:") {
		t.Error("component config produced the MODULE stub")
	}

	// A config with no exports writes nothing at all.
	cfg.Regexps = []config.RegexEntry{{Pattern: "abc"}}
	cfg.Sets = nil // a set declaring a capability IS an export
	empty := filepath.Join(t.TempDir(), "stub.h")
	if err := cComponentStub(cfg, empty); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(empty); !os.IsNotExist(err) {
		t.Error("no header should have been written")
	}
}

func TestCComponentStubToStdout(t *testing.T) {
	r, w, err := os.Pipe()
	if err != nil {
		t.Fatal(err)
	}
	saved := os.Stdout
	os.Stdout = w
	done := make(chan string, 1)
	go func() {
		buf := make([]byte, 1<<20)
		n, _ := r.Read(buf)
		done <- string(buf[:n])
	}()
	err = cComponentStub(cComponentCfg(), "-")
	w.Close()
	os.Stdout = saved
	if err != nil {
		t.Fatal(err)
	}
	got := <-done
	if !strings.Contains(got, "#pragma once") || !strings.Contains(got, "__import_module__") {
		t.Error("stdout did not receive both halves")
	}
}

func TestCComponentNameErrors(t *testing.T) {
	cfg := cComponentCfg()
	cfg.Regexps = []config.RegexEntry{{Pattern: "a", FindFunc: "_bad"}}
	if _, _, err := genCComponentStubFiles(cfg, "stub.h"); err == nil {
		t.Error("an unrepresentable func name must be rejected")
	}
}

func TestStripExportWorld(t *testing.T) {
	in := "package regexped:x;\n\ninterface matcher {\n    enum e { a }\n}\n\nworld x {\n    export matcher;\n}\n"
	got := stripExportWorld(in)
	if strings.Contains(got, "world") {
		t.Errorf("world survived:\n%s", got)
	}
	if !strings.Contains(got, "interface matcher {") || !strings.Contains(got, "package regexped:x;") {
		t.Errorf("stripping removed too much:\n%s", got)
	}
}
