package generate

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/qrdl/regexped/config"
	"github.com/qrdl/regexped/internal/abi"
)

func cComponentCfg() config.BuildConfig {
	return config.BuildConfig{
		WasmFormat:   "component",
		ImportModule: "urlparts",
		WasmFile:     "/somewhere/urlparts.wasm",
		Regexps: []config.RegexEntry{
			{Pattern: `(?P<scheme>https?)://(?P<host>[^/:?#\s]+)`, GroupsFunc: "parse_url"},
			{Pattern: `AKIA[A-Z0-9]{16}`, FindFunc: "find_aws_key"},
			{Pattern: `[a-z]+`, MatchFunc: "lower_match"},
			{Name: "lower", Pattern: `[a-z]+`},
			{Name: "digits", Pattern: `[0-9]+`},
			{Name: "upper", Pattern: `[A-Z]+`},
		},
		// A SET too, so the header-parity check covers every capability and the
		// find scanner — the one place the component mechanism differs most
		// (a resource handle rather than a caller-owned drive), and therefore
		// the most likely to leak into the API.
		Sets: []config.SetConfig{{
			Name:     "secrets",
			Patterns: config.PatternSelector{All: true},
			MatchAny: "which_secret",
			MatchAll: "all_secrets",
			ScanAny:  "any_secret",
			ScanAll:  "all_secret_hits",
			Find:     "scan_secrets",
		}, {
			// CACHE-ELIGIBLE: an overlapping set over literal-less patterns is
			// the only shape whose module scanner struct carries the two
			// answer-cache fields, and the component struct lacked them. With
			// only the set above, the parity test compared two headers that
			// happened to agree.
			Name:        "runs",
			Patterns:    config.PatternSelector{Names: []string{"lower", "digits", "upper"}},
			Find:        "scan_runs",
			Overlapping: true,
		}},
	}
}

// The HEADER is the API, and it is generated by the module-format code for both
// formats. Asserting equality here is what makes "same API" a fact rather than an
// intention: a change to either generator that moved the surface would fail.
func TestCComponentHeaderIsIdenticalToModuleHeader(t *testing.T) {
	component := cComponentCfg()
	module := component
	module.WasmFormat = ""

	componentH, _, err := genCComponentStubFiles(component, "stub.h")
	if err != nil {
		t.Fatal(err)
	}
	moduleH, _, err := genCStubFilesWithSets(module, "stub.h")
	if err != nil {
		t.Fatal(err)
	}
	// The lead comment differs by design — the component one documents a
	// different build — so compare from the include guard onwards.
	const anchor = "#ifndef REGEXPED_TYPES_DEFINED"
	ci, mi := strings.Index(componentH, anchor), strings.Index(moduleH, anchor)
	if ci < 0 || mi < 0 {
		t.Fatal("could not locate the shared preamble in one of the headers")
	}
	got, want := stripCFFIImports(componentH[ci:]), stripCFFIImports(moduleH[mi:])
	if got != want {
		t.Errorf("headers differ below the lead comment.\n--- component ---\n%s\n--- module ---\n%s", got, want)
	}
}

// stripCFFIImports removes the raw WASM import declarations from a header.
//
// They are NOT API: they are how one stub reaches the module it was generated
// for, and the two formats import different things from different modules under
// different signatures — a module build imports `ffi_scan_secrets(ptr, len, from,
// gates, out, cap)` from the config's import_module, a component build imports
// `[method]scan-it.next(handle, retptr)` from a WIT interface. Neither could
// carry the other's, so requiring them to match would be requiring the wrong
// thing.
//
// Everything a CALLER touches — the constants, the types, the function
// declarations — is compared. The set declarations are the only place the module
// generator puts import lines in the header at all; the per-pattern ones already
// live in the .c.
func stripCFFIImports(h string) string {
	var out []string
	lines := strings.Split(h, "\n")
	for i := 0; i < len(lines); i++ {
		if strings.HasPrefix(lines[i], "__attribute__((import_module(") {
			i++ // and the declaration it applies to
			continue
		}
		out = append(out, lines[i])
	}
	return strings.Join(out, "\n")
}

// A WASM import_name carries the WIT function name verbatim, which is KEBAB.
// Using the snake_case form produced "import interface … is missing function
// parse_url" at `component new` — a failure the generator can prevent.
func TestCComponentImportsUseKebabNames(t *testing.T) {
	_, cContent, err := genCComponentStubFiles(cComponentCfg(), "stub.h")
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{
		`__import_module__("regexped:urlparts/matcher")`,
		`__import_name__("parse-url")`,
		`__import_name__("find-aws-key")`,
		`__import_name__("lower-match")`,
	} {
		if !strings.Contains(cContent, want) {
			t.Errorf("missing %q", want)
		}
	}
	for _, bad := range []string{`__import_name__("parse_url")`, `__import_name__("find_aws_key")`} {
		if strings.Contains(cContent, bad) {
			t.Errorf("snake_case import name %q must not appear", bad)
		}
	}
}

// A returned list is allocated in the CONSUMER's memory, so a stub that receives
// one must export an allocator — and one that never does must not carry it.
func TestCComponentAllocatorOnlyWhenAListIsReturned(t *testing.T) {
	_, withGroups, err := genCComponentStubFiles(cComponentCfg(), "stub.h")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(withGroups, `export_name("cabi_realloc")`) {
		t.Error("a groups export needs cabi_realloc: the returned list lives in our memory")
	}
	// Save/restore, NOT a wholesale reset: cabi_realloc is the whole component's
	// allocator — the wasip1 adapter calls it too — so resetting it would hand
	// out memory something else is still using. That trapped in
	// `adapter!allocate_stack` when the C example was first built as a command.
	if !strings.Contains(withGroups, "regexped_cabi_mark()") ||
		!strings.Contains(withGroups, "regexped_cabi_release(_mark)") {
		t.Error("the groups wrapper must save and restore the bump mark")
	}
	if strings.Contains(withGroups, "cabi_reset") {
		t.Error("a wholesale reset is unsafe: the adapter's allocations live in the same heap")
	}
	// Weak, so a program with its own allocator wins.
	if !strings.Contains(withGroups, "__weak__") {
		t.Error("cabi_realloc must be weak")
	}
	// Every exit from the loop body must release, or a suppressed empty match
	// leaks the list it allocated.
	if strings.Count(withGroups, "regexped_cabi_release(_mark)") < 5 {
		t.Errorf("only %d release sites; every exit from the loop body needs one",
			strings.Count(withGroups, "regexped_cabi_release(_mark)"))
	}

	cfg := cComponentCfg()
	cfg.Regexps = []config.RegexEntry{{Pattern: `abc`, FindFunc: "f"}}
	cfg.Sets = nil // a set's `_all` and `find` return lists too
	_, noGroups, err := genCComponentStubFiles(cfg, "stub.h")
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(noGroups, "cabi_realloc") {
		t.Error("no list is ever returned here, so no allocator should be emitted")
	}

	// A SET capability that returns a list needs the allocator just as much: the
	// `_all` pair hands back a list of ids and the scanner a list of tuples, and
	// the canonical ABI lowers both into the CALLER's memory. Getting this wrong
	// fails late, at `component new`, with "module does not export a function
	// named cabi_realloc".
	setOnly := cComponentCfg()
	setOnly.Regexps = []config.RegexEntry{{Pattern: `abc`}, {Pattern: `def`}}
	_, setC, err := genCComponentStubFiles(setOnly, "stub.h")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(setC, `export_name("cabi_realloc")`) {
		t.Error("a set returning lists needs cabi_realloc")
	}
}

// The lowered signatures differ per shape: the anchored one takes no start.
func TestCComponentLoweredSignatures(t *testing.T) {
	_, cContent, err := genCComponentStubFiles(cComponentCfg(), "stub.h")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(cContent, "extern void ffi_lower_match(const unsigned char *ptr, unsigned int len, unsigned char *ret);") {
		t.Error("the anchored import must take (ptr, len, retptr)")
	}
	if !strings.Contains(cContent, "unsigned int start,\n               unsigned char *ret);") {
		t.Error("the non-anchored imports must take a start and a retptr")
	}
	// The result areas are read, not unpacked from an i64 as the module stub does.
	if strings.Contains(cContent, "long long") {
		t.Error("a component stub has no packed i64 return")
	}
	for _, want := range []string{"area[12]", "area[16]"} {
		if !strings.Contains(cContent, want) {
			t.Errorf("missing result area %s", want)
		}
	}
}

// Both drive rules must survive into the component implementation.
func TestCComponentKeepsTheDriveRules(t *testing.T) {
	_, cContent, err := genCComponentStubFiles(cComponentCfg(), "stub.h")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(cContent, "iter->offset = (end > start) ? end : start + 1;") {
		t.Error("the advance rule is missing; a zero-length match would spin")
	}
	if !strings.Contains(cContent, "if (start == end && iter->prev_end == start) continue;") {
		t.Error("Go's adjacent-empty rule is missing")
	}
}

// The WIT directory layout is load-bearing: `component embed` resolves deps/ only
// when given the DIRECTORY, and a dependency package must not carry an exporting
// world.
func TestCComponentWritesWitDirectory(t *testing.T) {
	dir := t.TempDir()
	out := filepath.Join(dir, "stub.h")
	if err := cComponentStub(cComponentCfg(), out); err != nil {
		t.Fatal(err)
	}
	for _, f := range []string{"stub.h", "stub.c", "wit/consumer.wit", "wit/deps/regexped-urlparts/matcher.wit"} {
		if _, err := os.Stat(filepath.Join(dir, f)); err != nil {
			t.Errorf("missing generated file %s: %v", f, err)
		}
	}
	consumer, err := os.ReadFile(filepath.Join(dir, "wit", "consumer.wit"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(consumer), "world urlparts-consumer {") ||
		!strings.Contains(string(consumer), "import regexped:urlparts/matcher;") {
		t.Errorf("consumer world is wrong:\n%s", consumer)
	}
	dep, err := os.ReadFile(filepath.Join(dir, "wit", "deps", "regexped-urlparts", "matcher.wit"))
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(dep), "world ") {
		t.Errorf("the export world leaked into the dependency package:\n%s", dep)
	}
	if !strings.Contains(string(dep), "interface matcher {") {
		t.Errorf("the dependency lost its interface:\n%s", dep)
	}
}

func TestCComponentVersioned(t *testing.T) {
	cfg := cComponentCfg()
	cfg.WitVersion = "2.3.0"
	_, cContent, err := genCComponentStubFiles(cfg, "stub.h")
	if err != nil {
		t.Fatal(err)
	}
	// The version follows the INTERFACE name in the import module.
	if !strings.Contains(cContent, `__import_module__("regexped:urlparts/matcher@2.3.0")`) {
		t.Error("the version is missing from, or misplaced in, the import module")
	}
}

func TestCComponentDispatchAndEmpty(t *testing.T) {
	dir := t.TempDir()
	out := filepath.Join(dir, "stub.h")
	cfg := cComponentCfg()
	cfg.StubType = "c"
	cfg.StubFile = out
	if err := CmdGenerateStub(cfg, out); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(filepath.Join(dir, "stub.c"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(data), "__import_module__(\"regexped:") {
		t.Error("component config produced the MODULE stub")
	}

	// A config with no exports writes nothing at all.
	cfg.Regexps = []config.RegexEntry{{Pattern: "abc"}}
	cfg.Sets = nil // a set declaring a capability IS an export
	empty := filepath.Join(t.TempDir(), "stub.h")
	if err := cComponentStub(cfg, empty); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(empty); !os.IsNotExist(err) {
		t.Error("no header should have been written")
	}
}

func TestCComponentStubToStdout(t *testing.T) {
	r, w, err := os.Pipe()
	if err != nil {
		t.Fatal(err)
	}
	saved := os.Stdout
	os.Stdout = w
	done := make(chan string, 1)
	go func() {
		buf := make([]byte, 1<<20)
		n, _ := r.Read(buf)
		done <- string(buf[:n])
	}()
	err = cComponentStub(cComponentCfg(), "-")
	w.Close()
	os.Stdout = saved
	if err != nil {
		t.Fatal(err)
	}
	got := <-done
	if !strings.Contains(got, "#pragma once") || !strings.Contains(got, "__import_module__") {
		t.Error("stdout did not receive both halves")
	}
}

func TestCComponentNameErrors(t *testing.T) {
	cfg := cComponentCfg()
	cfg.Regexps = []config.RegexEntry{{Pattern: "a", FindFunc: "_bad"}}
	if _, _, err := genCComponentStubFiles(cfg, "stub.h"); err == nil {
		t.Error("an unrepresentable func name must be rejected")
	}
}

func TestStripExportWorld(t *testing.T) {
	in := "package regexped:x;\n\ninterface matcher {\n    enum e { a }\n}\n\nworld x {\n    export matcher;\n}\n"
	got := stripExportWorld(in)
	if strings.Contains(got, "world") {
		t.Errorf("world survived:\n%s", got)
	}
	if !strings.Contains(got, "interface matcher {") || !strings.Contains(got, "package regexped:x;") {
		t.Errorf("stripping removed too much:\n%s", got)
	}
}

// cFunctionBody returns the body of the C function whose definition line starts
// with `prefix`, up to its closing brace at column 0.
func cFunctionBody(t *testing.T, src, prefix string) string {
	t.Helper()
	i := strings.Index(src, "\n"+prefix)
	if i < 0 {
		t.Fatalf("no function starting %q in the generated source", prefix)
	}
	body := src[i+1:]
	if j := strings.Index(body, "\n}\n"); j >= 0 {
		body = body[:j+2]
	}
	return body
}

// The set wrappers that RECEIVE a list — the `_all` pair and the scanner — must
// release it on every return after the call, as the groups wrapper does. The
// composition glue allocates the returned list in this component's memory
// through cabi_realloc, and without the mark and release every call leaked it
// from the bump heap for the life of the process.
func TestCComponentSetListsAreReleasedPerCall(t *testing.T) {
	_, c, err := genCComponentStubFiles(cComponentCfg(), "stub.h")
	if err != nil {
		t.Fatal(err)
	}
	for _, prefix := range []string{"int all_secret_hits(", "int all_secrets(", "int scan_secrets(rx_secrets_scanner_t"} {
		body := cFunctionBody(t, c, prefix)
		mark := strings.Index(body, "cabi_mark(")
		if mark < 0 || strings.Count(body, "cabi_mark(") != 1 {
			t.Errorf("%s: want exactly one mark before the call, got %d", prefix, strings.Count(body, "cabi_mark("))
			continue
		}
		after := body[mark:]
		if r, n := strings.Count(after, "cabi_release("), strings.Count(after, "return "); r != n {
			t.Errorf("%s: %d releases for %d return paths after the mark:\n%s", prefix, r, n, body)
		}
	}
}

// A scanner call whose buffer cannot hold one position's worst case is refused
// with RX_ERR_RANGE before anything is written or advanced — in BOTH formats,
// since they share the header that states the rule. The module call used to be
// transactional and the component one silently discarded what did not fit.
func TestCScannerRefusesABufferBelowPatternCount(t *testing.T) {
	const want = "if (cap < (size_t)SECRETS_PATTERN_COUNT) return RX_ERR_RANGE;"
	h, c, err := genCComponentStubFiles(cComponentCfg(), "stub.h")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(c, want) {
		t.Errorf("the component scanner does not refuse a small buffer: missing %q", want)
	}
	mod := cComponentCfg()
	mod.WasmFormat = ""
	dir := t.TempDir()
	if err := cStub(mod, filepath.Join(dir, "stub.h")); err != nil {
		t.Fatal(err)
	}
	mc, err := os.ReadFile(filepath.Join(dir, "stub.c"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(mc), want) {
		t.Errorf("the module scanner does not refuse a small buffer: missing %q", want)
	}
	if strings.Contains(h, "transactional") {
		t.Error("the shared header still promises a transactional overflow")
	}
}

// Re-initialising a LIVE component scanner drops the resource it held before
// constructing a new one; the header promises it. A magic word tells a live
// scanner from an uninitialised struct, as the module scanner's does.
func TestCComponentReinitDropsTheLiveHandle(t *testing.T) {
	_, c, err := genCComponentStubFiles(cComponentCfg(), "stub.h")
	if err != nil {
		t.Fatal(err)
	}
	body := cFunctionBody(t, c, "int scan_secrets_init(")
	if !strings.Contains(body, fmt.Sprint(abi.FindScratchMagic)) {
		t.Errorf("_init does not test the scanner's magic word:\n%s", body)
	}
	drop, ctor := strings.Index(body, "_drop("), strings.Index(body, "_new(")
	if drop < 0 || ctor < 0 || drop > ctor {
		t.Errorf("_init must drop a live handle BEFORE constructing (drop at %d, construct at %d):\n%s",
			drop, ctor, body)
	}
}

// Two component C stubs in ONE guest must link. The allocator's mark and release
// were strong, non-static definitions, so a second stub was a duplicate symbol;
// and a per-stub copy of the heap state would let one stub rewind a counter the
// winning cabi_realloc never advanced. Every allocator symbol is WEAK, shared by
// name, so the linker keeps one of each.
func TestTwoCComponentStubsLinkInOneGuest(t *testing.T) {
	for _, tool := range []string{"cc", "nm"} {
		if _, err := exec.LookPath(tool); err != nil {
			t.Skipf("%s not on PATH", tool)
		}
	}
	dir := t.TempDir()
	mk := func(ns, pkg, set string) config.BuildConfig {
		return config.BuildConfig{
			WasmFormat: "component", ImportModule: pkg, WitPackage: pkg, Namespace: ns,
			Regexps: []config.RegexEntry{{Name: "a", Pattern: `[a-z]+`}, {Name: "d", Pattern: `[0-9]+`}},
			Sets: []config.SetConfig{{
				Name: set, Patterns: config.PatternSelector{All: true},
				ScanAll: set + "_hits", Find: "scan_" + set,
			}},
		}
	}
	var objs []string
	for _, s := range []struct{ ns, pkg, set string }{{"nsa", "pkg-a", "ova"}, {"nsb", "pkg-b", "ovb"}} {
		sub := filepath.Join(dir, s.ns)
		if err := os.MkdirAll(sub, 0o755); err != nil {
			t.Fatal(err)
		}
		if err := cComponentStub(mk(s.ns, s.pkg, s.set), filepath.Join(sub, "stub.h")); err != nil {
			t.Fatalf("generate %s: %v", s.ns, err)
		}
		obj := filepath.Join(dir, s.ns+".o")
		run(t, sub, nil, "cc", "-c", "-Wno-attributes", "-o", obj, "stub.c")
		objs = append(objs, obj)
	}
	main := "#include \"nsa/stub.h\"\n#include \"nsb/stub.h\"\nint main(void) { return 0; }\n"
	if err := os.WriteFile(filepath.Join(dir, "main.c"), []byte(main), 0o644); err != nil {
		t.Fatal(err)
	}
	run(t, dir, nil, "cc", "-fsyntax-only", "-Wno-attributes", "main.c")

	strong := map[string][]string{}
	for _, obj := range objs {
		out, err := exec.Command("nm", obj).CombinedOutput()
		if err != nil {
			t.Fatalf("nm %s: %v\n%s", obj, err, out)
		}
		for _, line := range strings.Split(string(out), "\n") {
			f := strings.Fields(line)
			if len(f) == 3 && (f[1] == "T" || f[1] == "D" || f[1] == "B") && strings.Contains(f[2], "cabi") {
				strong[f[2]] = append(strong[f[2]], filepath.Base(obj))
			}
		}
	}
	for sym, in := range strong {
		if len(in) > 1 {
			t.Errorf("%s is a strong definition in %v: two stubs in one guest cannot link", sym, in)
		}
	}
}

// A capability named like the resource's own imports must not collide with
// them. The resource imports were `_ffi_<find>_next` and friends, so a
// `scan_all: scan_it_next` beside `find: scan_it` declared one symbol twice with
// two signatures.
func TestCComponentCapabilityNamedLikeTheResourceImport(t *testing.T) {
	if _, err := exec.LookPath("cc"); err != nil {
		t.Skip("cc not on PATH")
	}
	cfg := config.BuildConfig{
		WasmFormat: "component", ImportModule: "t", WitPackage: "t",
		Regexps: []config.RegexEntry{{Name: "a", Pattern: `[a-z]+`}, {Name: "d", Pattern: `[0-9]+`}},
		Sets: []config.SetConfig{{
			Name: "s", Patterns: config.PatternSelector{All: true},
			ScanAll: "scan_it_next", Find: "scan_it",
		}},
	}
	dir := t.TempDir()
	if err := cComponentStub(cfg, filepath.Join(dir, "stub.h")); err != nil {
		t.Fatalf("generate: %v", err)
	}
	run(t, dir, nil, "cc", "-fsyntax-only", "-Wno-attributes", "stub.c")
}
