package generate

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/qrdl/regexped/config"
)

// cStub generates C stub files (.h and .c) for all regex entries in cfg.
// out is the stub file path from config (e.g. "stub.h"); both .h and .c are derived from it.
// If out == "-", both files' content is written concatenated to stdout.
func cStub(cfg config.BuildConfig, out string) error {
	hBase := "stub.h"
	if out != "-" {
		base := strings.TrimSuffix(out, filepath.Ext(out))
		hBase = filepath.Base(base + ".h")
	}

	hContent, cContent, err := genCStubFilesWithSets(cfg, hBase)
	if err != nil {
		return fmt.Errorf("generate C stub: %w", err)
	}
	if hContent == "" {
		return nil
	}
	if out == "-" {
		_, err := os.Stdout.WriteString(hContent + cContent)
		return err
	}
	base := strings.TrimSuffix(out, filepath.Ext(out))
	if err := writeStub(base+".h", []byte(hContent)); err != nil {
		return err
	}
	return writeStub(base+".c", []byte(cContent))
}

// genCStubFiles generates the content for both the .h and .c stub files.
// hBasename is the bare filename of the header (e.g. "stub.h") used in the #include directive.
func genCStubFiles(entries []config.RegexEntry, importModule, hBasename string) (hContent, cContent string, err error) {
	type entryParts struct{ h, c string }
	var parts []entryParts
	for _, re := range entries {
		h, c, e := genCPartsForEntry(re, importModule)
		if e != nil {
			return "", "", e
		}
		if h != "" {
			parts = append(parts, entryParts{h, c})
		}
	}

	var hb, cb strings.Builder

	// .h file
	hb.WriteString("/* Auto-generated by regexped. Do not edit. */\n")
	hb.WriteString("#pragma once\n\n")
	hb.WriteString("#ifndef REGEXPED_TYPES_DEFINED\n")
	hb.WriteString("#define REGEXPED_TYPES_DEFINED\n")
	hb.WriteString("typedef struct { int start; int end; } rx_match_t;\n")
	hb.WriteString("typedef struct { int start; int end; const char *name; } rx_group_t;\n")
	hb.WriteString("typedef struct { int pattern_id; int start; int end; } rx_set_match_t;\n")
	hb.WriteString("typedef struct { int pattern_id; int end; } rx_set_anchor_t;\n")
	hb.WriteString("#endif\n\n")

	// .c file
	cb.WriteString("/* Auto-generated by regexped. Do not edit. */\n")
	fmt.Fprintf(&cb, "#include \"%s\"\n\n", hBasename)

	for _, p := range parts {
		hb.WriteString(p.h)
		cb.WriteString(p.c)
	}

	if len(parts) == 0 && !hasSetExports(config.BuildConfig{Sets: nil}) {
		return "", "", nil
	}

	return hb.String(), cb.String(), nil
}

// cStubWithSets updates genCStubFiles to also handle sets.
func genCStubFilesWithSets(cfg config.BuildConfig, hBasename string) (hContent, cContent string, err error) {
	hContent, cContent, err = genCStubFiles(cfg.Regexes, cfg.ImportModule, hBasename)
	if err != nil {
		return
	}
	if !hasSetExports(cfg) {
		return
	}
	var hb, cb strings.Builder
	hb.WriteString(hContent)
	cb.WriteString(cContent)
	for _, s := range cfg.Sets {
		if s.FindAll != "" || s.FindAny != "" {
			wasmExport := s.FindAll
			if wasmExport == "" {
				wasmExport = s.FindAny
			}
			fmt.Fprintf(&hb, `__attribute__((import_module("%s"), import_name("%s")))
int ffi_%s(const char *ptr, int len, int *out, int cap, int start);
`, cfg.ImportModule, wasmExport, wasmExport)
			if s.FindAll != "" {
				fmt.Fprintf(&hb, "int %s_next(const char *input, int len, rx_set_match_t *out);\nvoid %s_reset(void);\n\n", s.FindAll, s.FindAll)
				fmt.Fprintf(&cb, `static int _start_%s = 0; static int _buf_%s[3];
int %s_next(const char *input, int len, rx_set_match_t *out) {
    int n = ffi_%s(input, len, _buf_%s, 1, _start_%s);
    if (n <= 0) return 0;
    out->pattern_id = _buf_%s[0]; out->start = _buf_%s[1]; out->end = _buf_%s[1]+_buf_%s[2];
    _start_%s = _buf_%s[1] + (_buf_%s[2] > 0 ? _buf_%s[2] : 1);
    return 1;
}
void %s_reset(void) { _start_%s = 0; }
`, s.FindAll, s.FindAll, s.FindAll, wasmExport, s.FindAll, s.FindAll,
					s.FindAll, s.FindAll, s.FindAll, s.FindAll,
					s.FindAll, s.FindAll, s.FindAll, s.FindAll,
					s.FindAll, s.FindAll)
			}
			if s.FindAny != "" {
				anyFFI := "ffi_" + s.FindAny
				if s.FindAll != "" {
					anyFFI = "ffi_" + s.FindAll
				}
				fmt.Fprintf(&hb, "int %s(const char *input, int len, rx_set_match_t *out);\n\n", s.FindAny)
				fmt.Fprintf(&cb, `int %s(const char *input, int len, rx_set_match_t *out) {
    int buf[3];
    if (%s(input, len, buf, 1, 0) <= 0) return 0;
    out->pattern_id = buf[0]; out->start = buf[1]; out->end = buf[1]+buf[2];
    return 1;
}
`, s.FindAny, anyFFI)
			}
		}
		if s.Match != "" {
			fmt.Fprintf(&hb, `__attribute__((import_module("%s"), import_name("%s")))
int ffi_%s(const char *ptr, int len, int *out, int cap);
int %s(const char *input, int len, rx_set_anchor_t *out);

`, cfg.ImportModule, s.Match, s.Match, s.Match)
			fmt.Fprintf(&cb, `int %s(const char *input, int len, rx_set_anchor_t *out) {
    int buf[2];
    if (ffi_%s(input, len, buf, 1) <= 0) return 0;
    out->pattern_id = buf[0]; out->end = buf[1];
    return 1;
}
`, s.Match, s.Match)
		}
	}
	if hasEmitNameMap(cfg) {
		hb.WriteString("const char *pattern_name(int id);\n\n")
		cb.WriteString("static const char *_pattern_names[] = {")
		for i, re := range cfg.Regexes {
			if i > 0 {
				cb.WriteString(", ")
			}
			fmt.Fprintf(&cb, "%q", re.Name)
		}
		cb.WriteString("};\nconst char *pattern_name(int id) { int n=sizeof(_pattern_names)/sizeof(*_pattern_names); return (id>=0&&id<n)?_pattern_names[id]:\"\"; }\n")
	}
	hContent = hb.String()
	cContent = cb.String()
	return
}

// genCPartsForEntry generates the .h and .c fragments for one regex entry.
func genCPartsForEntry(re config.RegexEntry, importModule string) (hPart, cPart string, err error) {
	if re.NamedGroupsFunc != "" {
		return "", "", fmt.Errorf("named_groups_func is not supported for C stubs; use groups_func instead")
	}

	var hb, cb strings.Builder

	if re.MatchFunc != "" {
		hb.WriteString(genCMatchHPart(re.MatchFunc))
		cb.WriteString(genCMatchCPart(importModule, re.MatchFunc))
	}
	if re.FindFunc != "" {
		hb.WriteString(genCFindHPart(re.FindFunc))
		cb.WriteString(genCFindCPart(importModule, re.FindFunc))
	}
	if re.GroupsFunc != "" {
		exportName := re.GroupsExportName()
		numGroups, namedGroups, e := extractGroupInfo(re.Pattern)
		if e != nil {
			return "", "", e
		}
		h, c := genCGroupsStubParts(importModule, re.GroupsFunc, exportName, numGroups, namedGroups)
		hb.WriteString(h)
		cb.WriteString(c)
	}
	return hb.String(), cb.String(), nil
}

// genCMatchHPart generates the .h prototype for an anchored-match function.
func genCMatchHPart(funcName string) string {
	return fmt.Sprintf(
		"/* %s: anchored match. Returns end position (>=0) or -1 if no match. */\n"+
			"int %s(const unsigned char *input, unsigned int len);\n\n",
		funcName, funcName)
}

// genCMatchCPart generates the .c FFI declaration and wrapper for an anchored-match function.
func genCMatchCPart(importModule, funcName string) string {
	ffi := "_ffi_" + funcName
	var sb strings.Builder
	fmt.Fprintf(&sb, "__attribute__((import_module(\"%s\"), import_name(\"%s\")))\n", importModule, funcName)
	fmt.Fprintf(&sb, "extern int %s(const unsigned char *ptr, unsigned int len);\n\n", ffi)
	fmt.Fprintf(&sb, "int %s(const unsigned char *input, unsigned int len) {\n", funcName)
	fmt.Fprintf(&sb, "    return %s(input, len);\n", ffi)
	sb.WriteString("}\n\n")
	return sb.String()
}

// genCFindHPart generates the .h prototype for a non-anchored find function.
func genCFindHPart(funcName string) string {
	return fmt.Sprintf(
		"/* %s: non-anchored find from offset.\n"+
			"   Returns absolute {start, end}, or {-1, -1} if not found. */\n"+
			"rx_match_t %s(const unsigned char *input, unsigned int len, unsigned int offset);\n\n",
		funcName, funcName)
}

// genCFindCPart generates the .c FFI declaration and wrapper for a non-anchored find function.
func genCFindCPart(importModule, funcName string) string {
	ffi := "_ffi_" + funcName
	var sb strings.Builder
	fmt.Fprintf(&sb, "__attribute__((import_module(\"%s\"), import_name(\"%s\")))\n", importModule, funcName)
	fmt.Fprintf(&sb, "extern long long %s(const unsigned char *ptr, unsigned int len);\n\n", ffi)
	fmt.Fprintf(&sb, "rx_match_t %s(const unsigned char *input, unsigned int len, unsigned int offset) {\n", funcName)
	sb.WriteString("    if (offset > len) return (rx_match_t){-1, -1};\n")
	fmt.Fprintf(&sb, "    long long r = %s(input + offset, len - offset);\n", ffi)
	sb.WriteString("    if (r < 0) return (rx_match_t){-1, -1};\n")
	sb.WriteString("    unsigned int rel_s = (unsigned int)((unsigned long long)r >> 32);\n")
	sb.WriteString("    unsigned int rel_e = (unsigned int)(r & 0xFFFFFFFFU);\n")
	sb.WriteString("    return (rx_match_t){(int)(offset + rel_s), (int)(offset + rel_e)};\n")
	sb.WriteString("}\n\n")
	return sb.String()
}

// toUpperIdent returns s with all lowercase ASCII letters uppercased.
func toUpperIdent(s string) string {
	var b strings.Builder
	for _, c := range s {
		if c >= 'a' && c <= 'z' {
			b.WriteRune(c - 32)
		} else {
			b.WriteRune(c)
		}
	}
	return b.String()
}

// cGroupConst returns the C constant name for a named capture group.
// e.g. funcName="parse_url", groupName="host" → "PARSE_URL_GROUP_HOST"
func cGroupConst(funcName, groupName string) string {
	return toUpperIdent(funcName) + "_GROUP_" + toUpperIdent(groupName)
}

// genCGroupsStubParts generates the .h and .c fragments for a capture-groups function.
// Both groups_func and named_groups_func entries are handled identically: the generated
// wrapper scans from offset and fills a static rx_group_t array.
// Named groups have their name field pointing to a public char array constant; others are NULL.
func genCGroupsStubParts(importModule, funcName, exportName string, numGroups int, namedGroups map[string]int) (hPart, cPart string) {
	type namedGroup struct {
		name  string
		index int // 1-based capture group index
	}
	var named []namedGroup
	for n, idx := range namedGroups {
		named = append(named, namedGroup{n, idx})
	}
	sort.Slice(named, func(i, j int) bool { return named[i].index < named[j].index })

	funcUpper := toUpperIdent(funcName)
	slotCount := numGroups * 2
	ffi := "_ffi_" + exportName
	resultVar := "_" + funcName + "_result"
	namesVar := "_" + funcName + "_names"

	var hb, cb strings.Builder

	// .h: group name constants
	if len(named) > 0 {
		fmt.Fprintf(&hb, "/* Group name constants for %s */\n", funcName)
		for _, g := range named {
			fmt.Fprintf(&hb, "extern const char * const %s;\n", cGroupConst(funcName, g.name))
		}
		hb.WriteString("\n")
	}

	// .h: groups count macro
	fmt.Fprintf(&hb, "#define %s_GROUPS %d\n\n", funcUpper, numGroups)

	// .h: function prototype and doc comment
	fmt.Fprintf(&hb,
		"/* %s: find next capture match from offset.\n"+
			"   Returns pointer to a static array of %s_GROUPS rx_group_t entries.\n"+
			"   groups[0] is the full match; subsequent entries are capture groups in order.\n"+
			"   Named groups have their name field pointing to the corresponding %s_GROUP_* constant;\n"+
			"   use == for identity comparison. Unnamed groups have name == NULL.\n"+
			"   All entries are {-1, -1, ...} when no match is found starting from offset.\n"+
			"   To iterate non-overlapping matches, advance offset to groups[0].end after\n"+
			"   each successful call. */\n"+
			"const rx_group_t *%s(const unsigned char *input, unsigned int len, unsigned int offset);\n\n",
		funcName, funcUpper, funcUpper, funcName)

	// .c: group name constant definitions
	if len(named) > 0 {
		fmt.Fprintf(&cb, "/* Group name constants for %s */\n", funcName)
		for _, g := range named {
			fmt.Fprintf(&cb, "const char * const %s = \"%s\";\n", cGroupConst(funcName, g.name), g.name)
		}
		cb.WriteString("\n")
	}

	// .c: internal name table (index → name pointer; NULL for group 0 and unnamed groups)
	// Using char array addresses (not pointer variables) ensures stable identity comparison.
	groupConstByIdx := make(map[int]string, len(named))
	for _, g := range named {
		groupConstByIdx[g.index] = cGroupConst(funcName, g.name)
	}
	fmt.Fprintf(&cb, "static const char * const %s[%d] = {\n", namesVar, numGroups)
	for i := 0; i < numGroups; i++ {
		if constName, ok := groupConstByIdx[i]; ok {
			fmt.Fprintf(&cb, "    %s,\n", constName)
		} else {
			cb.WriteString("    (const char *)0,\n")
		}
	}
	cb.WriteString("};\n\n")

	// .c: FFI declaration
	fmt.Fprintf(&cb, "__attribute__((import_module(\"%s\"), import_name(\"%s\")))\n", importModule, exportName)
	fmt.Fprintf(&cb, "extern int %s(const unsigned char *ptr, unsigned int len, int *out);\n\n", ffi)

	// .c: wrapper function
	fmt.Fprintf(&cb, "const rx_group_t *%s(const unsigned char *input, unsigned int len, unsigned int offset) {\n", funcName)
	fmt.Fprintf(&cb, "    static rx_group_t %s[%d];\n", resultVar, numGroups)
	fmt.Fprintf(&cb, "    int slots[%d];\n", slotCount)
	cb.WriteString("    unsigned int pos = offset;\n")
	cb.WriteString("    while (pos <= len) {\n")
	fmt.Fprintf(&cb, "        for (int i = 0; i < %d; i++) slots[i] = -1;\n", slotCount)
	fmt.Fprintf(&cb, "        int r = %s(input + pos, len - pos, slots);\n", ffi)
	cb.WriteString("        if (r >= 0) {\n")
	fmt.Fprintf(&cb, "            for (int i = 0; i < %d; i++) {\n", numGroups)
	fmt.Fprintf(&cb, "                %s[i].name = %s[i];\n", resultVar, namesVar)
	cb.WriteString("                if (slots[i*2] >= 0) {\n")
	fmt.Fprintf(&cb, "                    %s[i].start = (int)(pos + (unsigned int)slots[i*2]);\n", resultVar)
	fmt.Fprintf(&cb, "                    %s[i].end   = (int)(pos + (unsigned int)slots[i*2+1]);\n", resultVar)
	cb.WriteString("                } else {\n")
	fmt.Fprintf(&cb, "                    %s[i].start = -1;\n", resultVar)
	fmt.Fprintf(&cb, "                    %s[i].end   = -1;\n", resultVar)
	cb.WriteString("                }\n")
	cb.WriteString("            }\n")
	fmt.Fprintf(&cb, "            return %s;\n", resultVar)
	cb.WriteString("        }\n")
	cb.WriteString("        if (pos == len) break;\n")
	cb.WriteString("        pos++;\n")
	cb.WriteString("    }\n")
	// No match: set all entries to -1/-1 with names
	fmt.Fprintf(&cb, "    for (int i = 0; i < %d; i++) {\n", numGroups)
	fmt.Fprintf(&cb, "        %s[i].start = -1;\n", resultVar)
	fmt.Fprintf(&cb, "        %s[i].end   = -1;\n", resultVar)
	fmt.Fprintf(&cb, "        %s[i].name  = %s[i];\n", resultVar, namesVar)
	cb.WriteString("    }\n")
	fmt.Fprintf(&cb, "    return %s;\n", resultVar)
	cb.WriteString("}\n\n")

	return hb.String(), cb.String()
}
