package generate

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/qrdl/regexped/config"
)

// cStub generates C stub files (.h and .c) for all regexp entries in cfg.
// out is the stub file path from config (e.g. "stub.h"); both .h and .c are derived from it.
// If out == "-", both files' content is written concatenated to stdout.
func cStub(cfg config.BuildConfig, out string) error {
	hBase := "stub.h"
	if out != "-" {
		base := strings.TrimSuffix(out, filepath.Ext(out))
		hBase = filepath.Base(base + ".h")
	}

	hContent, cContent, err := genCStubFilesWithSets(cfg, hBase)
	if err != nil {
		return fmt.Errorf("generate C stub: %w", err)
	}
	if hContent == "" {
		return nil
	}
	if out == "-" {
		_, err := os.Stdout.WriteString(hContent + cContent)
		return err
	}
	base := strings.TrimSuffix(out, filepath.Ext(out))
	if err := writeStub(base+".h", []byte(hContent)); err != nil {
		return err
	}
	return writeStub(base+".c", []byte(cContent))
}

// genCStubFiles generates the content for both the .h and .c stub files.
// hBasename is the bare filename of the header (e.g. "stub.h") used in the #include directive.
func genCStubFiles(entries []config.RegexEntry, importModule, hBasename string) (hContent, cContent string, err error) {
	type entryParts struct{ h, c string }
	var parts []entryParts
	for _, re := range entries {
		h, c, e := genCPartsForEntry(re, importModule)
		if e != nil {
			return "", "", e
		}
		if h != "" {
			parts = append(parts, entryParts{h, c})
		}
	}

	var hb, cb strings.Builder

	// .h file
	hb.WriteString("/* Auto-generated by regexped. Do not edit. */\n")
	hb.WriteString("#pragma once\n\n")
	hb.WriteString("#ifndef REGEXPED_TYPES_DEFINED\n")
	hb.WriteString("#define REGEXPED_TYPES_DEFINED\n")
	// Types per TODO task 59 decision (1). size_t for lengths, offsets and
	// capacities and ONLY those — it means "can hold the size of any object",
	// which a pattern id is not. ptrdiff_t for positions coming back, because
	// -1 is the sentinel for "no match" / "group absent" and an unsigned type
	// has no room for it; this is the read() pairing. int for pattern ids and
	// counts, which keeps a negative slot free for a future failure and avoids
	// the signed/unsigned warning in for (int i = 0; i < n; i++).
	hb.WriteString("#include <stddef.h>   /* size_t, ptrdiff_t -- freestanding-required, no libc */\n\n")
	hb.WriteString("typedef struct { ptrdiff_t start, end; } rx_match_t;\n")
	hb.WriteString("typedef struct { ptrdiff_t start, end; const char *name; } rx_group_t;\n")
	hb.WriteString("typedef struct { int pattern_id; ptrdiff_t start, end; } rx_set_match_t;\n")
	hb.WriteString("\n")
	hb.WriteString("/* Returned when the Backtracking engine exhausted its backtrack-frame\n")
	hb.WriteString("   budget on this input. The engine abandoned part of the search space, so\n")
	hb.WriteString("   whether the input matches is UNKNOWN -- this is NOT \"no match\". Treat it\n")
	hb.WriteString("   as an error: shorten the input, or raise the pattern's frame budget.\n")
	hb.WriteString("   Unlike the other language stubs (which throw or panic), C has no\n")
	hb.WriteString("   unwinding, so the sentinel is returned to the caller: an int-returning\n")
	hb.WriteString("   match function returns it directly, a find function returns\n")
	hb.WriteString("   {RX_ERR_BT_OVERFLOW, RX_ERR_BT_OVERFLOW}, and a groups function returns\n")
	hb.WriteString("   NULL (which it never does otherwise). See docs/engines.md. */\n")
	fmt.Fprintf(&hb, "#define RX_ERR_BT_OVERFLOW (%d)\n", btOverflow)
	hb.WriteString("/* Argument errors from the scanner initialisers. */\n")
	hb.WriteString("#define RX_ERR_NULL_ARG    (-3)\n")
	hb.WriteString("#define RX_ERR_RANGE       (-5)\n")
	hb.WriteString("#endif\n\n")

	// .c file
	cb.WriteString("/* Auto-generated by regexped. Do not edit. */\n")
	fmt.Fprintf(&cb, "#include \"%s\"\n\n", hBasename)

	for _, p := range parts {
		hb.WriteString(p.h)
		cb.WriteString(p.c)
	}

	return hb.String(), cb.String(), nil
}

// cStubWithSets updates genCStubFiles to also handle sets.
func genCStubFilesWithSets(cfg config.BuildConfig, hBasename string) (hContent, cContent string, err error) {
	hasIndividual := false
	for _, re := range cfg.Regexps {
		if re.MatchFunc != "" || re.FindFunc != "" || re.GroupsFunc != "" || re.NamedGroupsFunc != "" {
			hasIndividual = true
			break
		}
	}
	if !hasIndividual && !hasSetExports(cfg) {
		return "", "", nil
	}
	hContent, cContent, err = genCStubFiles(cfg.Regexps, cfg.ImportModule, hBasename)
	if err != nil {
		return
	}
	if !hasSetExports(cfg) {
		return
	}
	var hb, cb strings.Builder
	hb.WriteString(hContent)
	cb.WriteString(cContent)
	for _, s := range cfg.Sets {
		n := patternsInSet(s, cfg)
		konst := screamingCase(s.Name) + "_PATTERN_COUNT"
		idN := idSpaceSize(s, cfg)
		idKonst := screamingCase(s.Name) + "_ID_SPACE"
		wide := wideAllForm(s, cfg)

		fmt.Fprintf(&hb, "/* Number of patterns in set %q. Sizes the match buffer: the scanner can\n   receive at most this many matches at one position. */\n#define %s %d\n\n", s.Name, konst, n)
		fmt.Fprintf(&hb, "/* One past the largest pattern id set %q can report. Pattern ids are global\n   indices into regexps:, so a set holding a few late-declared patterns has a\n   small count and a large id space. Everything indexed BY an id \u2014 the gate\n   array, the _all bitmap, and the out_ids array you pass to the _all calls \u2014\n   is sized from this. */\n#define %s %d\n\n", s.Name, idKonst, idN)

		imp := func(name, sig string) {
			fmt.Fprintf(&hb, "__attribute__((import_module(%q), import_name(%q)))\n%s\n", cfg.ImportModule, name, sig)
		}
		if s.MatchAny != "" {
			imp(s.MatchAny, fmt.Sprintf("int ffi_%s(const char *ptr, int len);", s.MatchAny))
			fmt.Fprintf(&hb, "/* Id of SOME pattern matching the whole input, or -1. */\nint %s(const char *input, size_t len);\n\n", s.MatchAny)
			fmt.Fprintf(&cb, `int %s(const char *input, size_t len) { return ffi_%s(input, (int)len); }
`, s.MatchAny, s.MatchAny)
		}
		if s.MatchAll != "" {
			if wide {
				imp(s.MatchAll, fmt.Sprintf("int ffi_%s(const char *ptr, int len, unsigned char *bits);", s.MatchAll))
			} else {
				imp(s.MatchAll, fmt.Sprintf("long long ffi_%s(const char *ptr, int len);", s.MatchAll))
			}
			// Decision (12): C99's `static N` in an array parameter declarator
			// means "the caller must pass at least N elements" — GCC and Clang
			// diagnose a smaller array at the CALL SITE, it rules out NULL,
			// and it self-documents. A plain int patterns[N] would decay to
			// int * and be documentation only.
			//
			// The size is PATTERN_COUNT, not ID_SPACE: the body loops k over
			// the id space and appends one entry per set bit, and only
			// patterns IN the set have bits, so at most PATTERN_COUNT entries
			// are ever written. ID_SPACE stays correct for things indexed BY
			// an id — the gate array, the _all bitmap — and this is a LIST of
			// ids, not an id-indexed array.
			fmt.Fprintf(&hb, "/* Writes the matching pattern ids into patterns and returns how many. */\nint %s(const char *input, size_t len, int patterns[static %s]);\n\n", s.MatchAll, konst)
			if wide {
				fmt.Fprintf(&cb, `int %[1]s(const char *input, size_t len, int patterns[static %[3]s]) {
    unsigned char bits[(%[2]s + 7) / 8] = {0};
    int n = ffi_%[1]s(input, (int)len, bits);
    if (n < 0) return n; /* RX_ERR_BT_OVERFLOW: result unknown, not empty */
    int c = 0;
    for (int k = 0; k < %[2]s; k++) if (bits[k / 8] & (1u << (k %% 8))) patterns[c++] = k;
    return c;
}
`, s.MatchAll, idKonst, konst)
			} else {
				fmt.Fprintf(&cb, `int %[1]s(const char *input, size_t len, int patterns[static %[3]s]) {
    unsigned long long mask = (unsigned long long)ffi_%[1]s(input, (int)len);
    int c = 0;
    for (int k = 0; k < %[2]s; k++) if (mask & (1ULL << k)) patterns[c++] = k;
    return c;
}
`, s.MatchAll, idKonst, konst)
			}
		}
		if s.ScanAny != "" {
			imp(s.ScanAny, fmt.Sprintf("int ffi_%s(const char *ptr, int len, int from);", s.ScanAny))
			fmt.Fprintf(&hb, "/* Returns one pattern id matching somewhere at or after offset, or -1.\n   Which id you get is unspecified when several patterns match, and no\n   position is reported.\n\n   May also return RX_ERR_BT_OVERFLOW: a Backtracking member of this set\n   exhausted its frame budget, so the answer is UNKNOWN rather than -1.\n   Test for it before treating a negative result as \"no match\". */\nint %s(const char *input, size_t len, size_t offset);\n\n", s.ScanAny)
			fmt.Fprintf(&cb, `int %[1]s(const char *input, size_t len, size_t offset) {
    return ffi_%[1]s(input, (int)len, (int)offset);
}
`, s.ScanAny)
		}
		if s.ScanAll != "" {
			if wide {
				imp(s.ScanAll, fmt.Sprintf("int ffi_%s(const char *ptr, int len, int from, unsigned char *bits);", s.ScanAll))
			} else {
				imp(s.ScanAll, fmt.Sprintf("long long ffi_%s(const char *ptr, int len, int from);", s.ScanAll))
			}
			fmt.Fprintf(&hb, "/* Writes the matching pattern ids into patterns and returns how many.\n   See match_all for why the size is in the type. */\nint %s(const char *input, size_t len, size_t offset, int patterns[static %s]);\n\n", s.ScanAll, konst)
			if wide {
				fmt.Fprintf(&cb, `int %[1]s(const char *input, size_t len, size_t offset, int patterns[static %[3]s]) {
    unsigned char bits[(%[2]s + 7) / 8] = {0};
    int n = ffi_%[1]s(input, (int)len, (int)offset, bits);
    if (n < 0) return n; /* RX_ERR_BT_OVERFLOW: result unknown, not empty */
    int c = 0;
    for (int k = 0; k < %[2]s; k++) if (bits[k / 8] & (1u << (k %% 8))) patterns[c++] = k;
    return c;
}
`, s.ScanAll, idKonst, konst)
			} else {
				fmt.Fprintf(&cb, `int %[1]s(const char *input, size_t len, size_t offset, int patterns[static %[3]s]) {
    unsigned long long mask = (unsigned long long)ffi_%[1]s(input, (int)len, (int)offset);
    int c = 0;
    for (int k = 0; k < %[2]s; k++) if (mask & (1ULL << k)) patterns[c++] = k;
    return c;
}
`, s.ScanAll, idKonst, konst)
			}
		}
		if s.Find != "" {
			scannerType := "rx_" + setConstBase(s.Name) + "_scanner_t"
			gateField, gateInit, gateArg := "", "", ""
			if findGateArray(s) {
				imp(s.Find, fmt.Sprintf("int ffi_%s(const char *ptr, int len, int from, unsigned *gates, int *out, int cap);", s.Find))
				gateField = fmt.Sprintf("    unsigned gates[%s];\n", idKonst)
				gateInit = fmt.Sprintf("    for (size_t k = 0; k < %s; k++) s->gates[k] = 0;\n", idKonst)
				gateArg = "s->gates, "
			} else {
				imp(s.Find, fmt.Sprintf("int ffi_%s(const char *ptr, int len, int from, int *out, int cap);", s.Find))
			}
			// D17: the scanner is CALLER-owned, so two scans can be in flight
			// and re-initialising the struct restarts one. The static
			// _next/_reset pair this replaces could do neither.
			//
			// The TUPLE BUFFER is the caller's too, for the reason §19.6 gives
			// for find_batch: a header with no allocator can only own storage
			// whose size is known at compile time, and PATTERN_COUNT tuples of
			// a several-thousand-pattern set is tens of kilobytes to bury in a
			// struct the caller is invited to put on the stack. The GATE array
			// stays inside — its length is a size the compiler knows, not one
			// the caller picks.
			//
			// Unlike find_batch, the buffer has a MINIMUM: `find` is
			// transactional (SETS §3.11), so a position reporting more matches
			// than fit records no gate and writes no complete answer, and the
			// scan cannot step past it. PATTERN_COUNT is that worst case
			// exactly — one match per pattern at one start.
			fmt.Fprintf(&hb, `/* Caller-owned scanner for %[1]s. Two scans may be in flight at once, and
   re-initialising the struct restarts a scan.

   The scanner holds the INPUT as well as the position (decision (5)): the
   input never changes during a scan while the position changes every step, so
   the old split — remembering the position and taking the input on every
   step — was backwards, and let a caller pass a DIFFERENT buffer on a later
   step with the stored position silently indexing into it.

   %[1]s fills your array with every match at the FIRST position at or after
   the scanner's offset — they all share that start — and returns HOW MANY.
   0 means the scan is finished. The return is the position's TOTAL, which may
   exceed cap: the underlying call is transactional, so it writes min(total,
   cap), records nothing and does not advance, and n > cap means "grow and call
   again, same position". Sizing cap at %[2]s makes overflow impossible.

       rx_set_match_t buf[%[2]s];
       %[4]s sc;
       if (%[1]s_init(&sc, input, len, 0) != 0) { ... }
       for (int n; (n = %[1]s(&sc, buf, %[2]s)) > 0; )
           for (int i = 0; i < n; i++) { ... buf[i] ... }  */
typedef struct {
    const char *input;
    size_t len, offset;
    int done;
%[3]s} %[4]s;

/* 0 on success, a negative RX_ERR_* otherwise. An EMPTY input is legitimate
   (a*, (?:), x?, \\A\\z all match it) and offset > len is not an error either
   — the ABI defines it as "nothing found". */
int %[1]s_init(%[4]s *s, const char *input, size_t len, size_t offset);
int %[1]s(%[4]s *s, rx_set_match_t *buf, size_t cap);

`, s.Find, konst, gateField, scannerType)
			fmt.Fprintf(&cb, `int %[1]s_init(%[2]s *s, const char *input, size_t len, size_t offset) {
    if (!s || !input) return RX_ERR_NULL_ARG;
    /* The FFI imports are i32. */
    if (len > 0x7FFFFFFF || offset > 0x7FFFFFFF) return RX_ERR_RANGE;
    s->input = input; s->len = len; s->offset = offset; s->done = 0;
%[3]s    return 0;
}

int %[1]s(%[2]s *s, rx_set_match_t *buf, size_t cap) {
    if (!s || !buf) return RX_ERR_NULL_ARG;
    if (cap > 0x7FFFFFFF) return RX_ERR_RANGE;
    if (s->done) return 0;
    int got = ffi_%[1]s(s->input, (int)s->len, (int)s->offset, %[4]s(int *)buf, (int)cap);
    /* Negative is RX_ERR_BT_OVERFLOW, not a count: a Backtracking member of
       this set exhausted its frame budget, so what remains is UNKNOWN rather
       than nothing. Folding it into the "0 means finished" test below would
       end the scan silently and report success. */
    if (got < 0) { s->done = 1; return got; }
    if (got == 0) { s->done = 1; return 0; }
    /* Over capacity: nothing was recorded and the scan did not advance, so the
       caller can grow and repeat at this same position. */
    if ((size_t)got > cap) return got;
    /* The module writes 12-byte {id, start, end} tuples. On wasm32 ptrdiff_t
       is 4 bytes, rx_set_match_t IS that layout, and the answer is already in
       place — the branch below folds away. Anywhere else (a host build for an
       editor or a static check) the structs are wider, so expand in place from
       the LAST element backwards: entry i occupies bytes [i*S, (i+1)*S) with
       S >= 12 while its ints sit at [i*12, i*12+12), so writing downward never
       clobbers a triple not yet read. */
    if (sizeof(rx_set_match_t) != 12) {
        const int *raw = (const int *)buf;
        for (int i = got - 1; i >= 0; i--) {
            int id = raw[i * 3], st = raw[i * 3 + 1], en = raw[i * 3 + 2];
            buf[i].pattern_id = id;
            buf[i].start = (ptrdiff_t)st;
            buf[i].end = (ptrdiff_t)en;
        }
    }
    /* Every tuple in one call shares a start; resume one past it. */
    s->offset = (size_t)buf[0].start + 1;
    return got;
}
`, s.Find, scannerType, gateInit, gateArg)
		}
	}
	if hasEmitNameMap(cfg) {
		hb.WriteString("const char *pattern_name(int id);\n\n")
		cb.WriteString("static const char *_pattern_names[] = {")
		for i, re := range cfg.Regexps {
			if i > 0 {
				cb.WriteString(", ")
			}
			fmt.Fprintf(&cb, "%q", re.Name)
		}
		cb.WriteString("};\nconst char *pattern_name(int id) { int n=sizeof(_pattern_names)/sizeof(*_pattern_names); return (id>=0&&id<n)?_pattern_names[id]:\"\"; }\n")
	}
	hContent = hb.String()
	cContent = cb.String()
	return
}

// genCPartsForEntry generates the .h and .c fragments for one regexp entry.
func genCPartsForEntry(re config.RegexEntry, importModule string) (hPart, cPart string, err error) {
	if re.NamedGroupsFunc != "" {
		return "", "", fmt.Errorf("named_groups_func is not supported for C stubs; use groups_func instead")
	}

	var hb, cb strings.Builder

	if re.MatchFunc != "" {
		hb.WriteString(genCMatchHPart(re.MatchFunc))
		cb.WriteString(genCMatchCPart(importModule, re.MatchFunc))
	}
	if re.FindFunc != "" {
		hb.WriteString(genCFindHPart(re.FindFunc))
		cb.WriteString(genCFindCPart(importModule, re.FindFunc))
	}
	if re.GroupsFunc != "" {
		exportName := re.GroupsExportName()
		numGroups, namedGroups, e := extractGroupInfo(re.Pattern)
		if e != nil {
			return "", "", e
		}
		h, c := genCGroupsStubParts(importModule, re.GroupsFunc, exportName, numGroups, namedGroups)
		hb.WriteString(h)
		cb.WriteString(c)
	}
	return hb.String(), cb.String(), nil
}

// genCMatchHPart generates the .h prototype for an anchored-match function.
func genCMatchHPart(funcName string) string {
	return fmt.Sprintf(
		"/* %s: anchored match. Returns end position (>=0), -1 if no match, or\n"+
			"   RX_ERR_BT_OVERFLOW (see above) if the match result is unknown. */\n"+
			"ptrdiff_t %s(const char *input, size_t len);\n\n",
		funcName, funcName)
}

// genCMatchCPart generates the .c FFI declaration and wrapper for an anchored-match function.
func genCMatchCPart(importModule, funcName string) string {
	ffi := "_ffi_" + funcName
	var sb strings.Builder
	fmt.Fprintf(&sb, "__attribute__((import_module(\"%s\"), import_name(\"%s\")))\n", importModule, funcName)
	fmt.Fprintf(&sb, "extern int %s(const unsigned char *ptr, unsigned int len);\n\n", ffi)
	fmt.Fprintf(&sb, "ptrdiff_t %s(const char *input, size_t len) {\n", funcName)
	fmt.Fprintf(&sb, "    return %s((const unsigned char *)input, (unsigned int)len);\n", ffi)
	sb.WriteString("}\n\n")
	return sb.String()
}

// genCFindHPart generates the .h prototype for a non-anchored find function.
func genCFindHPart(funcName string) string {
	return fmt.Sprintf(
		"/* %s: non-anchored find from offset.\n"+
			"   Returns absolute {start, end}, {-1, -1} if not found, or\n"+
			"   {RX_ERR_BT_OVERFLOW, RX_ERR_BT_OVERFLOW} if the result is unknown.\n"+
			"   To iterate non-overlapping matches, advance past each match; a pattern\n"+
			"   that can match empty needs the guard, or offset never moves:\n"+
			"     off = m.end > m.start ? m.end : m.start + 1;\n"+
			"   To match Go's FindAllIndex exactly, also SKIP an empty match that\n"+
			"   begins where the previous reported match ended:\n"+
			"     if (m.start == m.end && m.start == prev_end) continue;\n"+
			"     prev_end = m.end; */\n"+
			"rx_match_t %s(const char *input, size_t len, size_t offset);\n\n",
		funcName, funcName)
}

// genCFindCPart generates the .c FFI declaration and wrapper for a non-anchored find function.
func genCFindCPart(importModule, funcName string) string {
	ffi := "_ffi_" + funcName
	var sb strings.Builder
	fmt.Fprintf(&sb, "__attribute__((import_module(\"%s\"), import_name(\"%s\")))\n", importModule, funcName)
	fmt.Fprintf(&sb, "extern long long %s(const unsigned char *ptr, unsigned int len, unsigned int from);\n\n", ffi)
	fmt.Fprintf(&sb, "rx_match_t %s(const char *input, size_t len, size_t offset) {\n", funcName)
	sb.WriteString("    if (offset > len) return (rx_match_t){-1, -1};\n")
	fmt.Fprintf(&sb, "    long long r = %s((const unsigned char *)input, (unsigned int)len, (unsigned int)offset);\n", ffi)
	sb.WriteString("    if (r == RX_ERR_BT_OVERFLOW) return (rx_match_t){RX_ERR_BT_OVERFLOW, RX_ERR_BT_OVERFLOW};\n")
	sb.WriteString("    if (r < 0) return (rx_match_t){-1, -1};\n")
	// Whole buffer plus a start position, so these are already absolute.
	sb.WriteString("    unsigned int abs_s = (unsigned int)((unsigned long long)r >> 32);\n")
	sb.WriteString("    unsigned int abs_e = (unsigned int)(r & 0xFFFFFFFFU);\n")
	sb.WriteString("    return (rx_match_t){(ptrdiff_t)abs_s, (ptrdiff_t)abs_e};\n")
	sb.WriteString("}\n\n")
	return sb.String()
}

// toUpperIdent returns s with all lowercase ASCII letters uppercased.
func toUpperIdent(s string) string {
	var b strings.Builder
	for _, c := range s {
		if c >= 'a' && c <= 'z' {
			b.WriteRune(c - 32)
		} else {
			b.WriteRune(c)
		}
	}
	return b.String()
}

// cGroupConst returns the C constant name for a named capture group.
// e.g. funcName="parse_url", groupName="host" → "PARSE_URL_GROUP_HOST"
func cGroupConst(funcName, groupName string) string {
	return toUpperIdent(funcName) + "_GROUP_" + toUpperIdent(groupName)
}

// genCGroupsStubParts generates the .h and .c fragments for a capture-groups function.
// Both groups_func and named_groups_func entries are handled identically: the generated
// wrapper scans from offset and fills a static rx_group_t array.
// Named groups have their name field pointing to a public char array constant; others are NULL.
func genCGroupsStubParts(importModule, funcName, exportName string, numGroups int, namedGroups map[string]int) (hPart, cPart string) {
	type namedGroup struct {
		name  string
		index int // 1-based capture group index
	}
	var named []namedGroup
	for n, idx := range namedGroups {
		named = append(named, namedGroup{n, idx})
	}
	sort.Slice(named, func(i, j int) bool { return named[i].index < named[j].index })

	funcUpper := toUpperIdent(funcName)
	slotCount := numGroups * 2
	ffi := "_ffi_" + exportName
	namesVar := "_" + funcName + "_names"

	var hb, cb strings.Builder

	// .h: group name constants
	if len(named) > 0 {
		fmt.Fprintf(&hb, "/* Group name constants for %s */\n", funcName)
		for _, g := range named {
			fmt.Fprintf(&hb, "extern const char * const %s;\n", cGroupConst(funcName, g.name))
		}
		hb.WriteString("\n")
	}

	// .h: groups count macro
	fmt.Fprintf(&hb, "#define %s_GROUPS %d\n\n", funcUpper, numGroups)

	// .h: function prototype and doc comment
	fmt.Fprintf(&hb,
		"/* %s: find next capture match from offset.\n"+
			"   Returns pointer to a static array of %s_GROUPS rx_group_t entries.\n"+
			"   groups[0] is the full match; subsequent entries are capture groups in order.\n"+
			"   Named groups have their name field pointing to the corresponding %s_GROUP_* constant;\n"+
			"   use == for identity comparison. Unnamed groups have name == NULL.\n"+
			"   All entries are {-1, -1, ...} when no match is found starting from offset.\n"+
			"   Returns NULL (never returned otherwise) if the Backtracking engine\n"+
			"   exhausted its frame budget -- see RX_ERR_BT_OVERFLOW above.\n"+
			"   To iterate non-overlapping matches, advance past each match; a pattern\n"+
			"   that can match empty needs the guard, or offset never moves:\n"+
			"     off = groups[0].end > groups[0].start ? groups[0].end\n"+
			"                                          : groups[0].start + 1;\n"+
			"   To match Go's FindAllSubmatchIndex exactly, also SKIP an empty match\n"+
			"   that begins where the previous reported match ended:\n"+
			"     if (groups[0].start == groups[0].end &&\n"+
			"         groups[0].start == prev_end) continue;\n"+
			"     prev_end = groups[0].end; */\n"+
			"const rx_group_t *%s(const char *input, size_t len, size_t offset, rx_group_t *out);\n\n",
		funcName, funcUpper, funcUpper, funcName)

	// .c: group name constant definitions
	if len(named) > 0 {
		fmt.Fprintf(&cb, "/* Group name constants for %s */\n", funcName)
		for _, g := range named {
			fmt.Fprintf(&cb, "const char * const %s = \"%s\";\n", cGroupConst(funcName, g.name), g.name)
		}
		cb.WriteString("\n")
	}

	// .c: internal name table (index → name pointer; NULL for group 0 and unnamed groups)
	// Using char array addresses (not pointer variables) ensures stable identity comparison.
	groupConstByIdx := make(map[int]string, len(named))
	for _, g := range named {
		groupConstByIdx[g.index] = cGroupConst(funcName, g.name)
	}
	fmt.Fprintf(&cb, "static const char * const %s[%d] = {\n", namesVar, numGroups)
	for i := 0; i < numGroups; i++ {
		if constName, ok := groupConstByIdx[i]; ok {
			fmt.Fprintf(&cb, "    %s,\n", constName)
		} else {
			cb.WriteString("    (const char *)0,\n")
		}
	}
	cb.WriteString("};\n\n")

	// .c: FFI declaration
	fmt.Fprintf(&cb, "__attribute__((import_module(\"%s\"), import_name(\"%s\")))\n", importModule, exportName)
	fmt.Fprintf(&cb, "extern int %s(const unsigned char *ptr, unsigned int len, int *out, unsigned int from);\n\n", ffi)

	// .c: wrapper function
	// Decision (8): the caller supplies the array. The `static rx_group_t`
	// this replaces was the last mutable static in generated C — two threads
	// corrupted each other and a second call invalidated the first result.
	//
	// NOTE this does NOT make the C stubs thread-safe: the Backtracking engine
	// keeps its stack at a fixed stackBase and its BitState memo at a fixed
	// memoTableBase (compile/engine_backtrack.go), so BT-compiled patterns
	// stay non-reentrant at the WASM level. Claim re-entrancy, not
	// thread-safety.
	fmt.Fprintf(&cb, "const rx_group_t *%s(const char *input, size_t len, size_t offset, rx_group_t *out) {\n", funcName)
	cb.WriteString("    if (!input || !out) return (const rx_group_t *)0;\n")
	fmt.Fprintf(&cb, "    int slots[%d];\n", slotCount)
	cb.WriteString("    size_t pos = offset;\n")
	cb.WriteString("    while (pos <= len) {\n")
	fmt.Fprintf(&cb, "        for (int i = 0; i < %d; i++) slots[i] = -1;\n", slotCount)
	// Whole buffer plus a start position; slots come back absolute.
	fmt.Fprintf(&cb, "        int r = %s((const unsigned char *)input, (unsigned int)len, slots, (unsigned int)pos);\n", ffi)
	cb.WriteString("        if (r == RX_ERR_BT_OVERFLOW) return (const rx_group_t *)0;\n")
	cb.WriteString("        if (r >= 0) {\n")
	fmt.Fprintf(&cb, "            for (int i = 0; i < %d; i++) {\n", numGroups)
	fmt.Fprintf(&cb, "                out[i].name = %s[i];\n", namesVar)
	cb.WriteString("                if (slots[i*2] >= 0) {\n")
	cb.WriteString("                    out[i].start = (ptrdiff_t)slots[i*2];\n")
	cb.WriteString("                    out[i].end   = (ptrdiff_t)slots[i*2+1];\n")
	cb.WriteString("                } else {\n")
	cb.WriteString("                    out[i].start = -1;\n")
	cb.WriteString("                    out[i].end   = -1;\n")
	cb.WriteString("                }\n")
	cb.WriteString("            }\n")
	cb.WriteString("            return out;\n")
	cb.WriteString("        }\n")
	cb.WriteString("        if (pos == len) break;\n")
	cb.WriteString("        pos++;\n")
	cb.WriteString("    }\n")
	// No match: set all entries to -1/-1 with names
	fmt.Fprintf(&cb, "    for (int i = 0; i < %d; i++) {\n", numGroups)
	cb.WriteString("        out[i].start = -1;\n")
	cb.WriteString("        out[i].end   = -1;\n")
	fmt.Fprintf(&cb, "        out[i].name  = %s[i];\n", namesVar)
	cb.WriteString("    }\n")
	cb.WriteString("    return out;\n")
	cb.WriteString("}\n\n")

	return hb.String(), cb.String()
}
