package generate

import (
	"fmt"
	"sort"
	"strings"

	"github.com/qrdl/regexped/config"
)

// cStub generates a C header stub file for all regex entries in cfg.
// out is the full output path or "-" for stdout.
func cStub(cfg config.BuildConfig, out string) error {
	content, err := genCStubFile(cfg.Regexes, cfg.ImportModule)
	if err != nil {
		return fmt.Errorf("generate C stub: %w", err)
	}
	if content == "" {
		return nil
	}
	if out == "-" {
		_, err := fmt.Print(content)
		return err
	}
	return writeStub(out, []byte(content))
}

// genCStubFile generates the content of a C header stub file for a slice of entries.
func genCStubFile(entries []config.RegexEntry, importModule string) (string, error) {
	if len(entries) == 0 {
		return "", nil
	}

	var parts []string
	needsStreq := false
	for _, re := range entries {
		part, err := genCStubsForEntry(re, importModule)
		if err != nil {
			return "", err
		}
		if part != "" {
			parts = append(parts, part)
			if re.NamedGroupsFunc != "" {
				needsStreq = true
			}
		}
	}
	if len(parts) == 0 {
		return "", nil
	}

	var sb strings.Builder
	sb.WriteString("/* Auto-generated by regexped. Do not edit. */\n")
	sb.WriteString("#pragma once\n\n")
	if needsStreq {
		sb.WriteString("static int _rx_streq(const char *a, const char *b) {\n")
		sb.WriteString("    while (*a && *a == *b) { a++; b++; }\n")
		sb.WriteString("    return *a == *b;\n")
		sb.WriteString("}\n\n")
	}
	sb.WriteString(strings.Join(parts, ""))
	return sb.String(), nil
}

// genCStubsForEntry generates the C stub content for a single regex entry.
func genCStubsForEntry(re config.RegexEntry, importModule string) (string, error) {
	var out string
	written := false

	if re.MatchFunc != "" {
		out += genCMatchStub(importModule, re.MatchFunc)
		written = true
	}
	if re.FindFunc != "" {
		out += genCFindStub(importModule, re.FindFunc)
		written = true
	}
	if re.GroupsFunc != "" || re.NamedGroupsFunc != "" {
		numGroups, namedGroups, err := extractGroupInfo(re.Pattern)
		if err != nil {
			return "", err
		}
		exportName := re.GroupsExportName()
		if re.GroupsFunc != "" {
			out += genCGroupsStub(importModule, re.GroupsFunc, exportName, true, numGroups)
			written = true
		}
		if re.NamedGroupsFunc != "" {
			declareFFI := re.GroupsFunc == ""
			out += genCNamedGroupsStub(importModule, re.NamedGroupsFunc, exportName, declareFFI, numGroups, namedGroups)
			written = true
		}
	}

	if !written {
		return "", nil
	}
	return out, nil
}

// genCMatchStub generates an anchored-match C stub.
func genCMatchStub(importModule, funcName string) string {
	ffi := "_ffi_" + funcName
	var sb strings.Builder
	fmt.Fprintf(&sb, "__attribute__((import_module(\"%s\"), import_name(\"%s\")))\n", importModule, funcName)
	fmt.Fprintf(&sb, "extern int %s(const unsigned char *ptr, unsigned int len);\n\n", ffi)
	fmt.Fprintf(&sb, "/* Returns end position of the match (>=0), or -1 if no match. Anchored at start. */\n")
	fmt.Fprintf(&sb, "static int %s(const unsigned char *input, unsigned int len) {\n", funcName)
	fmt.Fprintf(&sb, "    return %s(input, len);\n", ffi)
	sb.WriteString("}\n\n")
	return sb.String()
}

// genCFindStub generates a find iterator C stub with static offset state.
func genCFindStub(importModule, funcName string) string {
	ffi := "_ffi_" + funcName
	off := "_" + funcName + "_off"
	var sb strings.Builder
	fmt.Fprintf(&sb, "__attribute__((import_module(\"%s\"), import_name(\"%s\")))\n", importModule, funcName)
	fmt.Fprintf(&sb, "extern long long %s(const unsigned char *ptr, unsigned int len);\n\n", ffi)
	fmt.Fprintf(&sb, "static unsigned int %s;\n\n", off)
	fmt.Fprintf(&sb, "/* Resets the %s iterator. Call before the first %s_next(). */\n", funcName, funcName)
	fmt.Fprintf(&sb, "static void %s_reset(void) { %s = 0; }\n\n", funcName, off)
	fmt.Fprintf(&sb, "/* Advances to the next match; sets *start and *end to absolute byte offsets.\n")
	fmt.Fprintf(&sb, "   Returns 1 if a match was found, 0 when exhausted. */\n")
	fmt.Fprintf(&sb, "static int %s_next(const unsigned char *input, unsigned int len,\n", funcName)
	fmt.Fprintf(&sb, "                   unsigned int *start, unsigned int *end) {\n")
	fmt.Fprintf(&sb, "    while (%s <= len) {\n", off)
	fmt.Fprintf(&sb, "        long long r = %s(input + %s, len - %s);\n", ffi, off, off)
	fmt.Fprintf(&sb, "        if (r < 0) { %s = len + 1; return 0; }\n", off)
	sb.WriteString("        unsigned int rel_s = (unsigned int)((unsigned long long)r >> 32);\n")
	sb.WriteString("        unsigned int rel_e = (unsigned int)(r & 0xFFFFFFFFU);\n")
	fmt.Fprintf(&sb, "        *start = %s + rel_s;\n", off)
	fmt.Fprintf(&sb, "        *end   = %s + rel_e;\n", off)
	fmt.Fprintf(&sb, "        %s += (rel_e > rel_s) ? rel_e : rel_s + 1;\n", off)
	sb.WriteString("        return 1;\n")
	sb.WriteString("    }\n")
	sb.WriteString("    return 0;\n")
	sb.WriteString("}\n\n")
	return sb.String()
}

// genCGroupsStub generates a capture-groups iterator C stub.
// declareFFI controls whether the extern declaration is emitted.
func genCGroupsStub(importModule, funcName, exportName string, declareFFI bool, numGroups int) string {
	ffi := "_ffi_" + exportName
	off := "_" + funcName + "_off"
	slotsDefine := strings.ToUpper(funcName) + "_SLOTS"
	slotCount := numGroups * 2

	var sb strings.Builder
	fmt.Fprintf(&sb, "#define %s %d\n\n", slotsDefine, slotCount)
	if declareFFI {
		fmt.Fprintf(&sb, "__attribute__((import_module(\"%s\"), import_name(\"%s\")))\n", importModule, exportName)
		fmt.Fprintf(&sb, "extern int %s(const unsigned char *ptr, unsigned int len, int *out);\n\n", ffi)
	}
	fmt.Fprintf(&sb, "static unsigned int %s;\n\n", off)
	fmt.Fprintf(&sb, "/* Resets the %s iterator. Call before the first %s_next(). */\n", funcName, funcName)
	fmt.Fprintf(&sb, "static void %s_reset(void) { %s = 0; }\n\n", funcName, off)
	fmt.Fprintf(&sb, "/* Advances to the next match; fills slots[0..%s-1].\n", slotsDefine)
	fmt.Fprintf(&sb, "   slots[i*2] and slots[i*2+1] are start/end for group i (absolute); -1 if absent.\n")
	fmt.Fprintf(&sb, "   Returns 1 if a match was found, 0 when exhausted. */\n")
	fmt.Fprintf(&sb, "static int %s_next(const unsigned char *input, unsigned int len, int *slots) {\n", funcName)
	fmt.Fprintf(&sb, "    while (%s <= len) {\n", off)
	fmt.Fprintf(&sb, "        int r = %s(input + %s, len - %s, slots);\n", ffi, off, off)
	fmt.Fprintf(&sb, "        if (r < 0) {\n")
	fmt.Fprintf(&sb, "            if (%s == len) { %s = len + 1; return 0; }\n", off, off)
	fmt.Fprintf(&sb, "            %s++; continue;\n", off)
	fmt.Fprintf(&sb, "        }\n")
	fmt.Fprintf(&sb, "        unsigned int off = %s;\n", off)
	fmt.Fprintf(&sb, "        for (int i = 0; i < %s; i++)\n", slotsDefine)
	sb.WriteString("            if (slots[i] >= 0) slots[i] += (int)off;\n")
	sb.WriteString("        unsigned int end = (slots[1] >= 0) ? (unsigned int)slots[1] : off + 1;\n")
	fmt.Fprintf(&sb, "        %s = (end > off) ? end : off + 1;\n", off)
	sb.WriteString("        return 1;\n")
	sb.WriteString("    }\n")
	sb.WriteString("    return 0;\n")
	sb.WriteString("}\n\n")
	return sb.String()
}

// genCNamedGroupsStub generates a named-capture-groups iterator C stub.
// declareFFI controls whether the extern declaration is emitted.
func genCNamedGroupsStub(importModule, funcName, exportName string, declareFFI bool, numGroups int, namedGroups map[string]int) string {
	// The iteration part is identical to groups; reuse genCGroupsStub for the body.
	out := genCGroupsStub(importModule, funcName, exportName, declareFFI, numGroups)

	type entry struct {
		name  string
		index int
	}
	var entries []entry
	for name, idx := range namedGroups {
		entries = append(entries, entry{name, idx})
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].index < entries[j].index })

	var sb strings.Builder
	fmt.Fprintf(&sb, "/* Looks up a named group in slots filled by %s_next().\n", funcName)
	fmt.Fprintf(&sb, "   Returns 1 and sets *start / *end if captured; 0 if absent or unknown name. */\n")
	fmt.Fprintf(&sb, "static int %s_get(const int *slots, const char *name, int *start, int *end) {\n", funcName)
	sb.WriteString("    int idx = -1;\n")
	for i, e := range entries {
		if i == 0 {
			fmt.Fprintf(&sb, "    if (_rx_streq(name, \"%s\")) idx = %d;\n", e.name, e.index)
		} else {
			fmt.Fprintf(&sb, "    else if (_rx_streq(name, \"%s\")) idx = %d;\n", e.name, e.index)
		}
	}
	sb.WriteString("    if (idx < 0 || slots[idx*2] < 0) return 0;\n")
	sb.WriteString("    *start = slots[idx*2];\n")
	sb.WriteString("    *end   = slots[idx*2+1];\n")
	sb.WriteString("    return 1;\n")
	sb.WriteString("}\n\n")
	return out + sb.String()
}
