package generate

import (
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"regexp/syntax"
	"strings"

	"github.com/qrdl/regexped/config"
)

// ResolveStubType determines the stub type from cfg.StubType or the extension
// of cfg.StubFile. Returns one of "rust", "js", "ts", or an error.
func ResolveStubType(cfg config.BuildConfig) (string, error) {
	if cfg.StubType != "" {
		switch cfg.StubType {
		case "rust", "js", "ts":
			return cfg.StubType, nil
		default:
			return "", fmt.Errorf("unknown stub_type %q (expected rust, js, or ts)", cfg.StubType)
		}
	}
	ext := strings.ToLower(filepath.Ext(cfg.StubFile))
	switch ext {
	case ".rs":
		return "rust", nil
	case ".js":
		return "js", nil
	case ".ts":
		return "ts", nil
	default:
		return "", fmt.Errorf("cannot infer stub type from %q: set stub_type in config (rust, js, or ts)", cfg.StubFile)
	}
}

// CmdGenerateStub generates a stub file of the appropriate type for cfg.
// out is the full output path or "-" for stdout.
func CmdGenerateStub(cfg config.BuildConfig, out string) error {
	stubType, err := ResolveStubType(cfg)
	if err != nil {
		return err
	}
	switch stubType {
	case "rust":
		return CmdStub(cfg, out)
	case "js":
		return CmdJS(cfg, out)
	case "ts":
		return CmdTS(cfg, out)
	}
	return fmt.Errorf("unknown stub type: %s", stubType)
}

// CmdStub generates a Rust stub file for all regex entries in cfg.
// out is the full output path or "-" for stdout.
func CmdStub(cfg config.BuildConfig, out string) error {
	content, err := genRustStubFile(cfg.Regexes, cfg.ImportModule)
	if err != nil {
		return fmt.Errorf("generate Rust stub: %w", err)
	}
	if content == "" {
		return nil
	}
	if out == "-" {
		_, err := os.Stdout.WriteString(content)
		return err
	}
	return writeStub(out, []byte(content))
}

// CmdTS generates a TypeScript ES module stub file for all regex entries in cfg.
// out is the full output path or "-" for stdout.
func CmdTS(cfg config.BuildConfig, out string) error {
	content, err := genTSStubFile(cfg)
	if err != nil {
		return fmt.Errorf("generate TS stub: %w", err)
	}
	if out == "-" {
		_, err := os.Stdout.WriteString(content)
		return err
	}
	return writeStub(out, []byte(content))
}

// CmdJS generates a JS ES module stub file for all regex entries in cfg.
// out is the full output path or "-" for stdout.
func CmdJS(cfg config.BuildConfig, out string) error {
	content, err := genJSStubFile(cfg)
	if err != nil {
		return fmt.Errorf("generate JS stub: %w", err)
	}
	if out == "-" {
		_, err := os.Stdout.WriteString(content)
		return err
	}
	return writeStub(out, []byte(content))
}

// genRustStubFile generates the content of a Rust stub file for a slice of entries.
// All entries are wrapped in a single pub mod <importModule> { } block.
func genRustStubFile(entries []config.RegexEntry, importModule string) (string, error) {
	if len(entries) == 0 {
		return "", nil
	}

	var bodyParts []string
	for _, re := range entries {
		body, err := genRustStubsForEntry(re, importModule)
		if err != nil {
			return "", err
		}
		if body != "" {
			bodyParts = append(bodyParts, body)
		}
	}
	if len(bodyParts) == 0 {
		return "", nil
	}

	combined := strings.TrimRight(strings.Join(bodyParts, ""), "\n")

	header := "// Auto-generated by regexped. Do not edit.\n\n"
	var out strings.Builder
	out.WriteString(header)
	fmt.Fprintf(&out, "pub mod %s {\n", importModule)
	for _, line := range strings.Split(combined, "\n") {
		if line == "" {
			out.WriteString("\n")
		} else {
			fmt.Fprintf(&out, "    %s\n", line)
		}
	}
	out.WriteString("}\n")
	return out.String(), nil
}

// genRustStubsForEntry generates the Rust stub content for a single entry.
func genRustStubsForEntry(re config.RegexEntry, importModule string) (string, error) {
	var out string
	written := false

	if re.MatchFunc != "" {
		out += genRustMatchStub(importModule, re.MatchFunc)
		written = true
	}
	if re.FindFunc != "" {
		out += genRustFindIterStub(importModule, re.FindFunc)
		written = true
	}
	if re.GroupsFunc != "" || re.NamedGroupsFunc != "" {
		numGroups, namedGroups, err := extractGroupInfo(re.Pattern)
		if err != nil {
			return "", err
		}
		exportName := re.GroupsExportName()
		if re.GroupsFunc != "" {
			out += genRustGroupsIterStub(importModule, re.GroupsFunc, exportName, true, numGroups)
			written = true
		}
		if re.NamedGroupsFunc != "" {
			// Only declare the FFI if groups_func didn't already declare it.
			declareFFI := re.GroupsFunc == ""
			out += genRustNamedGroupsIterStub(importModule, re.NamedGroupsFunc, exportName, declareFFI, numGroups, namedGroups)
			written = true
		}
	}

	if !written {
		return "", nil
	}
	return out, nil
}

// writeStub creates the parent directory and writes data to path.
func writeStub(path string, data []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", filepath.Dir(path), err)
	}
	if err := os.WriteFile(path, data, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	slog.Info("Written stub", "file", path)
	return nil
}

// extractGroupInfo parses the pattern and returns:
// - numGroups: total number of capture groups including group 0
// - namedGroups: map from name to group index (1-based) for named groups
func extractGroupInfo(pattern string) (int, map[string]int, error) {
	re, err := syntax.Parse(pattern, syntax.Perl)
	if err != nil {
		return 0, nil, fmt.Errorf("parse pattern: %w", err)
	}
	numGroups := re.MaxCap() + 1 // +1 for group 0
	named := make(map[string]int)
	collectNamedGroups(re, named)
	return numGroups, named, nil
}

func collectNamedGroups(re *syntax.Regexp, named map[string]int) {
	if re.Op == syntax.OpCapture && re.Name != "" {
		named[re.Name] = re.Cap
	}
	for _, sub := range re.Sub {
		collectNamedGroups(sub, named)
	}
}
