package generate

import (
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"regexp/syntax"

	"github.com/qrdl/regexped/config"
)

// CmdStub generates Rust stub files for each regex in cfg.
func CmdStub(cfg config.BuildConfig, outDir string, rust bool) error {
	if !rust {
		return nil
	}
	if err := os.MkdirAll(filepath.Join(outDir, "src"), 0o755); err != nil {
		return fmt.Errorf("mkdir %s/src: %w", outDir, err)
	}
	for _, re := range cfg.Regexes {
		if re.StubFile == "" {
			continue
		}
		content, err := genRustStubsForEntry(re)
		if err != nil {
			return fmt.Errorf("generate stub for %s: %w", re.ImportModule, err)
		}
		if content == "" {
			continue
		}
		stubPath := filepath.Join(outDir, "src", re.StubFile)
		if err := os.WriteFile(stubPath, []byte(content), 0o644); err != nil {
			return fmt.Errorf("write %s: %w", stubPath, err)
		}
		slog.Info("Written stub", "file", stubPath)
	}
	return nil
}

// genRustStubsForEntry generates all requested Rust stubs for a single entry.
func genRustStubsForEntry(re config.RegexEntry) (string, error) {
	var out string
	header := fmt.Sprintf("// Auto-generated by regexped. Do not edit.\n// Pattern: %s\n\n", re.Pattern)
	written := false

	if re.MatchFunc != "" {
		out += genRustMatchStub(re.Pattern, re.ImportModule, re.MatchFunc)
		written = true
	}
	if re.FindFunc != "" {
		out += genRustFindStubs(re.Pattern, re.ImportModule, re.FindFunc)
		written = true
	}
	if re.GroupsFunc != "" || re.NamedGroupsFunc != "" {
		numGroups, namedGroups, err := extractGroupInfo(re.Pattern)
		if err != nil {
			return "", err
		}
		if re.GroupsFunc != "" {
			out += genRustGroupsStub(re.Pattern, re.ImportModule, re.GroupsFunc, numGroups)
			written = true
		}
		if re.NamedGroupsFunc != "" {
			out += genRustNamedGroupsStub(re.Pattern, re.ImportModule, re.NamedGroupsFunc, numGroups, namedGroups)
			written = true
		}
	}

	if !written {
		return "", nil
	}
	return header + out, nil
}

// extractGroupInfo parses the pattern and returns:
// - numGroups: total number of capture groups including group 0
// - namedGroups: map from name to group index (1-based) for named groups
func extractGroupInfo(pattern string) (int, map[string]int, error) {
	re, err := syntax.Parse(pattern, syntax.Perl)
	if err != nil {
		return 0, nil, fmt.Errorf("parse pattern: %w", err)
	}
	numGroups := re.MaxCap() + 1 // +1 for group 0
	named := make(map[string]int)
	collectNamedGroups(re, named)
	return numGroups, named, nil
}

func collectNamedGroups(re *syntax.Regexp, named map[string]int) {
	if re.Op == syntax.OpCapture && re.Name != "" {
		named[re.Name] = re.Cap
	}
	for _, sub := range re.Sub {
		collectNamedGroups(sub, named)
	}
}
