package generate

import (
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"regexp/syntax"
	"strings"

	"github.com/qrdl/regexped/config"
)

// CmdStub generates Rust stub files for each regex in cfg.
// Patterns with a per-entry stub_file go to their own file.
// Patterns using the global stub_file are collected into one file,
// each wrapped in a pub mod <import_module> { } block when there are
// multiple entries sharing the file.
func CmdStub(cfg config.BuildConfig, outDir string) error {
	groups := groupByStubFile(cfg)
	for stubFile, entries := range groups {
		content, err := genRustStubFile(entries)
		if err != nil {
			return fmt.Errorf("generate Rust stub %s: %w", stubFile, err)
		}
		if content == "" {
			continue
		}
		if err := writeStub(outDir, stubFile, []byte(content)); err != nil {
			return err
		}
	}
	return nil
}

// CmdJS generates a single ES module JS stub file for all regex entries.
func CmdJS(cfg config.BuildConfig, outDir string) error {
	if cfg.StubFile == "" {
		return fmt.Errorf("js: stub_file must be set in config (top-level)")
	}
	if cfg.Output == "" {
		return fmt.Errorf("js: output (merged WASM path) must be set in config")
	}
	content, err := genJSStubFile(cfg)
	if err != nil {
		return fmt.Errorf("generate JS stub: %w", err)
	}
	return writeStub(outDir, cfg.StubFile, []byte(content))
}

// groupByStubFile groups RegexEntry values by their effective stub file path.
func groupByStubFile(cfg config.BuildConfig) map[string][]config.RegexEntry {
	groups := make(map[string][]config.RegexEntry)
	for _, re := range cfg.Regexes {
		sf := re.EffectiveStubFile(cfg.StubFile)
		if sf == "" {
			continue
		}
		groups[sf] = append(groups[sf], re)
	}
	return groups
}

// genRustStubFile generates the content of a Rust stub file for a slice of entries.
// If there is more than one entry, each is wrapped in pub mod <import_module> { }.
func genRustStubFile(entries []config.RegexEntry) (string, error) {
	if len(entries) == 0 {
		return "", nil
	}

	header := "// Auto-generated by regexped. Do not edit.\n\n"

	if len(entries) == 1 {
		body, err := genRustStubsForEntry(entries[0])
		if err != nil {
			return "", err
		}
		if body == "" {
			return "", nil
		}
		return header + body, nil
	}

	// Multiple entries: wrap each in a pub mod block.
	var out strings.Builder
	out.WriteString(header)
	for _, re := range entries {
		body, err := genRustStubsForEntry(re)
		if err != nil {
			return "", err
		}
		if body == "" {
			continue
		}
		fmt.Fprintf(&out, "pub mod %s {\n", re.ImportModule)
		for _, line := range strings.Split(strings.TrimRight(body, "\n"), "\n") {
			if line == "" {
				out.WriteString("\n")
			} else {
				fmt.Fprintf(&out, "    %s\n", line)
			}
		}
		out.WriteString("}\n\n")
	}
	return out.String(), nil
}

// genRustStubsForEntry generates the Rust stub content for a single entry.
func genRustStubsForEntry(re config.RegexEntry) (string, error) {
	var out string
	written := false

	if re.MatchFunc != "" {
		out += genRustMatchStub(re.ImportModule, re.MatchFunc)
		written = true
	}
	if re.FindFunc != "" {
		out += genRustFindIterStub(re.ImportModule, re.FindFunc)
		written = true
	}
	if re.GroupsFunc != "" || re.NamedGroupsFunc != "" {
		numGroups, namedGroups, err := extractGroupInfo(re.Pattern)
		if err != nil {
			return "", err
		}
		exportName := re.GroupsExportName()
		if re.GroupsFunc != "" {
			out += genRustGroupsIterStub(re.ImportModule, re.GroupsFunc, exportName, true, numGroups)
			written = true
		}
		if re.NamedGroupsFunc != "" {
			// Only declare the FFI if groups_func didn't already declare it.
			declareFFI := re.GroupsFunc == ""
			out += genRustNamedGroupsIterStub(re.ImportModule, re.NamedGroupsFunc, exportName, declareFFI, numGroups, namedGroups)
			written = true
		}
	}

	if !written {
		return "", nil
	}
	return out, nil
}

// writeStub creates the parent directory and writes data to outDir/stubFile.
func writeStub(outDir, stubFile string, data []byte) error {
	path := filepath.Join(outDir, stubFile)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", filepath.Dir(path), err)
	}
	if err := os.WriteFile(path, data, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	slog.Info("Written stub", "file", path)
	return nil
}

// extractGroupInfo parses the pattern and returns:
// - numGroups: total number of capture groups including group 0
// - namedGroups: map from name to group index (1-based) for named groups
func extractGroupInfo(pattern string) (int, map[string]int, error) {
	re, err := syntax.Parse(pattern, syntax.Perl)
	if err != nil {
		return 0, nil, fmt.Errorf("parse pattern: %w", err)
	}
	numGroups := re.MaxCap() + 1 // +1 for group 0
	named := make(map[string]int)
	collectNamedGroups(re, named)
	return numGroups, named, nil
}

func collectNamedGroups(re *syntax.Regexp, named map[string]int) {
	if re.Op == syntax.OpCapture && re.Name != "" {
		named[re.Name] = re.Cap
	}
	for _, sub := range re.Sub {
		collectNamedGroups(sub, named)
	}
}
