package generate

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"github.com/qrdl/regexped/config"
)

// goStub generates a Go stub file (//go:build wasip1) for all regexp entries in cfg.
// out is the full output path for stub.go, or "-" for stdout.
// The Go package name is set to cfg.ImportModule when the stub is placed in a
// subdirectory named after the import module; otherwise "main" is used.
func goStub(cfg config.BuildConfig, out string) error {
	pkgName := cfg.ImportModule
	if filepath.Base(filepath.Dir(out)) != cfg.ImportModule {
		pkgName = "main"
	}
	singleBody, needsIter, err := genGoStubsBody(cfg.Regexps, cfg.ImportModule)
	if err != nil {
		return fmt.Errorf("generate Go stub: %w", err)
	}
	setBody, setNeedsIter := genGoSetBody(cfg)
	if singleBody == "" && setBody == "" {
		return nil
	}
	needsIter = needsIter || setNeedsIter

	var sb strings.Builder
	sb.WriteString("// Auto-generated by regexped. Do not edit.\n\n")
	sb.WriteString("//go:build wasip1\n\n")
	fmt.Fprintf(&sb, "package %s\n\n", pkgName)
	if needsIter {
		sb.WriteString("import (\n\t\"iter\"\n\t\"unsafe\"\n)\n\n")
	} else {
		sb.WriteString("import \"unsafe\"\n\n")
	}
	sb.WriteString(singleBody)
	sb.WriteString(setBody)
	combined := sb.String()

	if out == "-" {
		_, err := fmt.Print(combined)
		return err
	}
	return writeStub(out, []byte(combined))
}

// genGoSetBody generates Go set wrappers (body only, no file header or imports).
// Returns (body string, needsIter bool).
// Uses unified SetMatch for all match ops; SetAnchorMatch is removed.
func genGoSetBody(cfg config.BuildConfig) (string, bool) {
	if !hasSetExports(cfg) {
		return "", false
	}
	var out strings.Builder
	fmt.Fprintf(&out, "// ---- set composition wrappers ----\n\n")
	fmt.Fprintf(&out, "// SetMatch is one match reported by a set Find iterator.\n"+
		"//\n"+
		"// Start and End are unsigned: an offset into the input cannot be negative,\n"+
		"// and the iterator reports absence by ending rather than by a sentinel, so\n"+
		"// nothing here needs a -1. PatternID stays signed because it is an id, not\n"+
		"// an offset.\ntype SetMatch struct {\n\tPatternID  int\n\tStart, End uint\n}\n\n")
	needsIter := false
	for _, s := range cfg.Sets {
		n := patternsInSet(s, cfg)
		konst := pascalSet(s.Name) + "PatternCount"
		idN := idSpaceSize(s, cfg)
		idKonst := pascalSet(s.Name) + "IDSpace"
		wide := wideAllForm(s, cfg)

		fmt.Fprintf(&out, "// %s is the number of patterns in set %q. It sizes the match buffer:\n// Find can report at most this many matches at one position.\nconst %s = %d\n\n", konst, s.Name, konst, n)
		fmt.Fprintf(&out, "// %s is one past the largest pattern id set %q can report. Pattern ids\n// are global indices into regexps:, so a set holding a few late-declared\n// patterns has a small count and a large id space. Everything indexed BY an\n// id \u2014 the gate array, the _all bitmask \u2014 is sized from this.\nconst %s = %d\n\n", idKonst, s.Name, idKonst, idN)

		imp := func(name, sig string) {
			fmt.Fprintf(&out, "//go:wasmimport %s %s\n//go:noescape\nfunc ffi_%s%s\n\n", cfg.ImportModule, name, name, sig)
		}
		const inArgs = "ptr unsafe.Pointer, length int32"

		if s.MatchAny != "" {
			imp(s.MatchAny, "("+inArgs+") int32")
			pub := goPublicName(s.MatchAny)
			fmt.Fprintf(&out, `// %s returns the id of SOME pattern matching the whole input.
// A set is unordered, so which id you get is unspecified when several match.
func %s(input []byte) (int, bool) {
	r := ffi_%s(unsafe.Pointer(unsafe.SliceData(input)), int32(len(input)))
	if r < 0 { return 0, false }
	return int(r), true
}

`, pub, pub, s.MatchAny)
		}
		if s.MatchAll != "" {
			needsIter = true
			pub := goPublicName(s.MatchAll)
			if wide {
				imp(s.MatchAll, "("+inArgs+", outPtr unsafe.Pointer) int32")
				fmt.Fprintf(&out, `// %s yields the id of every pattern matching the whole input.
//
// An iterator rather than a slice: the ABI hands back a bitmap whose set bits
// can be yielded lazily with nothing materialised, so a caller who only wants
// to know "any?" or to stop early allocates nothing. slices.Collect gives you
// a slice when you want one.
func %s(input []byte) iter.Seq[int] {
	return func(yield func(int) bool) {
		bits := make([]byte, (%s+7)/8)
		ffi_%s(unsafe.Pointer(unsafe.SliceData(input)), int32(len(input)), unsafe.Pointer(&bits[0]))
		for k := 0; k < %s; k++ {
			if bits[k/8]&(1<<uint(k%%8)) != 0 {
				if !yield(k) { return }
			}
		}
	}
}

`, pub, pub, idKonst, s.MatchAll, idKonst)
			} else {
				imp(s.MatchAll, "("+inArgs+") int64")
				fmt.Fprintf(&out, `// %s yields the id of every pattern matching the whole input.
// See the wide form's comment for why this is an iterator.
func %s(input []byte) iter.Seq[int] {
	return func(yield func(int) bool) {
		mask := uint64(ffi_%s(unsafe.Pointer(unsafe.SliceData(input)), int32(len(input))))
		for k := 0; k < %s; k++ {
			if mask&(1<<uint(k)) != 0 {
				if !yield(k) { return }
			}
		}
	}
}

`, pub, pub, s.MatchAll, idKonst)
			}
		}
		if s.ScanAny != "" {
			imp(s.ScanAny, "("+inArgs+", from int32) int32")
			pub := goPublicName(s.ScanAny)
			fmt.Fprintf(&out, `// %s reports one pattern that matches somewhere at or after offset.
// Which id you get is unspecified when several patterns match; it names a
// genuinely matching pattern, and no position is reported.
func %s(input []byte, offset uint) (id int, ok bool) {
	r := ffi_%s(unsafe.Pointer(unsafe.SliceData(input)), int32(len(input)), int32(offset))
	if r < 0 { return 0, false }
	return int(r), true
}

`, pub, pub, s.ScanAny)
		}
		if s.ScanAll != "" {
			needsIter = true
			pub := goPublicName(s.ScanAll)
			if wide {
				imp(s.ScanAll, "("+inArgs+", from int32, outPtr unsafe.Pointer) int32")
				fmt.Fprintf(&out, `// %s yields the id of every pattern matching somewhere at or after offset.
func %s(input []byte, offset uint) iter.Seq[int] {
	return func(yield func(int) bool) {
		bits := make([]byte, (%s+7)/8)
		ffi_%s(unsafe.Pointer(unsafe.SliceData(input)), int32(len(input)), int32(offset), unsafe.Pointer(&bits[0]))
		for k := 0; k < %s; k++ {
			if bits[k/8]&(1<<uint(k%%8)) != 0 {
				if !yield(k) { return }
			}
		}
	}
}

`, pub, pub, idKonst, s.ScanAll, idKonst)
			} else {
				imp(s.ScanAll, "("+inArgs+", from int32) int64")
				fmt.Fprintf(&out, `// %s yields the id of every pattern matching somewhere at or after offset.
func %s(input []byte, offset uint) iter.Seq[int] {
	return func(yield func(int) bool) {
		mask := uint64(ffi_%s(unsafe.Pointer(unsafe.SliceData(input)), int32(len(input)), int32(offset)))
		for k := 0; k < %s; k++ {
			if mask&(1<<uint(k)) != 0 {
				if !yield(k) { return }
			}
		}
	}
}

`, pub, pub, s.ScanAll, idKonst)
			}
		}
		if s.Find != "" {
			needsIter = true
			pub := goPublicName(s.Find)
			gateDecl, gateArg, gateDoc := "", "", ""
			if gatedFind(s) {
				imp(s.Find, "("+inArgs+", from int32, gatePtr unsafe.Pointer, outPtr unsafe.Pointer, outCap int32) int32")
				gateDecl = "\t\tgates := make([]uint32, " + idKonst + ")\n"
				gateArg = "unsafe.Pointer(&gates[0]), "
				gateDoc = " and a zeroed gate array"
			} else {
				imp(s.Find, "("+inArgs+", from int32, outPtr unsafe.Pointer, outCap int32) int32")
			}
			fmt.Fprintf(&out, `// %s iterates the set's matches from position offset. The sequence owns a
// reusable tuple buffer%s; each step yields one match, and each WASM call
// returns every match at one position before the scan advances.
func %s(input []byte, offset uint) iter.Seq[SetMatch] {
	return func(yield func(SetMatch) bool) {
		buf := make([][3]int32, %s)
%s		pos := int32(offset)
		for {
			n := ffi_%s(unsafe.Pointer(unsafe.SliceData(input)), int32(len(input)), pos, %sunsafe.Pointer(&buf[0]), %s)
			if n <= 0 { return }
			// Every tuple in one call shares a start; resume one past it.
			next := buf[0][1] + 1
			for i := int32(0); i < n; i++ {
				if !yield(SetMatch{PatternID: int(buf[i][0]), Start: uint(buf[i][1]), End: uint(buf[i][2])}) { return }
			}
			pos = next
		}
	}
}

`, pub, gateDoc, pub, konst, gateDecl, s.Find, gateArg, konst)
		}
	}
	if hasEmitNameMap(cfg) {
		out.WriteString("// PatternName returns the name of the pattern with the given ID.\n")
		out.WriteString("func PatternName(id int) string {\n\tswitch id {\n")
		for i, re := range cfg.Regexps {
			if re.Name != "" {
				fmt.Fprintf(&out, "\tcase %d: return %q\n", i, re.Name)
			}
		}
		out.WriteString("\t}\n\treturn \"\"\n}\n\n")
	}
	return out.String(), needsIter
}

// genGoSetSection is kept for backward compatibility with tests.
func genGoSetSection(cfg config.BuildConfig, _ string) string {
	body, needsIter := genGoSetBody(cfg)
	if body == "" {
		return ""
	}
	if needsIter {
		return "import (\n    \"iter\"\n    \"unsafe\"\n)\n\n" + body
	}
	return body
}

// goPublicName converts a snake_case function name to a PascalCase Go identifier.
// "url_match" → "UrlMatch", "find_github_token" → "FindGithubToken"
func goPublicName(s string) string {
	var b strings.Builder
	upper := true
	for _, c := range s {
		if c == '_' {
			upper = true
			continue
		}
		if upper {
			if c >= 'a' && c <= 'z' {
				c -= 'a' - 'A'
			}
			upper = false
		}
		b.WriteRune(c)
	}
	return b.String()
}

// genGoMatchStub generates an anchored-match stub.
func genGoMatchStub(importModule, funcName string) string {
	ffi := "ffi_" + funcName
	pub := goPublicName(funcName)
	return fmt.Sprintf(`//go:wasmimport %s %s
//go:noescape
func %s(ptr unsafe.Pointer, length uint32) int32

// %s returns the end position of the match (exclusive), or (0, false) if no
// match. The match is anchored: it starts at the beginning of input.
//
// The position is unsigned: it cannot be negative, and the comma-ok bool
// already carries "no match", so nothing here needs a -1.
func %s(input []byte) (uint, bool) {
	var ptr unsafe.Pointer
	if len(input) > 0 {
		ptr = unsafe.Pointer(&input[0])
	}
	r := %s(ptr, uint32(len(input)))
	if r == %d {
		panic("%s")
	}
	if r < 0 {
		return 0, false
	}
	return uint(r), true
}

`, importModule, funcName, ffi, pub, pub, ffi, btOverflow, btOverflowMsg(pub))
}

// genGoFindStub generates a find iterator returning iter.Seq2[int,int].
func genGoFindStub(importModule, funcName string) string {
	ffi := "ffi_" + funcName
	pub := goPublicName(funcName)
	return fmt.Sprintf(`//go:wasmimport %s %s
//go:noescape
func %s(ptr unsafe.Pointer, length uint32, from uint32) int64

// %s returns an iterator over all non-overlapping matches at or after offset.
// Each iteration yields (start, end) absolute byte positions.
//
// The whole input is passed on every call and offset only bounds where the
// search STARTS, so a leading \b, \B, ^ or (?m:^) is judged against the real
// preceding byte rather than a slice edge.
func %s(input []byte, offset uint) iter.Seq2[uint, uint] {
	return func(yield func(uint, uint) bool) {
		pos := int(offset)
		if pos > len(input) {
			return
		}
		var base unsafe.Pointer
		if len(input) > 0 {
			base = unsafe.Pointer(&input[0])
		}
		prevEnd := -1
		for pos <= len(input) {
			r := %s(base, uint32(len(input)), uint32(pos))
			if r == %d {
				panic("%s")
			}
			if r < 0 {
				break
			}
			start := int(uint64(r) >> 32)
			end := int(uint32(r))
			// Go's FindAllIndex rule: an EMPTY match beginning exactly where
			// the previous match ended is suppressed. Without this the
			// iterator reports a strict superset of Go's answer — e.g. a* on
			// "a" gives 0-1 AND 1-1, where Go gives only 0-1.
			//
			// The advance itself is unchanged and still steps one byte past a
			// zero-length match, which is what stops the loop spinning; only
			// whether that match is REPORTED changes.
			if !(start == end && prevEnd >= 0 && start == prevEnd) {
				if !yield(uint(start), uint(end)) {
					break
				}
				prevEnd = end
			}
			if end > start {
				pos = end
			} else {
				pos = start + 1
			}
		}
	}
}

`, importModule, funcName, ffi, pub, pub, ffi, btOverflow, btOverflowMsg(pub))
}

// genGoGroupsStub generates a groups iterator returning iter.Seq2[[][]int, bool].
// Each iteration yields a slice of [start, end] pairs (nil if the group didn't participate).
// declareFFI controls whether the //go:wasmimport block is emitted; pass false when
// a sibling named-groups stub in the same file already declared it.
func genGoGroupsStub(importModule, funcName, exportName string, declareFFI bool, numGroups int) string {
	ffi := "ffi_" + exportName
	pub := goPublicName(funcName)
	slotCount := numGroups * 2

	var ffiDecl string
	if declareFFI {
		ffiDecl = fmt.Sprintf(`//go:wasmimport %s %s
//go:noescape
func %s(ptr unsafe.Pointer, length uint32, outPtr unsafe.Pointer, from uint32) int32

`, importModule, exportName, ffi)
	}

	return ffiDecl + fmt.Sprintf(`// %s returns an iterator over capture groups of all non-overlapping matches
// starting at or after offset.
// Each iteration yields a slice of numGroups [start,end] pairs; nil means the group didn't participate.
// Index 0 is the full match. Positions are absolute byte offsets.
//
// LIMITATION: offset currently NARROWS the input rather than bounding only the
// search, so at offset > 0 a leading \b, \B, ^ or (?m:^) judges a truncated
// left context. The single-pattern WASM exports take no offset; TODO 54 gives
// them one, after which this stub stops narrowing and the signature is
// unchanged.
func %s(input []byte, offset uint) iter.Seq[[][]uint] {
	return func(yield func([][]uint) bool) {
		pos := int(offset)
		if pos > len(input) {
			return
		}
		var base unsafe.Pointer
		if len(input) > 0 {
			base = unsafe.Pointer(&input[0])
		}
		prevEnd := -1
		for pos <= len(input) {
			buf := make([]int32, %d)
			r := %s(base, uint32(len(input)), unsafe.Pointer(&buf[0]), uint32(pos))
			if r == %d {
				panic("%s")
			}
			if r < 0 {
				if pos == len(input) {
					break
				}
				pos++
				continue
			}
			groups := make([][]uint, %d)
			for i := range groups {
				s, e := buf[i*2], buf[i*2+1]
				if s < 0 {
					groups[i] = nil
				} else {
					// Absolute already: the whole input is passed on every
					// call, so slots are positions in it.
					groups[i] = []uint{uint(s), uint(e)}
				}
			}
			absStart, absEnd := int(buf[0]), int(buf[0])
			if buf[1] >= 0 {
				absEnd = int(buf[1])
			}
			if absEnd > absStart {
				pos = absEnd
			} else {
				pos = absStart + 1
			}
			// Go's FindAllSubmatchIndex rule: suppress an EMPTY match
			// beginning exactly where the previous reported match ended. The
			// advance above is unchanged.
			if absStart == absEnd && prevEnd == absStart {
				continue
			}
			prevEnd = absEnd
			if !yield(groups) {
				break
			}
		}
	}
}

`, pub, pub, slotCount, ffi, btOverflow, btOverflowMsg(pub), numGroups)
}

// genGoNamedGroupsStub generates a named-groups iterator that calls the FFI export directly.
// declareFFI controls whether the //go:wasmimport block is emitted; pass false when a
// sibling groups stub in the same file already declared it.
func genGoNamedGroupsStub(importModule, funcName, exportName string, declareFFI bool, numGroups int, namedGroups map[string]int) string {
	ffi := "ffi_" + exportName
	pub := goPublicName(funcName)
	slotCount := numGroups * 2

	var ffiDecl string
	if declareFFI {
		ffiDecl = fmt.Sprintf(`//go:wasmimport %s %s
//go:noescape
func %s(ptr unsafe.Pointer, length uint32, outPtr unsafe.Pointer, from uint32) int32

`, importModule, exportName, ffi)
	}

	type entry struct {
		name  string
		index int
	}
	var entries []entry
	for name, idx := range namedGroups {
		entries = append(entries, entry{name, idx})
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].index < entries[j].index })

	var assigns strings.Builder
	for _, e := range entries {
		fmt.Fprintf(&assigns,
			"\t\t\tif buf[%d] >= 0 { named[\"%s\"] = []uint{uint(buf[%d]), uint(buf[%d])} }\n",
			e.index*2, e.name, e.index*2, e.index*2+1)
	}

	return ffiDecl + fmt.Sprintf(`// %s returns an iterator over named capture groups of all non-overlapping matches.
// Each iteration yields a map of group name → [start,end] absolute byte offsets.
func %s(input []byte, offset uint) iter.Seq[map[string][]uint] {
	return func(yield func(map[string][]uint) bool) {
		pos := int(offset)
		if pos > len(input) {
			return
		}
		var base unsafe.Pointer
		if len(input) > 0 {
			base = unsafe.Pointer(&input[0])
		}
		prevEnd := -1
		for pos <= len(input) {
			buf := make([]int32, %d)
			r := %s(base, uint32(len(input)), unsafe.Pointer(&buf[0]), uint32(pos))
			if r == %d {
				panic("%s")
			}
			if r < 0 {
				if pos == len(input) {
					break
				}
				pos++
				continue
			}
			named := make(map[string][]uint, %d)
%s			absStart, absEnd := int(buf[0]), int(buf[0])
			if buf[1] >= 0 {
				absEnd = int(buf[1])
			}
			if absEnd > absStart {
				pos = absEnd
			} else {
				pos = absStart + 1
			}
			// See the groups iterator: Go suppresses an empty match adjacent
			// to the previous one.
			if absStart == absEnd && prevEnd == absStart {
				continue
			}
			prevEnd = absEnd
			if !yield(named) {
				break
			}
		}
	}
}

`, pub, pub, slotCount, ffi, btOverflow, btOverflowMsg(pub), len(entries), assigns.String())
}

// genGoStubsBody returns the body (no header, no imports) for single-pattern stubs.
// Returns (body string, needsIter bool).
func genGoStubsBody(entries []config.RegexEntry, importModule string) (string, bool, error) {
	var parts []string
	needsIter := false
	for _, re := range entries {
		part, err := genGoStubsForEntry(re, importModule)
		if err != nil {
			return "", false, err
		}
		if part != "" {
			parts = append(parts, part)
			if re.FindFunc != "" || re.GroupsFunc != "" || re.NamedGroupsFunc != "" {
				needsIter = true
			}
		}
	}
	return strings.Join(parts, ""), needsIter, nil
}

// genGoStubFile generates the full Go stub file for a slice of entries (no sets).
// Kept for backward compatibility with tests.
func genGoStubFile(entries []config.RegexEntry, importModule, pkgName string) (string, error) {
	body, needsIter, err := genGoStubsBody(entries, importModule)
	if err != nil || body == "" {
		return "", err
	}
	var sb strings.Builder
	sb.WriteString("// Auto-generated by regexped. Do not edit.\n\n")
	sb.WriteString("//go:build wasip1\n\n")
	fmt.Fprintf(&sb, "package %s\n\n", pkgName)
	if needsIter {
		sb.WriteString("import (\n\t\"iter\"\n\t\"unsafe\"\n)\n\n")
	} else {
		sb.WriteString("import \"unsafe\"\n\n")
	}
	sb.WriteString(body)
	return sb.String(), nil
}

// genGoStubsForEntry generates the Go stub content for a single regexp entry.
func genGoStubsForEntry(re config.RegexEntry, importModule string) (string, error) {
	var out string
	written := false

	if re.MatchFunc != "" {
		out += genGoMatchStub(importModule, re.MatchFunc)
		written = true
	}
	if re.FindFunc != "" {
		out += genGoFindStub(importModule, re.FindFunc)
		written = true
	}
	if re.GroupsFunc != "" || re.NamedGroupsFunc != "" {
		numGroups, namedGroups, err := extractGroupInfo(re.Pattern)
		if err != nil {
			return "", err
		}
		exportName := re.GroupsExportName()
		if re.GroupsFunc != "" {
			out += genGoGroupsStub(importModule, re.GroupsFunc, exportName, true, numGroups)
			written = true
		}
		if re.NamedGroupsFunc != "" {
			declareFFI := re.GroupsFunc == ""
			out += genGoNamedGroupsStub(importModule, re.NamedGroupsFunc, exportName, declareFFI, numGroups, namedGroups)
			written = true
		}
	}

	if !written {
		return "", nil
	}
	return out, nil
}
