package generate

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"github.com/qrdl/regexped/config"
)

// goStub generates a Go stub file (//go:build wasip1) for all regexp entries in cfg.
// out is the full output path for stub.go, or "-" for stdout.
// The Go package name is set to cfg.ImportModule when the stub is placed in a
// subdirectory named after the import module; otherwise "main" is used.
func goStub(cfg config.BuildConfig, out string) error {
	pkgName := cfg.ImportModule
	if filepath.Base(filepath.Dir(out)) != cfg.ImportModule {
		pkgName = "main"
	}
	singleBody, needsIter, err := genGoStubsBody(cfg.Regexps, cfg.ImportModule)
	if err != nil {
		return fmt.Errorf("generate Go stub: %w", err)
	}
	setBody, setNeedsIter := genGoSetBody(cfg)
	if singleBody == "" && setBody == "" {
		return nil
	}
	needsIter = needsIter || setNeedsIter

	var sb strings.Builder
	sb.WriteString("// Auto-generated by regexped. Do not edit.\n\n")
	sb.WriteString("//go:build wasip1\n\n")
	fmt.Fprintf(&sb, "package %s\n\n", pkgName)
	if needsIter {
		sb.WriteString("import (\n\t\"iter\"\n\t\"unsafe\"\n)\n\n")
	} else {
		sb.WriteString("import \"unsafe\"\n\n")
	}
	sb.WriteString(singleBody)
	sb.WriteString(setBody)
	combined := sb.String()

	if out == "-" {
		_, err := fmt.Print(combined)
		return err
	}
	return writeStub(out, []byte(combined))
}

// genGoSetBody generates Go set wrappers (body only, no file header or imports).
// Returns (body string, needsIter bool).
// Uses unified SetMatch for all match ops; SetAnchorMatch is removed.
func genGoSetBody(cfg config.BuildConfig) (string, bool) {
	if !hasSetExports(cfg) {
		return "", false
	}
	var out strings.Builder
	fmt.Fprintf(&out, "// ---- set composition wrappers ----\n\n")
	fmt.Fprintf(&out, "// SetMatch is one match reported by a set Find iterator.\ntype SetMatch struct { PatternID, Start, End int }\n\n")
	if hasFindBatch(cfg) {
		fmt.Fprintf(&out, "// SetTuple is one slot of a batched scan's buffer, in the raw form the\n// module writes. Allocate a []SetTuple once and reuse it for every scan: the\n// batched iterator borrows it and never allocates.\ntype SetTuple [3]int32\n\n")
	}
	needsIter := false
	for _, s := range cfg.Sets {
		n := patternsInSet(s, cfg)
		konst := pascalSet(s.Name) + "PatternCount"
		idN := idSpaceSize(s, cfg)
		idKonst := pascalSet(s.Name) + "IDSpace"
		wide := wideAllForm(s, cfg)

		fmt.Fprintf(&out, "// %s is the number of patterns in set %q. It sizes the match buffer:\n// Find can report at most this many matches at one position.\nconst %s = %d\n\n", konst, s.Name, konst, n)
		fmt.Fprintf(&out, "// %s is one past the largest pattern id set %q can report. Pattern ids\n// are global indices into regexps:, so a set holding a few late-declared\n// patterns has a small count and a large id space. Everything indexed BY an\n// id \u2014 the gate array, the _all bitmask \u2014 is sized from this.\nconst %s = %d\n\n", idKonst, s.Name, idKonst, idN)

		if s.FindBatch != "" {
			bits := pascalSet(s.Name) + "BatchCountBits"
			maxc := pascalSet(s.Name) + "BatchMaxCount"
			fmt.Fprintf(&out, "// %s is the width of the count field in set %q's find_batch cursor.\n// The count is packed & ((1 << %s) - 1); the scan is finished when the top\n// 32 bits of the cursor are all ones. Only a direct WASM caller needs this —\n// the generated iterator decodes the cursor for you.\nconst %s = %d\n\n", bits, s.Name, bits, bits, cursorCountBits(s, cfg))
			fmt.Fprintf(&out, "// %s is the largest tuple count one find_batch call can report for\n// set %q. The module clamps out_cap to it.\nconst %s = %d\n\n", maxc, s.Name, maxc, cursorMaxCount(s, cfg))
		}

		imp := func(name, sig string) {
			fmt.Fprintf(&out, "//go:wasmimport %s %s\n//go:noescape\nfunc ffi_%s%s\n\n", cfg.ImportModule, name, name, sig)
		}
		const inArgs = "ptr unsafe.Pointer, length int32"

		if s.Match != "" {
			imp(s.Match, "("+inArgs+") int32")
			pub := goPublicName(s.Match)
			fmt.Fprintf(&out, `// %s reports whether some pattern in the set matches the WHOLE input.
func %s(input []byte) bool {
	return ffi_%s(unsafe.Pointer(unsafe.SliceData(input)), int32(len(input))) != 0
}

`, pub, pub, s.Match)
		}
		if s.MatchAny != "" {
			imp(s.MatchAny, "("+inArgs+") int32")
			pub := goPublicName(s.MatchAny)
			fmt.Fprintf(&out, `// %s returns the id of SOME pattern matching the whole input.
// A set is unordered, so which id you get is unspecified when several match.
func %s(input []byte) (int, bool) {
	r := ffi_%s(unsafe.Pointer(unsafe.SliceData(input)), int32(len(input)))
	if r < 0 { return 0, false }
	return int(r), true
}

`, pub, pub, s.MatchAny)
		}
		if s.MatchAll != "" {
			pub := goPublicName(s.MatchAll)
			if wide {
				imp(s.MatchAll, "("+inArgs+", outPtr unsafe.Pointer) int32")
				fmt.Fprintf(&out, `// %s returns the ids of every pattern matching the whole input.
func %s(input []byte) []int {
	bits := make([]byte, (%s+7)/8)
	n := ffi_%s(unsafe.Pointer(unsafe.SliceData(input)), int32(len(input)), unsafe.Pointer(&bits[0]))
	out := make([]int, 0, n)
	for k := 0; k < %s; k++ {
		if bits[k/8]&(1<<uint(k%%8)) != 0 { out = append(out, k) }
	}
	return out
}

`, pub, pub, idKonst, s.MatchAll, idKonst)
			} else {
				imp(s.MatchAll, "("+inArgs+") int64")
				fmt.Fprintf(&out, `// %s returns the ids of every pattern matching the whole input.
func %s(input []byte) []int {
	mask := uint64(ffi_%s(unsafe.Pointer(unsafe.SliceData(input)), int32(len(input))))
	var out []int
	for k := 0; k < %s; k++ {
		if mask&(1<<uint(k)) != 0 { out = append(out, k) }
	}
	return out
}

`, pub, pub, s.MatchAll, idKonst)
			}
		}
		if s.Scan != "" {
			imp(s.Scan, "("+inArgs+", from int32) int32")
			pub := goPublicName(s.Scan)
			fmt.Fprintf(&out, `// %s reports whether some pattern matches at a position at or after from.
func %s(input []byte, from int) bool {
	return ffi_%s(unsafe.Pointer(unsafe.SliceData(input)), int32(len(input)), int32(from)) != 0
}

`, pub, pub, s.Scan)
		}
		if s.ScanAny != "" {
			imp(s.ScanAny, "("+inArgs+", from int32) int64")
			pub := goPublicName(s.ScanAny)
			fmt.Fprintf(&out, `// %s returns the pattern id and start of the FIRST position at or after
// from where anything matches. Which id you get is unspecified when several
// patterns match at that position.
func %s(input []byte, from int) (id, start int, ok bool) {
	packed := ffi_%s(unsafe.Pointer(unsafe.SliceData(input)), int32(len(input)), int32(from))
	if packed < 0 { return 0, 0, false }
	return int(packed & 0xFFFFFFFF), int(packed >> 32), true
}

`, pub, pub, s.ScanAny)
		}
		if s.ScanAll != "" {
			pub := goPublicName(s.ScanAll)
			if wide {
				imp(s.ScanAll, "("+inArgs+", from int32, outPtr unsafe.Pointer) int32")
				fmt.Fprintf(&out, `// %s returns the ids of every pattern matching somewhere at or after from.
func %s(input []byte, from int) []int {
	bits := make([]byte, (%s+7)/8)
	n := ffi_%s(unsafe.Pointer(unsafe.SliceData(input)), int32(len(input)), int32(from), unsafe.Pointer(&bits[0]))
	out := make([]int, 0, n)
	for k := 0; k < %s; k++ {
		if bits[k/8]&(1<<uint(k%%8)) != 0 { out = append(out, k) }
	}
	return out
}

`, pub, pub, idKonst, s.ScanAll, idKonst)
			} else {
				imp(s.ScanAll, "("+inArgs+", from int32) int64")
				fmt.Fprintf(&out, `// %s returns the ids of every pattern matching somewhere at or after from.
func %s(input []byte, from int) []int {
	mask := uint64(ffi_%s(unsafe.Pointer(unsafe.SliceData(input)), int32(len(input)), int32(from)))
	var out []int
	for k := 0; k < %s; k++ {
		if mask&(1<<uint(k)) != 0 { out = append(out, k) }
	}
	return out
}

`, pub, pub, s.ScanAll, idKonst)
			}
		}
		if s.Find != "" {
			needsIter = true
			pub := goPublicName(s.Find)
			gateDecl, gateArg, gateDoc := "", "", ""
			if gatedFind(s) {
				imp(s.Find, "("+inArgs+", from int32, gatePtr unsafe.Pointer, outPtr unsafe.Pointer, outCap int32) int32")
				gateDecl = "\t\tgates := make([]uint32, " + idKonst + ")\n"
				gateArg = "unsafe.Pointer(&gates[0]), "
				gateDoc = " and a zeroed gate array"
			} else {
				imp(s.Find, "("+inArgs+", from int32, outPtr unsafe.Pointer, outCap int32) int32")
			}
			fmt.Fprintf(&out, `// %s iterates the set's matches from position from. The sequence owns a
// reusable tuple buffer%s; each step yields one match, and each WASM call
// returns every match at one position before the scan advances.
func %s(input []byte, from int) iter.Seq[SetMatch] {
	return func(yield func(SetMatch) bool) {
		buf := make([][3]int32, %s)
%s		pos := int32(from)
		for {
			n := ffi_%s(unsafe.Pointer(unsafe.SliceData(input)), int32(len(input)), pos, %sunsafe.Pointer(&buf[0]), %s)
			if n <= 0 { return }
			// Every tuple in one call shares a start; resume one past it.
			next := buf[0][1] + 1
			for i := int32(0); i < n; i++ {
				if !yield(SetMatch{PatternID: int(buf[i][0]), Start: int(buf[i][1]), End: int(buf[i][2])}) { return }
			}
			pos = next
		}
	}
}

`, pub, gateDoc, pub, konst, gateDecl, s.Find, gateArg, konst)
		}
		if s.FindBatch != "" {
			needsIter = true
			pub := goPublicName(s.FindBatch)
			maxKonst := pascalSet(s.Name) + "BatchMaxCount"
			gateDecl, gateArg, gateDoc := "", "", ""
			if gatedFind(s) {
				// The gate array stays stub-owned and out of the public
				// surface (docs/sets.md "The gate array"): its length is the
				// emitted id-space constant, so it is not a size the caller
				// chooses. Only the tuple buffer is.
				imp(s.FindBatch, "("+inArgs+", cursor int64, gatePtr unsafe.Pointer, outPtr unsafe.Pointer, outCap int32) int64")
				gateDecl = "\t\tgates := make([]uint32, " + idKonst + ")\n"
				gateArg = "unsafe.Pointer(&gates[0]), "
				gateDoc = " and a zeroed gate array"
			} else {
				imp(s.FindBatch, "("+inArgs+", cursor int64, outPtr unsafe.Pointer, outCap int32) int64")
			}
			// The comparison only names `find` when the set actually declares
			// it; the two capabilities are independent.
			peer := "the unbatched find"
			if s.Find != "" {
				peer = goPublicName(s.Find)
			}
			fmt.Fprintf(&out, `// %s iterates the set's matches from position from, refilling the CALLER'S
// buffer a bufferful at a time.
//
// Same matches in the same order as %s — the difference is one host call per
// bufferful instead of one per position. Prefer it when the whole scan will be
// consumed; prefer %s when you may stop early, since a batch call does the
// work for matches you never look at.
//
// len(buf) is the batch size, capped at %s; an empty buffer yields nothing.
// The buffer is borrowed, not copied, so allocate one and reuse it for every
// scan. The sequence owns only its cursor%s.
func %s(input []byte, from int, buf []SetTuple) iter.Seq[SetMatch] {
	return func(yield func(SetMatch) bool) {
		n := len(buf)
		if n < 1 { return }
		if n > %s { n = %s }
%s		cursor := int64(from) << 32
		for {
			packed := ffi_%s(unsafe.Pointer(unsafe.SliceData(input)), int32(len(input)), cursor, %sunsafe.Pointer(&buf[0]), int32(n))
			// The cursor is opaque: hand it back unchanged. Only its top 32
			// bits are public — all ones means the scan is finished, and that
			// arrives on the same call as the last matches.
			got := int32(packed & %d)
			done := uint64(packed)>>32 == 0xFFFFFFFF
			for i := int32(0); i < got; i++ {
				if !yield(SetMatch{PatternID: int(buf[i][0]), Start: int(buf[i][1]), End: int(buf[i][2])}) { return }
			}
			// A call reports at least one match unless the scan is over.
			if done || got == 0 { return }
			cursor = packed
		}
	}
}

`, pub, peer, peer, maxKonst, gateDoc, pub,
				maxKonst, maxKonst,
				gateDecl, s.FindBatch, gateArg, cursorCountMask(s, cfg))
		}
	}
	if hasEmitNameMap(cfg) {
		out.WriteString("// PatternName returns the name of the pattern with the given ID.\n")
		out.WriteString("func PatternName(id int) string {\n\tswitch id {\n")
		for i, re := range cfg.Regexps {
			if re.Name != "" {
				fmt.Fprintf(&out, "\tcase %d: return %q\n", i, re.Name)
			}
		}
		out.WriteString("\t}\n\treturn \"\"\n}\n\n")
	}
	return out.String(), needsIter
}

// genGoSetSection is kept for backward compatibility with tests.
func genGoSetSection(cfg config.BuildConfig, _ string) string {
	body, needsIter := genGoSetBody(cfg)
	if body == "" {
		return ""
	}
	if needsIter {
		return "import (\n    \"iter\"\n    \"unsafe\"\n)\n\n" + body
	}
	return body
}

// goPublicName converts a snake_case function name to a PascalCase Go identifier.
// "url_match" → "UrlMatch", "find_github_token" → "FindGithubToken"
func goPublicName(s string) string {
	var b strings.Builder
	upper := true
	for _, c := range s {
		if c == '_' {
			upper = true
			continue
		}
		if upper {
			if c >= 'a' && c <= 'z' {
				c -= 'a' - 'A'
			}
			upper = false
		}
		b.WriteRune(c)
	}
	return b.String()
}

// genGoMatchStub generates an anchored-match stub.
func genGoMatchStub(importModule, funcName string) string {
	ffi := "ffi_" + funcName
	pub := goPublicName(funcName)
	return fmt.Sprintf(`//go:wasmimport %s %s
//go:noescape
func %s(ptr unsafe.Pointer, length uint32) int32

// %s returns the end position of the match (exclusive), or (0, false) if no match.
// The match is anchored: it starts at the beginning of input.
func %s(input []byte) (int, bool) {
	var ptr unsafe.Pointer
	if len(input) > 0 {
		ptr = unsafe.Pointer(&input[0])
	}
	r := %s(ptr, uint32(len(input)))
	if r == %d {
		panic("%s")
	}
	if r < 0 {
		return 0, false
	}
	return int(r), true
}

`, importModule, funcName, ffi, pub, pub, ffi, btOverflow, btOverflowMsg(pub))
}

// genGoFindStub generates a find iterator returning iter.Seq2[int,int].
func genGoFindStub(importModule, funcName string) string {
	ffi := "ffi_" + funcName
	pub := goPublicName(funcName)
	return fmt.Sprintf(`//go:wasmimport %s %s
//go:noescape
func %s(ptr unsafe.Pointer, length uint32) int64

// %s returns an iterator over all non-overlapping matches in input.
// Each iteration yields (start, end) absolute byte positions.
func %s(input []byte) iter.Seq2[int, int] {
	return func(yield func(int, int) bool) {
		pos := 0
		for pos <= len(input) {
			var ptr unsafe.Pointer
			if pos < len(input) {
				ptr = unsafe.Pointer(&input[pos])
			}
			r := %s(ptr, uint32(len(input)-pos))
			if r == %d {
				panic("%s")
			}
			if r < 0 {
				break
			}
			start := pos + int(uint64(r)>>32)
			end := pos + int(uint32(r))
			if !yield(start, end) {
				break
			}
			if end > start {
				pos = end
			} else {
				pos = start + 1
			}
		}
	}
}

`, importModule, funcName, ffi, pub, pub, ffi, btOverflow, btOverflowMsg(pub))
}

// genGoGroupsStub generates a groups iterator returning iter.Seq2[[][]int, bool].
// Each iteration yields a slice of [start, end] pairs (nil if the group didn't participate).
// declareFFI controls whether the //go:wasmimport block is emitted; pass false when
// a sibling named-groups stub in the same file already declared it.
func genGoGroupsStub(importModule, funcName, exportName string, declareFFI bool, numGroups int) string {
	ffi := "ffi_" + exportName
	pub := goPublicName(funcName)
	slotCount := numGroups * 2

	var ffiDecl string
	if declareFFI {
		ffiDecl = fmt.Sprintf(`//go:wasmimport %s %s
//go:noescape
func %s(ptr unsafe.Pointer, length uint32, outPtr unsafe.Pointer) int32

`, importModule, exportName, ffi)
	}

	return ffiDecl + fmt.Sprintf(`// %s returns an iterator over capture groups of all non-overlapping matches.
// Each iteration yields a slice of numGroups [start,end] pairs; nil means the group didn't participate.
// Index 0 is the full match. Positions are absolute byte offsets.
func %s(input []byte) iter.Seq[[][]int] {
	return func(yield func([][]int) bool) {
		pos := 0
		for pos <= len(input) {
			var ptr unsafe.Pointer
			if pos < len(input) {
				ptr = unsafe.Pointer(&input[pos])
			}
			buf := make([]int32, %d)
			r := %s(ptr, uint32(len(input)-pos), unsafe.Pointer(&buf[0]))
			if r == %d {
				panic("%s")
			}
			if r < 0 {
				if pos == len(input) {
					break
				}
				pos++
				continue
			}
			groups := make([][]int, %d)
			for i := range groups {
				s, e := buf[i*2], buf[i*2+1]
				if s < 0 {
					groups[i] = nil
				} else {
					groups[i] = []int{int(s) + pos, int(e) + pos}
				}
			}
			matchEnd := 0
			if buf[1] >= 0 {
				matchEnd = int(buf[1])
			}
			if matchEnd > 0 {
				pos += matchEnd
			} else {
				pos++
			}
			if !yield(groups) {
				break
			}
		}
	}
}

`, pub, pub, slotCount, ffi, btOverflow, btOverflowMsg(pub), numGroups)
}

// genGoNamedGroupsStub generates a named-groups iterator that calls the FFI export directly.
// declareFFI controls whether the //go:wasmimport block is emitted; pass false when a
// sibling groups stub in the same file already declared it.
func genGoNamedGroupsStub(importModule, funcName, exportName string, declareFFI bool, numGroups int, namedGroups map[string]int) string {
	ffi := "ffi_" + exportName
	pub := goPublicName(funcName)
	slotCount := numGroups * 2

	var ffiDecl string
	if declareFFI {
		ffiDecl = fmt.Sprintf(`//go:wasmimport %s %s
//go:noescape
func %s(ptr unsafe.Pointer, length uint32, outPtr unsafe.Pointer) int32

`, importModule, exportName, ffi)
	}

	type entry struct {
		name  string
		index int
	}
	var entries []entry
	for name, idx := range namedGroups {
		entries = append(entries, entry{name, idx})
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].index < entries[j].index })

	var assigns strings.Builder
	for _, e := range entries {
		fmt.Fprintf(&assigns,
			"\t\t\tif buf[%d] >= 0 { named[\"%s\"] = []int{int(buf[%d]) + pos, int(buf[%d]) + pos} }\n",
			e.index*2, e.name, e.index*2, e.index*2+1)
	}

	return ffiDecl + fmt.Sprintf(`// %s returns an iterator over named capture groups of all non-overlapping matches.
// Each iteration yields a map of group name → [start,end] absolute byte offsets.
func %s(input []byte) iter.Seq[map[string][]int] {
	return func(yield func(map[string][]int) bool) {
		pos := 0
		for pos <= len(input) {
			var ptr unsafe.Pointer
			if pos < len(input) {
				ptr = unsafe.Pointer(&input[pos])
			}
			buf := make([]int32, %d)
			r := %s(ptr, uint32(len(input)-pos), unsafe.Pointer(&buf[0]))
			if r == %d {
				panic("%s")
			}
			if r < 0 {
				if pos == len(input) {
					break
				}
				pos++
				continue
			}
			named := make(map[string][]int, %d)
%s			matchEnd := 0
			if buf[1] >= 0 {
				matchEnd = int(buf[1])
			}
			if matchEnd > 0 {
				pos += matchEnd
			} else {
				pos++
			}
			if !yield(named) {
				break
			}
		}
	}
}

`, pub, pub, slotCount, ffi, btOverflow, btOverflowMsg(pub), len(entries), assigns.String())
}

// genGoStubsBody returns the body (no header, no imports) for single-pattern stubs.
// Returns (body string, needsIter bool).
func genGoStubsBody(entries []config.RegexEntry, importModule string) (string, bool, error) {
	var parts []string
	needsIter := false
	for _, re := range entries {
		part, err := genGoStubsForEntry(re, importModule)
		if err != nil {
			return "", false, err
		}
		if part != "" {
			parts = append(parts, part)
			if re.FindFunc != "" || re.GroupsFunc != "" || re.NamedGroupsFunc != "" {
				needsIter = true
			}
		}
	}
	return strings.Join(parts, ""), needsIter, nil
}

// genGoStubFile generates the full Go stub file for a slice of entries (no sets).
// Kept for backward compatibility with tests.
func genGoStubFile(entries []config.RegexEntry, importModule, pkgName string) (string, error) {
	body, needsIter, err := genGoStubsBody(entries, importModule)
	if err != nil || body == "" {
		return "", err
	}
	var sb strings.Builder
	sb.WriteString("// Auto-generated by regexped. Do not edit.\n\n")
	sb.WriteString("//go:build wasip1\n\n")
	fmt.Fprintf(&sb, "package %s\n\n", pkgName)
	if needsIter {
		sb.WriteString("import (\n\t\"iter\"\n\t\"unsafe\"\n)\n\n")
	} else {
		sb.WriteString("import \"unsafe\"\n\n")
	}
	sb.WriteString(body)
	return sb.String(), nil
}

// genGoStubsForEntry generates the Go stub content for a single regexp entry.
func genGoStubsForEntry(re config.RegexEntry, importModule string) (string, error) {
	var out string
	written := false

	if re.MatchFunc != "" {
		out += genGoMatchStub(importModule, re.MatchFunc)
		written = true
	}
	if re.FindFunc != "" {
		out += genGoFindStub(importModule, re.FindFunc)
		written = true
	}
	if re.GroupsFunc != "" || re.NamedGroupsFunc != "" {
		numGroups, namedGroups, err := extractGroupInfo(re.Pattern)
		if err != nil {
			return "", err
		}
		exportName := re.GroupsExportName()
		if re.GroupsFunc != "" {
			out += genGoGroupsStub(importModule, re.GroupsFunc, exportName, true, numGroups)
			written = true
		}
		if re.NamedGroupsFunc != "" {
			declareFFI := re.GroupsFunc == ""
			out += genGoNamedGroupsStub(importModule, re.NamedGroupsFunc, exportName, declareFFI, numGroups, namedGroups)
			written = true
		}
	}

	if !written {
		return "", nil
	}
	return out, nil
}
