package generate

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"github.com/qrdl/regexped/config"
)

// genJSStubFile generates the content of an ES module JS stub that loads the
// merged WASM and exports wrapper functions for every regex entry in cfg.
func genJSStubFile(cfg config.BuildConfig) (string, error) {
	wasmBase := filepath.Base(cfg.Output)

	// Determine whether any entry needs a slots buffer (groups/named_groups).
	needSlots := false
	for _, re := range cfg.Regexes {
		if re.CaptureStubsRequested() {
			needSlots = true
			break
		}
	}

	var sb strings.Builder
	sb.WriteString("// Auto-generated by regexped. Do not edit.\n\n")

	// WASM load — merged module exports its own memory, no imports needed.
	fmt.Fprintf(&sb, "const _r = await WebAssembly.instantiateStreaming(\n")
	fmt.Fprintf(&sb, "    fetch(new URL('./%s', import.meta.url)));\n", wasmBase)
	sb.WriteString("const _exp = _r.instance.exports;\n")
	sb.WriteString("const _mem = new Uint8Array(_exp.memory.buffer);\n")
	sb.WriteString("const _enc = new TextEncoder();\n")
	if needSlots {
		sb.WriteString("const _SLOTS = 1024; // capture group output buffer offset\n")
	}
	sb.WriteString("\n")
	sb.WriteString("function _b(input) {\n")
	sb.WriteString("    return typeof input === 'string' ? _enc.encode(input) : input;\n")
	sb.WriteString("}\n\n")

	for _, re := range cfg.Regexes {
		if re.MatchFunc != "" {
			sb.WriteString(genJSMatchFunc(re.MatchFunc))
		}
		if re.FindFunc != "" {
			sb.WriteString(genJSFindFunc(re.FindFunc))
		}
		if re.GroupsFunc != "" {
			numGroups, _, err := extractGroupInfo(re.Pattern)
			if err != nil {
				return "", fmt.Errorf("entry %s: %w", re.ImportModule, err)
			}
			sb.WriteString(genJSGroupsFunc(re.GroupsFunc, numGroups))
		}
		if re.NamedGroupsFunc != "" {
			numGroups, namedGroups, err := extractGroupInfo(re.Pattern)
			if err != nil {
				return "", fmt.Errorf("entry %s: %w", re.ImportModule, err)
			}
			sb.WriteString(genJSNamedGroupsFunc(re.NamedGroupsFunc, re.GroupsExportName(), numGroups, namedGroups))
		}
	}

	return sb.String(), nil
}

// genJSMatchFunc generates a JS export for an anchored match.
// Returns true if the full input matches, false otherwise.
func genJSMatchFunc(funcName string) string {
	return fmt.Sprintf(`// %s — anchored match; returns true if the full input matches.
export function %s(input) {
    const b = _b(input);
    _mem.set(b, 0);
    return _exp['%s'](0, b.length) === b.length;
}

`, funcName, funcName, funcName)
}

// genJSFindFunc generates a JS generator for non-anchored find.
// Yields [start, end] absolute byte positions for each non-overlapping match.
func genJSFindFunc(funcName string) string {
	return fmt.Sprintf(`// %s — yields [start, end] for each non-overlapping match.
export function* %s(input) {
    const b = _b(input);
    let off = 0;
    while (off <= b.length) {
        _mem.set(b.subarray(off), 0);
        const r = _exp['%s'](0, b.length - off);
        if (r < 0n) break;
        const relStart = Number(r >> 32n);
        const relEnd   = Number(r & 0xFFFFFFFFn);
        yield [off + relStart, off + relEnd];
        off += relEnd > relStart ? relEnd : relStart + 1;
    }
}

`, funcName, funcName, funcName)
}

// genJSGroupsFunc generates a JS generator for indexed capture groups.
// Yields an array per match; each element is [start, end] or null for
// unmatched groups. Index 0 is the full match.
func genJSGroupsFunc(funcName string, numGroups int) string {
	slotCount := numGroups * 2
	return fmt.Sprintf(`// %s — yields capture group arrays per match.
// Each element is [start, end] (absolute) or null for unmatched groups.
// Index 0 is the full match.
export function* %s(input) {
    const b = _b(input);
    let off = 0;
    while (off <= b.length) {
        _mem.set(b.subarray(off), 0);
        const slots = new Int32Array(_exp.memory.buffer, _SLOTS, %d);
        slots.fill(-1);
        if (_exp['%s'](0, b.length - off, _SLOTS) < 0) {
            if (off === b.length) break;
            off++;
            continue;
        }
        const matchEnd = slots[1] >= 0 ? slots[1] : 0;
        const result = [];
        for (let i = 0; i < %d; i++) {
            const s = slots[i * 2], e = slots[i * 2 + 1];
            result.push(s < 0 ? null : [off + s, off + e]);
        }
        off += matchEnd > 0 ? matchEnd : 1;
        yield result;
    }
}

`, funcName, funcName, slotCount, funcName, numGroups)
}

// genJSNamedGroupsFunc generates a JS generator for named capture groups.
// Yields a plain object per match with name → [start, end] entries.
// Only groups that participated in the match are included.
func genJSNamedGroupsFunc(funcName, exportName string, numGroups int, namedGroups map[string]int) string {
	slotCount := numGroups * 2

	type entry struct {
		name  string
		index int
	}
	var entries []entry
	for name, idx := range namedGroups {
		entries = append(entries, entry{name, idx})
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].index < entries[j].index })

	var inserts strings.Builder
	for _, e := range entries {
		fmt.Fprintf(&inserts,
			"        if (slots[%d] >= 0) result['%s'] = [off + slots[%d], off + slots[%d]];\n",
			e.index*2, e.name, e.index*2, e.index*2+1)
	}

	return fmt.Sprintf(`// %s — yields named capture group objects per match.
// Each object maps name → [start, end] (absolute) for participating groups.
export function* %s(input) {
    const b = _b(input);
    let off = 0;
    while (off <= b.length) {
        _mem.set(b.subarray(off), 0);
        const slots = new Int32Array(_exp.memory.buffer, _SLOTS, %d);
        slots.fill(-1);
        if (_exp['%s'](0, b.length - off, _SLOTS) < 0) {
            if (off === b.length) break;
            off++;
            continue;
        }
        const matchEnd = slots[1] >= 0 ? slots[1] : 0;
        const result = {};
%s        off += matchEnd > 0 ? matchEnd : 1;
        yield result;
    }
}

`, funcName, funcName, slotCount, exportName, inserts.String())
}
