package generate

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/qrdl/regexped/config"
)

// jsStub generates a JS ES module stub file for all regex entries and sets in cfg.
// out is the full output path or "-" for stdout.
func jsStub(cfg config.BuildConfig, out string) error {
	content, err := genJSStubFile(cfg)
	if err != nil {
		return fmt.Errorf("generate JS stub: %w", err)
	}
	if out == "-" {
		_, err := os.Stdout.WriteString(content)
		return err
	}
	return writeStub(out, []byte(content))
}

// genJSSetSection returns JS set wrappers appended to the module body.
// Called from genJSStubFile's inner builder when cfg.Sets is non-empty.
func genJSSetSection(cfg config.BuildConfig) string {
	if !hasSetExports(cfg) {
		return ""
	}
	var out strings.Builder
	out.WriteString("\n// ---- set composition wrappers ----\n\n")
	for _, s := range cfg.Sets {
		bs := batchSize(s, cfg)
		if s.FindAll != "" || s.FindAny != "" {
			wasmExport := s.FindAll
			if wasmExport == "" {
				wasmExport = s.FindAny
			}
			if s.FindAll != "" {
				fmt.Fprintf(&out, `export function* %s(input) {
    const b = _b(input);
    _resize(b.length, %d*12);
    const outBuf = new Int32Array(_mem.buffer, _outBase, %d*3);
    _mem.set(b, _inBase);
    let startPos = 0;
    while (true) {
        const n = _exp['%s'](_inBase, b.length, _outBase, %d, startPos);
        if (n <= 0) break;
        for (let i = 0; i < n; i++) {
            yield { patternId: outBuf[i*3], start: outBuf[i*3+1], end: outBuf[i*3+1]+outBuf[i*3+2] };
        }
        const last = outBuf[(n-1)*3+2]; startPos = outBuf[(n-1)*3+1] + (last > 0 ? last : 1);
    }
}
`, s.FindAll, bs, bs, wasmExport, bs)
			}
			if s.FindAny != "" {
				fmt.Fprintf(&out, `export function %s(input) {
    const b = _b(input);
    _resize(b.length);
    const outBuf = new Int32Array(_mem.buffer, _outBase, 3);
    _mem.set(b, _inBase);
    const n = _exp['%s'](_inBase, b.length, _outBase, 1, 0);
    if (n <= 0) return null;
    return { patternId: outBuf[0], start: outBuf[1], end: outBuf[1]+outBuf[2] };
}
`, s.FindAny, wasmExport)
			}
		}
		if s.Match != "" {
			fmt.Fprintf(&out, `export function %s(input) {
    const b = _b(input);
    _resize(b.length);
    const outBuf = new Int32Array(_mem.buffer, _outBase, 3);
    _mem.set(b, _inBase);
    const n = _exp['%s'](_inBase, b.length, _outBase, 1);
    if (n <= 0) return null;
    return { patternId: outBuf[0], start: outBuf[1], end: outBuf[1]+outBuf[2] };
}
`, s.Match, s.Match)
		}
	}
	if hasEmitNameMap(cfg) {
		out.WriteString("const _patternNames = [")
		for i, re := range cfg.Regexes {
			if i > 0 {
				out.WriteString(", ")
			}
			fmt.Fprintf(&out, "%q", re.Name)
		}
		out.WriteString("];\nexport function patternName(id) { return _patternNames[id] ?? ''; }\n")
	}
	return out.String()
}

// genJSStubFile generates the content of an ES module JS stub that exports
// wrapper functions for every regex entry in cfg.  The caller is responsible
// for loading the WASM file and passing the bytes (or a WebAssembly.Module)
// to the exported init() function before calling any matcher.
func genJSStubFile(cfg config.BuildConfig) (string, error) {
	// Determine whether any entry needs a slots buffer (groups/named_groups).
	var sb strings.Builder
	sb.WriteString("// Auto-generated by regexped. Do not edit.\n\n")

	sb.WriteString("let _exp, _mem;\n")
	sb.WriteString("let _inBase = 0;  // byte offset where input is written (after DFA table pages)\n")
	sb.WriteString("let _outBase = 0; // byte offset for output buffers and capture slots\n")
	sb.WriteString("const _enc = new TextEncoder();\n")
	sb.WriteString("\n")

	// init() accepts a BufferSource (ArrayBuffer / Buffer / Uint8Array) or a
	// pre-compiled WebAssembly.Module — any value accepted by
	// WebAssembly.instantiate().  The caller chooses how to load the file:
	//
	//   Browser:            await init(await fetch('./merged.wasm').then(r => r.arrayBuffer()))
	//   Node.js:            await init(readFileSync('./merged.wasm'))
	//   Cloudflare Workers: import wasm from './merged.wasm'; await init(wasm)
	sb.WriteString("export async function init(wasm) {\n")
	sb.WriteString("    const r = await WebAssembly.instantiate(wasm);\n")
	sb.WriteString("    const instance = r instanceof WebAssembly.Instance ? r : r.instance;\n")
	sb.WriteString("    _exp = instance.exports;\n")
	sb.WriteString("    const _m = _exp.memory;\n")
	sb.WriteString("    _inBase = _m.buffer.byteLength; // first byte after DFA table pages\n")
	sb.WriteString("    _m.grow(2);                     // 1 page for input, 1 page for output/slots\n")
	sb.WriteString("    _outBase = _inBase + 65536;\n")
	sb.WriteString("    _mem = new Uint8Array(_m.buffer); // re-acquire after grow\n")
	sb.WriteString("}\n\n")

	sb.WriteString("function _b(input) {\n")
	sb.WriteString("    return typeof input === 'string' ? _enc.encode(input) : input;\n")
	sb.WriteString("}\n\n")
	sb.WriteString("function _resize(inputLen, outBytes) {\n")
	sb.WriteString("    const ob = outBytes && outBytes > 65536 ? outBytes : 65536;\n")
	sb.WriteString("    _outBase = _inBase + Math.max(1, Math.ceil(inputLen / 65536)) * 65536;\n")
	sb.WriteString("    const needed = _outBase + ob;\n")
	sb.WriteString("    if (needed > _mem.buffer.byteLength) {\n")
	sb.WriteString("        _exp.memory.grow(Math.ceil((needed - _mem.buffer.byteLength) / 65536));\n")
	sb.WriteString("        _mem = new Uint8Array(_exp.memory.buffer);\n")
	sb.WriteString("    }\n")
	sb.WriteString("}\n\n")

	for _, re := range cfg.Regexes {
		if re.MatchFunc != "" {
			sb.WriteString(genJSMatchFunc(re.MatchFunc))
		}
		if re.FindFunc != "" {
			sb.WriteString(genJSFindFunc(re.FindFunc))
		}
		if re.GroupsFunc != "" {
			numGroups, _, err := extractGroupInfo(re.Pattern)
			if err != nil {
				return "", fmt.Errorf("pattern %q: %w", re.Pattern, err)
			}
			sb.WriteString(genJSGroupsFunc(re.GroupsFunc, numGroups))
		}
		if re.NamedGroupsFunc != "" {
			numGroups, namedGroups, err := extractGroupInfo(re.Pattern)
			if err != nil {
				return "", fmt.Errorf("pattern %q: %w", re.Pattern, err)
			}
			sb.WriteString(genJSNamedGroupsFunc(re.NamedGroupsFunc, re.GroupsExportName(), numGroups, namedGroups))
		}
	}

	sb.WriteString(genJSSetSection(cfg))
	return sb.String(), nil
}

// genJSMatchFunc generates a JS export for an anchored match.
// Returns [endPos, true] on match, or [0, false] if no match.
func genJSMatchFunc(funcName string) string {
	return fmt.Sprintf(`// %s — anchored match; returns [endPos, true] on match or [0, false] if no match.
export function %s(input) {
    const b = _b(input);
    _resize(b.length);
    _mem.set(b, _inBase);
    const r = _exp['%s'](_inBase, b.length);
    if (r < 0) return [0, false];
    return [r, true];
}

`, funcName, funcName, funcName)
}

// genJSFindFunc generates a JS generator for non-anchored find.
// Yields [start, end] absolute byte positions for each non-overlapping match.
func genJSFindFunc(funcName string) string {
	return fmt.Sprintf(`// %s — yields [start, end] for each non-overlapping match.
export function* %s(input) {
    const b = _b(input);
    _resize(b.length);
    let off = 0;
    while (off <= b.length) {
        _mem.set(b.subarray(off), _inBase);
        const r = _exp['%s'](_inBase, b.length - off);
        if (r < 0n) break;
        const relStart = Number(r >> 32n);
        const relEnd   = Number(r & 0xFFFFFFFFn);
        yield [off + relStart, off + relEnd];
        off += relEnd > relStart ? relEnd : relStart + 1;
    }
}

`, funcName, funcName, funcName)
}

// genJSGroupsFunc generates a JS generator for indexed capture groups.
// Yields an array per match; each element is [start, end] or null for
// unmatched groups. Index 0 is the full match.
func genJSGroupsFunc(funcName string, numGroups int) string {
	slotCount := numGroups * 2
	return fmt.Sprintf(`// %s — yields capture group arrays per match.
// Each element is [start, end] (absolute) or null for unmatched groups.
// Index 0 is the full match.
export function* %s(input) {
    const b = _b(input);
    _resize(b.length);
    let off = 0;
    while (off <= b.length) {
        _mem.set(b.subarray(off), _inBase);
        const slots = new Int32Array(_mem.buffer, _outBase, %d);
        slots.fill(-1);
        if (_exp['%s'](_inBase, b.length - off, _outBase) < 0) {
            if (off === b.length) break;
            off++;
            continue;
        }
        const matchEnd = slots[1] >= 0 ? slots[1] : 0;
        const result = [];
        for (let i = 0; i < %d; i++) {
            const s = slots[i * 2], e = slots[i * 2 + 1];
            result.push(s < 0 ? null : [off + s, off + e]);
        }
        off += matchEnd > 0 ? matchEnd : 1;
        yield result;
    }
}

`, funcName, funcName, slotCount, funcName, numGroups)
}

// genJSNamedGroupsFunc generates a JS generator for named capture groups.
// Yields a plain object per match with name → [start, end] entries.
// Only groups that participated in the match are included.
func genJSNamedGroupsFunc(funcName, exportName string, numGroups int, namedGroups map[string]int) string {
	slotCount := numGroups * 2

	type entry struct {
		name  string
		index int
	}
	var entries []entry
	for name, idx := range namedGroups {
		entries = append(entries, entry{name, idx})
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].index < entries[j].index })

	var inserts strings.Builder
	for _, e := range entries {
		fmt.Fprintf(&inserts,
			"        if (slots[%d] >= 0) result['%s'] = [off + slots[%d], off + slots[%d]];\n",
			e.index*2, e.name, e.index*2, e.index*2+1)
	}

	return fmt.Sprintf(`// %s — yields named capture group objects per match.
// Each object maps name → [start, end] (absolute) for participating groups.
export function* %s(input) {
    const b = _b(input);
    _resize(b.length);
    let off = 0;
    while (off <= b.length) {
        _mem.set(b.subarray(off), _inBase);
        const slots = new Int32Array(_mem.buffer, _outBase, %d);
        slots.fill(-1);
        if (_exp['%s'](_inBase, b.length - off, _outBase) < 0) {
            if (off === b.length) break;
            off++;
            continue;
        }
        const matchEnd = slots[1] >= 0 ? slots[1] : 0;
        const result = {};
%s        off += matchEnd > 0 ? matchEnd : 1;
        yield result;
    }
}

`, funcName, funcName, slotCount, exportName, inserts.String())
}
