package generate

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/qrdl/regexped/config"
)

// The Rust stub for `wasm_format: component`.
//
// PARITY is the requirement: the public surface here is identical to the
// module-format stub's — `pub mod <rust_module>`, the `Error`/`Result` pair,
// `Span`, `<Func>Iter` for find and groups, the named-group index constants —
// so a user switching `wasm_format` changes no calling code.
//
// What differs is entirely below that surface. A component consumer cannot
// declare its imports by hand: `wasm32-wasip2` refuses a bare
// `#[link(wasm_import_module = …)]` with "module requires an import interface
// named …", because the component-type metadata a binding generator embeds is
// mandatory. So the stub opens with `wit_bindgen::generate!` and wraps the
// typed functions it produces.
//
// The WIT is passed INLINE rather than as a `wit/` directory, because the
// macro's `path:` option resolves against the crate manifest, which regexped
// cannot locate from `stub_file`. Inline keeps the stub a single file, which is
// the module format's property too.
//
// The user's Cargo.toml needs `wit-bindgen`. That is the one place build parity
// does not hold, and the generated header says so.

// witBindgenReq is the dependency line the generated stub tells the user to add.
// Pinned deliberately: the wrapper below references the macro's generated module
// paths, and those are wit-bindgen's to change.
const witBindgenReq = `wit-bindgen = "0.61"`

// rustComponentStub writes the component-flavoured Rust stub.
func rustComponentStub(cfg config.BuildConfig, out string) error {
	text, err := genRustComponentStubFile(cfg)
	if err != nil {
		return fmt.Errorf("generate Rust component stub: %w", err)
	}
	if text == "" {
		return nil
	}
	if out == "-" {
		_, err := os.Stdout.WriteString(text)
		return err
	}
	return writeStub(out, []byte(text))
}

// genRustComponentStubFile renders the whole stub.
func genRustComponentStubFile(cfg config.BuildConfig) (string, error) {
	// ONE derivation, as in the C generator: the package, the world, the
	// functions and the sets all come from witParts, which is where the naming
	// rules are enforced. Everything below works from its output, so no line
	// here carries an error branch for a failure it has already ruled out.
	pkg, world, funcs, sets, err := witParts(cfg)
	if err != nil {
		return "", err
	}
	witText := renderWit(cfg, pkg, world, funcs, sets)
	// KEBAB names, not the snake ones: `match` binds as a snake function, but
	// the two ITERATING exports bind as RESOURCE TYPES, whose Rust spelling is
	// the UpperCamel of the same kebab. One map, converted per shape at the use
	// site, rather than two that could disagree about which export is which.
	inner, err := genRustComponentInner(cfg, kebabNames(funcs))
	if err != nil {
		return "", err
	}
	inner += genRustComponentSetInner(cfg, sets)
	if inner == "" {
		return "", nil
	}
	// `super::`, not `crate::`. The macro expands wherever this file is INCLUDED,
	// and the wrapper always sits exactly one level below that — inside
	// `pub mod <rust_module>` — so `super::` reaches the generated modules whether
	// the stub is included at the crate root or inside a `mod`. `crate::` only
	// worked for the first case and failed to compile in the second.
	inner = bindingPaths(pkg, len(funcs) > 0, len(sets) > 0) + inner
	// Same placement rule as the canonical export names: the version follows the
	// INTERFACE name. `regexped:secrets@2.3.0/matcher` does not resolve.
	//
	// A config can declare patterns, sets, or both, and the consumer world
	// imports only the interfaces that exist — importing an interface the WIT
	// document does not define is a macro error.
	var imports []string
	ver := ""
	if cfg.WitVersion != "" {
		ver = "@" + cfg.WitVersion
	}
	if len(funcs) > 0 {
		imports = append(imports, "regexped:"+pkg+"/matcher"+ver)
	}
	if len(sets) > 0 {
		imports = append(imports, "regexped:"+pkg+"/sets"+ver)
	}
	var importLines strings.Builder
	for _, i := range imports {
		fmt.Fprintf(&importLines, "    import %s;\n", i)
	}

	var b strings.Builder
	fmt.Fprintf(&b, `// Auto-generated by regexped. Do not edit.
//
// This is the COMPONENT stub (wasm_format: component). Its API is identical to
// the module-format stub's, so switching formats changes no calling code.
//
// Add to Cargo.toml:
//
//     [dependencies]
//     %s
//
// Build the consumer as a component and compose it with the regexp component.
// "regexped merge" is the SAME command a module build uses — it dispatches on
// wasm_format and shells out to wac here, to wasm-merge there:
//
//     cargo build --release --target wasm32-wasip2
//     regexped merge --config=<config>.yaml --main=<your>.wasm %s
//     wasmtime run <output from the config, or --output>
//
`, witBindgenReq, filepath.Base(cfg.WasmFile))

	// The consumer world imports our interface. It lives in its own package so
	// it cannot collide with the interface package nested beside it.
	fmt.Fprintf(&b, `wit_bindgen::generate!({
    inline: r#"
package regexped-consumer:%s;

world %s {
%s}

%s
    "#,
    world: "%s",
    // Required: the interface comes from a package other than the consumer's
    // own, and without this the macro refuses with a missing-with-mapping error.
    generate_all,
});

`, pkg, consumerWorld(world), importLines.String(), nestPackage(witText), consumerWorld(world))

	b.WriteString(wrapRustModule(rustErrorPreamble()+inner, cfg.RustModuleName()))
	return b.String(), nil
}

// consumerWorld names the world the STUB declares. It must differ from the
// component's own world name, which describes the exporting side.
func consumerWorld(world string) string { return world + "-consumer" }

// nestPackage rewrites the generated .wit — a top-level `package X;` plus its
// items — into WIT's nested form, `package X { … }`, so it can sit beside the
// consumer package in one inline document. The export world is DROPPED: a
// dependency package supplies the interface only, and leaving an exporting world
// in it makes the document describe something else.
func nestPackage(witText string) string {
	var pkg string
	var body []string
	for _, l := range dropWorld(witText) {
		t := strings.TrimSpace(l)
		switch {
		case strings.HasPrefix(t, "//"):
			continue
		case strings.HasPrefix(t, "package ") && strings.HasSuffix(t, ";"):
			pkg = strings.TrimSuffix(strings.TrimPrefix(t, "package "), ";")
			continue
		}
		body = append(body, l)
	}
	var b strings.Builder
	fmt.Fprintf(&b, "package %s {\n", pkg)
	blank := false
	for _, l := range body {
		if strings.TrimSpace(l) == "" {
			// Stripping doc comments leaves runs of blank lines; collapse them
			// so the inline WIT reads like the file it came from.
			if !blank {
				b.WriteString("\n")
			}
			blank = true
			continue
		}
		blank = false
		fmt.Fprintf(&b, "    %s\n", l)
	}
	b.WriteString("}\n")
	return b.String()
}

// genRustComponentInner renders the per-entry wrappers, in config order.
func genRustComponentInner(cfg config.BuildConfig, names map[string]string) (string, error) {
	var b strings.Builder
	for _, re := range cfg.Regexps {
		if re.MatchFunc != "" {
			b.WriteString(genRustComponentMatch(re.MatchFunc, rustWitFuncName(names[re.MatchFunc])))
		}
		if re.FindFunc != "" {
			b.WriteString(genRustComponentFind(re.FindFunc, rustResourceType(names[re.FindFunc])))
		}
		if re.GroupsFunc != "" {
			numGroups, namedGroups, err := extractGroupInfo(re.Pattern)
			if err != nil {
				return "", fmt.Errorf("regexp %q: %w", re.Pattern, err)
			}
			b.WriteString(genRustComponentGroups(re.GroupsFunc, rustResourceType(names[re.GroupsFunc]), numGroups))
			b.WriteString(genRustGroupIndexConsts(re.GroupsFunc, numGroups, namedGroups))
		}
	}
	return b.String(), nil
}

// bindingPaths are the `use` lines that reach the macro's generated bindings.
//
// `super::`, not `crate::`, makes the stub position-independent: the macro
// expands at the include site and the wrapper is one level below it, so the
// relative path holds whether the file is included at the crate root or inside a
// `mod`. An earlier `crate::` compiled only in the first case.
//
// A `use` for an interface the document does not define does not compile, so the
// two flags are passed in rather than guessed here.
func bindingPaths(pkg string, patterns, sets bool) string {
	base := "super::regexped::" + strings.ReplaceAll(pkg, "-", "_") + "::"
	var b strings.Builder
	if patterns {
		fmt.Fprintf(&b, "use %smatcher;\n", base)
	}
	if sets {
		fmt.Fprintf(&b, "use %ssets;\n", base)
	}
	b.WriteString("\n")
	// ONE conversion per interface from its error enum into the stub's Error,
	// so every wrapper converts with Error::from and a new enum case changes
	// this and nothing else. There were eight identical match blocks.
	for _, iface := range []struct {
		name string
		used bool
	}{{"matcher", patterns}, {"sets", sets}} {
		if !iface.used {
			continue
		}
		fmt.Fprintf(&b, `impl From<%[1]s::ErrorCode> for Error {
    fn from(e: %[1]s::ErrorCode) -> Self {
        match e {
            %[1]s::ErrorCode::BacktrackOverflow => Error::BacktrackOverflow,
            %[1]s::ErrorCode::MalformedCache => Error::MalformedCache,
            %[1]s::ErrorCode::OutOfOrder => Error::OutOfOrder,
        }
    }
}

`, iface.name)
	}
	return b.String()
}

func genRustComponentMatch(funcName, witFunc string) string {
	return fmt.Sprintf(`/// Returns the end position of the match (exclusive), or Ok(None) if the input
/// does not match. The match is anchored: it starts at the beginning of input.
///
/// # Errors
/// Err(Error::BacktrackOverflow) if the pattern compiled to the Backtracking
/// engine and the input exhausted its frame budget: the engine cannot tell
/// whether the input matches, so Ok(None) — a definite "no" — would be a lie.
pub fn %s(input: &[u8]) -> Result<Option<usize>> {
    match matcher::%s(input) {
        Ok(Some(end)) => Ok(Some(end as usize)),
        Ok(None) => Ok(None),
        Err(e) => Err(Error::from(e)),
    }
}

`, funcName, witFunc)
}

func genRustComponentFind(funcName, resType string) string {
	iterName := iterTypeName(funcName)
	return fmt.Sprintf(`pub struct %[1]s<'a> {
    /// The scan inside the regexp component, created by the first call to next.
    /// The module-format iterator allocates nothing until it is driven, and
    /// neither does this one: an iterator built and dropped undriven costs no
    /// copy of the input into the component.
    ///
    /// The resource holds the input and the POSITION, which is why this struct
    /// no longer tracks an offset of its own past construction — the advance is
    /// the component's, and it is the same rule the module stub applies.
    inner: Option<matcher::%[2]s>,
    input: &'a [u8],
    offset: u32,
    /// End of the last REPORTED match, for Go's adjacent-empty rule. It stays
    /// HERE rather than moving into the component: it decides what is reported,
    /// not where the scan goes, and the raw resource must answer the same
    /// matches the raw module export does.
    prev_end: Option<usize>,
    /// Set once the iterator has finished, whether by exhausting the input or
    /// by reporting an error. Without it a caller who logs the Err and keeps
    /// pulling re-runs the identical call for ever, because the overflow is
    /// deterministic and the position never advanced.
    done: bool,
}

impl Iterator for %[1]s<'_> {
    type Item = Result<(usize, usize)>;

    fn next(&mut self) -> Option<Result<(usize, usize)>> {
        loop {
            if self.done {
                return None;
            }
            let (input, offset) = (self.input, self.offset);
            let inner = self.inner.get_or_insert_with(|| matcher::%[2]s::new(input, offset));
            match inner.next() {
                // Before the finished test: the engine gave up and cannot say
                // whether more matches exist, so ending iteration would report
                // success.
                Err(e) => {
                    self.done = true;
                    return Some(Err(Error::from(e)));
                }
                Ok(None) => {
                    self.done = true;
                    return None;
                }
                Ok(Some((start, end))) => {
                    let (abs_start, abs_end) = (start as usize, end as usize);
                    // Go's FindAllIndex rule: an EMPTY match beginning exactly
                    // where the previous match ended is suppressed. The scan has
                    // already advanced past it inside the component, so this only
                    // decides whether it is REPORTED.
                    if abs_start == abs_end && self.prev_end == Some(abs_start) {
                        continue;
                    }
                    self.prev_end = Some(abs_end);
                    return Some(Ok((abs_start, abs_end)));
                }
            }
        }
    }
}

impl std::iter::FusedIterator for %[1]s<'_> {}

/// Returns an iterator over all non-overlapping matches at or after offset.
/// Each item is an absolute (start, end) byte range.
///
/// The input crosses into the regexp component ONCE, when the scan starts.
/// Dropping the iterator ends the scan and releases what the component held.
///
/// # Errors
/// An item is Err(Error::BacktrackOverflow) if the pattern compiled to the
/// Backtracking engine and the input exhausted its frame budget: the engine
/// cannot tell whether more matches exist, so simply ending iteration would be
/// a lie. The iterator is fused, so it yields nothing after that.
pub fn %[3]s(input: &[u8], offset: usize) -> %[1]s<'_> {
    %[1]s { inner: None, input, offset: offset as u32, prev_end: None, done: false }
}

`, iterName, resType, funcName)
}

func genRustComponentGroups(funcName, resType string, numGroups int) string {
	iterName := iterTypeName(funcName)
	return fmt.Sprintf(`pub struct %[1]s<'a> {
    /// See the find iterator: the scan lives in the component, created lazily,
    /// and dropping this ends it.
    inner: Option<matcher::%[2]s>,
    input: &'a [u8],
    offset: u32,
    prev_end: Option<usize>,
    done: bool,
}

impl Iterator for %[1]s<'_> {
    type Item = Result<Vec<Option<Span>>>;

    fn next(&mut self) -> Option<Result<Vec<Option<Span>>>> {
        loop {
            if self.done {
                return None;
            }
            let (input, offset) = (self.input, self.offset);
            let inner = self.inner.get_or_insert_with(|| matcher::%[2]s::new(input, offset));
            match inner.next() {
                Err(e) => {
                    self.done = true;
                    return Some(Err(Error::from(e)));
                }
                // An EMPTY list is how this shape says "finished", where find
                // says none: a list is already an option of sorts, and one more
                // discriminant would carry a distinction no caller can act on.
                Ok(slots) if slots.is_empty() => {
                    self.done = true;
                    return None;
                }
                Ok(slots) => {
                    // Slot 0 is the whole match and is always present when the
                    // engine reported one.
                    let (abs_start, abs_end) = match slots.first().copied().flatten() {
                        Some((s, e)) => (s as usize, e as usize),
                        None => {
                            self.done = true;
                            return None;
                        }
                    };
                    if abs_start == abs_end && self.prev_end == Some(abs_start) {
                        continue;
                    }
                    self.prev_end = Some(abs_end);
                    let groups: Vec<Option<Span>> = slots
                        .into_iter()
                        .map(|g| g.map(|(s, e)| Span { start: s as usize, end: e as usize }))
                        .collect();
                    return Some(Ok(groups));
                }
            }
        }
    }
}

impl std::iter::FusedIterator for %[1]s<'_> {}

/// Iterates the non-overlapping matches at or after offset: each item is one
/// MATCH, represented by its capture groups.
///
/// The Vec always holds one entry per group (%[4]d here), index 0 being the whole
/// match, so its length does not depend on which groups participated — a group
/// that did not is None. Address a named group with the generated index
/// constant. Positions are absolute byte offsets.
///
/// The input crosses into the regexp component ONCE, when the scan starts.
///
/// # Errors
/// An item is Err(Error::BacktrackOverflow) if the pattern compiled to the
/// Backtracking engine and the input exhausted its frame budget.
pub fn %[3]s(input: &[u8], offset: usize) -> %[1]s<'_> {
    %[1]s { inner: None, input, offset: offset as u32, prev_end: None, done: false }
}

`, iterName, resType, funcName, numGroups)
}
