package generate

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/qrdl/regexped/config"
)

// rustStub generates a Rust stub file for all regex entries and sets in cfg.
// out is the full output path or "-" for stdout.
func rustStub(cfg config.BuildConfig, out string) error {
	singleInner, err := genRustStubsInner(cfg.Regexes, cfg.ImportModule)
	if err != nil {
		return fmt.Errorf("generate Rust stub: %w", err)
	}
	setInner := genRustSetInner(cfg)
	allInner := singleInner + setInner
	if allInner == "" {
		return nil
	}
	combined := "// Auto-generated by regexped. Do not edit.\n\n" + wrapRustModule(allInner, cfg.ImportModule)
	if out == "-" {
		_, err := os.Stdout.WriteString(combined)
		return err
	}
	return writeStub(out, []byte(combined))
}

// genRustSetInner generates Rust wrappers for all sets in cfg.
// Returns unindented content for placement INSIDE pub mod <importModule>.
// Emits SetMatch type (once), per-set iterators/wrappers, and optional pattern_name().
// SetMatch is used for all match operations (find_all, find_any, anchored match).
func genRustSetInner(cfg config.BuildConfig) string {
	if !hasSetExports(cfg) {
		return ""
	}
	var out strings.Builder
	out.WriteString(`/// A match from a set find_any, find_all, or anchored match operation.
#[derive(Debug, Clone, Copy)]
pub struct SetMatch {
    pub pattern_id: usize,
    pub start: usize,
    pub end: usize,
}

impl SetMatch {
    /// Returns the matched byte range as a Rust Range.
    pub fn range(self) -> std::ops::Range<usize> { self.start..self.end }
}

`)
	for _, s := range cfg.Sets {
		bs := batchSize(s)
		if s.FindAll != "" || s.FindAny != "" {
			ffiName := "ffi_" + s.FindAll
			wasmExport := s.FindAll
			if wasmExport == "" {
				wasmExport = s.FindAny
				ffiName = "ffi_" + s.FindAny
			}
			iterName := iterTypeName(s.FindAll)
			if s.FindAll == "" {
				iterName = iterTypeName(s.FindAny)
			}
			fmt.Fprintf(&out, `#[link(wasm_import_module = "%s")]
unsafe extern "C" {
    #[link_name = "%s"]
    fn %s(ptr: *const u8, len: i32, out: *mut i32, cap: i32, start: i32) -> i32;
}

`, cfg.ImportModule, wasmExport, ffiName)

			if s.FindAll != "" {
				fmt.Fprintf(&out, `pub struct %s<'a> {
    input: &'a [u8],
    start_pos: i32,
    buf: [[i32; 3]; %d],
    count: i32,
    idx: i32,
}

impl<'a> Iterator for %s<'a> {
    type Item = SetMatch;
    fn next(&mut self) -> Option<SetMatch> {
        loop {
            if self.idx < self.count {
                let e = self.buf[self.idx as usize];
                self.idx += 1;
                return Some(SetMatch { pattern_id: e[0] as usize, start: e[1] as usize, end: (e[1]+e[2]) as usize });
            }
            if self.start_pos < 0 { return None; }
            let n = unsafe { %s(self.input.as_ptr(), self.input.len() as i32, self.buf.as_mut_ptr() as *mut i32, %d, self.start_pos) };
            if n <= 0 { return None; }
            self.count = n;
            self.idx = 0;
            let last = self.buf[(n-1) as usize];
            self.start_pos = last[1] + if last[2] > 0 { last[2] } else { 1 };
        }
    }
}

pub fn %s(input: &[u8]) -> %s<'_> {
    %s { input, start_pos: 0, buf: [[0;3]; %d], count: 0, idx: 0 }
}

`, iterName, bs, iterName, ffiName, bs, s.FindAll, iterName, iterName, bs)
			}
			if s.FindAny != "" {
				anyFfiName := ffiName
				if s.FindAll != "" {
					anyFfiName = "ffi_" + s.FindAll
				}
				fmt.Fprintf(&out, `pub fn %s(input: &[u8]) -> Option<SetMatch> {
    let mut buf = [0i32; 3];
    let n = unsafe { %s(input.as_ptr(), input.len() as i32, buf.as_mut_ptr(), 1, 0) };
    if n <= 0 { return None; }
    Some(SetMatch { pattern_id: buf[0] as usize, start: buf[1] as usize, end: (buf[1]+buf[2]) as usize })
}

`, s.FindAny, anyFfiName)
			}
		}
		if s.Match != "" {
			ffiName := "ffi_" + s.Match
			fmt.Fprintf(&out, `#[link(wasm_import_module = "%s")]
unsafe extern "C" {
    #[link_name = "%s"]
    fn %s(ptr: *const u8, len: i32, out: *mut i32, cap: i32) -> i32;
}

/// Anchored set match: returns the first matching pattern with start=0, or None.
pub fn %s(input: &[u8]) -> Option<SetMatch> {
    let mut buf = [0i32; 2];
    let n = unsafe { %s(input.as_ptr(), input.len() as i32, buf.as_mut_ptr(), 1) };
    if n <= 0 { return None; }
    Some(SetMatch { pattern_id: buf[0] as usize, start: 0, end: buf[1] as usize })
}

`, cfg.ImportModule, s.Match, ffiName, s.Match, ffiName)
		}
	}
	if hasEmitNameMap(cfg) {
		out.WriteString("pub fn pattern_name(id: usize) -> &'static str {\n    match id {\n")
		for i, re := range cfg.Regexes {
			fmt.Fprintf(&out, "        %d => %q,\n", i, re.Name)
		}
		out.WriteString("        _ => \"\",\n    }\n}\n\n")
	}
	return out.String()
}

// genRustStubsInner generates the unindented inner content for single-pattern stubs
// (without the pub mod wrapper). Returns "" when there is nothing to emit.
func genRustStubsInner(entries []config.RegexEntry, importModule string) (string, error) {
	var bodyParts []string
	for _, re := range entries {
		body, err := genRustStubsForEntry(re, importModule)
		if err != nil {
			return "", err
		}
		if body != "" {
			bodyParts = append(bodyParts, body)
		}
	}
	if len(bodyParts) == 0 {
		return "", nil
	}
	return strings.TrimRight(strings.Join(bodyParts, ""), "\n") + "\n", nil
}

// wrapRustModule wraps inner (unindented) content in pub mod <moduleName> { }.
// Each non-empty line is indented by 4 spaces.
func wrapRustModule(inner, moduleName string) string {
	var out strings.Builder
	fmt.Fprintf(&out, "pub mod %s {\n", moduleName)
	for _, line := range strings.Split(strings.TrimRight(inner, "\n"), "\n") {
		if line == "" {
			out.WriteString("\n")
		} else {
			fmt.Fprintf(&out, "    %s\n", line)
		}
	}
	out.WriteString("}\n")
	return out.String()
}

// genRustStubFile is kept for backward compatibility with tests.
func genRustStubFile(entries []config.RegexEntry, importModule string) (string, error) {
	inner, err := genRustStubsInner(entries, importModule)
	if err != nil || inner == "" {
		return "", err
	}
	return "// Auto-generated by regexped. Do not edit.\n\n" + wrapRustModule(inner, importModule), nil
}

// genRustStubsForEntry generates the Rust stub content for a single entry.
func genRustStubsForEntry(re config.RegexEntry, importModule string) (string, error) {
	var out string
	written := false

	if re.MatchFunc != "" {
		out += genRustMatchStub(importModule, re.MatchFunc)
		written = true
	}
	if re.FindFunc != "" {
		out += genRustFindIterStub(importModule, re.FindFunc)
		written = true
	}
	if re.GroupsFunc != "" || re.NamedGroupsFunc != "" {
		numGroups, namedGroups, err := extractGroupInfo(re.Pattern)
		if err != nil {
			return "", err
		}
		exportName := re.GroupsExportName()
		if re.GroupsFunc != "" {
			out += genRustGroupsIterStub(importModule, re.GroupsFunc, exportName, true, numGroups)
			written = true
		}
		if re.NamedGroupsFunc != "" {
			declareFFI := re.GroupsFunc == ""
			out += genRustNamedGroupsIterStub(importModule, re.NamedGroupsFunc, exportName, declareFFI, numGroups, namedGroups)
			written = true
		}
	}

	if !written {
		return "", nil
	}
	return out, nil
}

// iterTypeName derives a unique Rust type name for an iterator from the function name.
// "find_github_token" → "FindGithubTokenIter"
func iterTypeName(funcName string) string {
	var b strings.Builder
	upper := true
	for _, c := range funcName {
		if c == '_' {
			upper = true
			continue
		}
		if upper {
			if c >= 'a' && c <= 'z' {
				c -= 'a' - 'A'
			}
			upper = false
		}
		b.WriteRune(c)
	}
	b.WriteString("Iter")
	return b.String()
}

// genRustMatchStub generates an anchored-match stub.
// The WASM export is named funcName; the internal FFI binding uses the ffi_ prefix
// to avoid a name collision with the public Rust wrapper.
func genRustMatchStub(importModule, funcName string) string {
	ffiName := "ffi_" + funcName
	return fmt.Sprintf(`#[link(wasm_import_module = "%s")]
unsafe extern "C" {
    #[link_name = "%s"]
    fn %s(ptr: *const u8, len: usize) -> i32;
}

/// Returns the end position of the match (exclusive), or None if no match.
/// The match is anchored: it starts at the beginning of input.
pub fn %s(input: &[u8]) -> Option<usize> {
    match unsafe { %s(input.as_ptr(), input.len()) } {
        n if n >= 0 => Some(n as usize),
        _ => None,
    }
}

`, importModule, funcName, ffiName, funcName, ffiName)
}

// genRustFindIterStub generates a find iterator.
// The WASM export is named funcName; ffi_ prefix avoids collision with the
// public constructor of the same name.
func genRustFindIterStub(importModule, funcName string) string {
	ffiName := "ffi_" + funcName
	iterName := iterTypeName(funcName)
	return fmt.Sprintf(`#[link(wasm_import_module = "%s")]
unsafe extern "C" {
    #[link_name = "%s"]
    fn %s(ptr: *const u8, len: usize) -> i64;
}

pub struct %s<'a> {
    input: &'a [u8],
    offset: usize,
}

impl<'a> Iterator for %s<'a> {
    type Item = (usize, usize);

    fn next(&mut self) -> Option<(usize, usize)> {
        if self.offset > self.input.len() {
            return None;
        }
        let remaining = &self.input[self.offset..];
        match unsafe { %s(remaining.as_ptr(), remaining.len()) } {
            -1 => None,
            n  => {
                let start = (n as u64 >> 32) as usize;
                let end   = (n as u32) as usize;
                let abs_start = self.offset + start;
                let abs_end   = self.offset + end;
                self.offset += if end > start { end } else { start + 1 };
                Some((abs_start, abs_end))
            }
        }
    }
}

/// Returns an iterator over all non-overlapping matches in input.
/// Each item is an absolute (start, end) byte range.
/// Use .next() to get only the first match.
pub fn %s(input: &[u8]) -> %s<'_> {
    %s { input, offset: 0 }
}

`, importModule, funcName, ffiName, iterName, iterName, ffiName, funcName, iterName, iterName)
}

// genRustGroupsIterStub generates a capture-groups iterator.
// exportName is the actual WASM export (= funcName unless named_groups_func
// shares the same WASM export, in which case exportName = groups_func value).
// declareFFI controls whether the extern "C" block is emitted; pass false when
// a sibling named-groups stub in the same file already declared it.
func genRustGroupsIterStub(importModule, funcName, exportName string, declareFFI bool, numGroups int) string {
	ffiName := "ffi_" + exportName
	slotCount := numGroups * 2

	var ffiDecl string
	if declareFFI {
		ffiDecl = fmt.Sprintf(`#[link(wasm_import_module = "%s")]
unsafe extern "C" {
    #[link_name = "%s"]
    fn %s(ptr: *const u8, len: usize, out: *mut i32) -> i32;
}

`, importModule, exportName, ffiName)
	}

	iterName := iterTypeName(funcName)
	return ffiDecl + fmt.Sprintf(`pub struct %s<'a> {
    input: &'a [u8],
    offset: usize,
}

impl<'a> Iterator for %s<'a> {
    type Item = Vec<Option<(usize, usize)>>;

    fn next(&mut self) -> Option<Vec<Option<(usize, usize)>>> {
        loop {
            if self.offset > self.input.len() {
                return None;
            }
            let remaining = &self.input[self.offset..];
            let mut slots = [-1i32; %d];
            if unsafe { %s(remaining.as_ptr(), remaining.len(), slots.as_mut_ptr()) } < 0 {
                if self.offset == self.input.len() {
                    return None;
                }
                self.offset += 1;
                continue;
            }
            let off = self.offset;
            let match_end = if slots[1] >= 0 { slots[1] as usize } else { 0 };
            self.offset += if match_end > 0 { match_end } else { 1 };
            let mut result = Vec::with_capacity(%d);
            for i in 0..%d {
                let start = slots[i * 2];
                let end   = slots[i * 2 + 1];
                result.push(if start < 0 { None } else { Some((start as usize + off, end as usize + off)) });
            }
            return Some(result);
        }
    }
}

/// Returns an iterator over all non-overlapping capture matches in input.
/// Group positions are absolute byte offsets. Index 0 is the full match.
/// Use .next() to get only the first match.
pub fn %s(input: &[u8]) -> %s<'_> {
    %s { input, offset: 0 }
}

`, iterName, iterName, slotCount, ffiName, numGroups, numGroups, funcName, iterName, iterName)
}

// genRustNamedGroupsIterStub generates a named-capture-groups iterator.
// exportName is the actual WASM export name.
// declareFFI controls whether the extern "C" block is emitted; pass false when
// a sibling groups stub in the same file already declared it.
func genRustNamedGroupsIterStub(importModule, funcName, exportName string, declareFFI bool, numGroups int, namedGroups map[string]int) string {
	ffiName := "ffi_" + exportName
	slotCount := numGroups * 2

	type entry struct {
		name  string
		index int
	}
	var entries []entry
	for name, idx := range namedGroups {
		entries = append(entries, entry{name, idx})
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].index < entries[j].index })

	var inserts strings.Builder
	for _, e := range entries {
		fmt.Fprintf(&inserts,
			"            if slots[%d] >= 0 { map.insert(\"%s\", (slots[%d] as usize + off, slots[%d] as usize + off)); }\n",
			e.index*2, e.name, e.index*2, e.index*2+1)
	}

	var ffiDecl string
	if declareFFI {
		ffiDecl = fmt.Sprintf(`#[link(wasm_import_module = "%s")]
unsafe extern "C" {
    #[link_name = "%s"]
    fn %s(ptr: *const u8, len: usize, out: *mut i32) -> i32;
}

`, importModule, exportName, ffiName)
	}

	iterName := iterTypeName(funcName)
	return ffiDecl + fmt.Sprintf(`pub struct %s<'a> {
    input: &'a [u8],
    offset: usize,
}

impl<'a> Iterator for %s<'a> {
    type Item = std::collections::HashMap<&'static str, (usize, usize)>;

    fn next(&mut self) -> Option<std::collections::HashMap<&'static str, (usize, usize)>> {
        loop {
            if self.offset > self.input.len() {
                return None;
            }
            let remaining = &self.input[self.offset..];
            let mut slots = [-1i32; %d];
            if unsafe { %s(remaining.as_ptr(), remaining.len(), slots.as_mut_ptr()) } < 0 {
                if self.offset == self.input.len() {
                    return None;
                }
                self.offset += 1;
                continue;
            }
            let off = self.offset;
            let match_end = if slots[1] >= 0 { slots[1] as usize } else { 0 };
            self.offset += if match_end > 0 { match_end } else { 1 };
            let mut map = std::collections::HashMap::new();
%s            return Some(map);
        }
    }
}

/// Returns an iterator over all non-overlapping named-capture matches in input.
/// Group positions are absolute byte offsets.
/// Use .next() to get only the first match.
pub fn %s(input: &[u8]) -> %s<'_> {
    %s { input, offset: 0 }
}

`, iterName, iterName, slotCount, ffiName, inserts.String(), funcName, iterName, iterName)
}
