package generate

import "fmt"

func genRustStubs(pattern, importModule, exportName, funcName string) string {
	return fmt.Sprintf(`// Auto-generated by regexped-wasm. Do not edit.
// Pattern: %s

#[link(wasm_import_module = "%s")]
unsafe extern "C" {
    /// Anchored match starting at ptr. Returns end position (0..len) or -1.
    fn %s(ptr: *const u8, len: usize) -> i32;
}

/// Returns the end position of the match (exclusive), or None if no match.
/// The match is anchored: it starts at the beginning of input.
pub fn %s(input: &[u8]) -> Option<usize> {
    match unsafe { %s(input.as_ptr(), input.len()) } {
        n if n >= 0 => Some(n as usize),
        _ => None,
    }
}
`, pattern, importModule, exportName, funcName, exportName)
}

func genRustFindStubs(pattern, importModule, exportName, funcName string) string {
	return fmt.Sprintf(`// Auto-generated by regexped-wasm. Do not edit.
// Pattern: %s

#[link(wasm_import_module = "%s")]
unsafe extern "C" {
    /// Non-anchored find. Returns packed (start << 32 | end) or -1 (as i64).
    fn %s(ptr: *const u8, len: usize) -> i64;
}

/// Returns (start, end) of the leftmost-longest match, or None if no match.
pub fn %s(input: &[u8]) -> Option<(usize, usize)> {
    match unsafe { %s(input.as_ptr(), input.len()) } {
        -1 => None,
        n  => Some(((n as u64 >> 32) as usize, (n as u32) as usize)),
    }
}
`, pattern, importModule, exportName, funcName, exportName)
}
