package generate

import (
	"fmt"
	"os"
	"strings"

	"github.com/qrdl/regexped/config"
)

// tsStub generates a TypeScript ES module stub file for all regexp entries in cfg.
// out is the full output path or "-" for stdout.
func tsStub(cfg config.BuildConfig, out string) error {
	content, err := genTSStubFile(cfg)
	if err != nil {
		return fmt.Errorf("generate TS stub: %w", err)
	}
	// See jsStub: the namespace applies on the stdout path too.
	content = applyNamespace(cfg, "ts", content)
	if out == "-" {
		_, err := os.Stdout.WriteString(content)
		return err
	}
	return writeStub(out, []byte(content))
}

// genTSStubFile generates the content of a TypeScript ES module stub that
// exports typed wrapper functions for every regexp entry in cfg.
// The caller is responsible for loading the WASM file and passing the bytes
// (or a WebAssembly.Module) to the exported init() function.
func genTSStubFile(cfg config.BuildConfig) (string, error) {
	// A config with no exports gets NO FILE, matching the other four
	// generators. It used to get a module of dead `_align`/`_grow`/`_stage`
	// helpers and nothing to call them.
	if !anyStubExport(cfg) {
		return "", nil
	}
	var sb strings.Builder
	sb.WriteString("// Auto-generated by regexped. Do not edit.\n\n")

	sb.WriteString("let _exp: WebAssembly.Exports;\n")
	sb.WriteString("let _mem: Uint8Array;\n")
	sb.WriteString("let _staticTop = 0; // first byte after the module's own table pages\n")
	sb.WriteString("let _bump = 0;      // next free byte; regions are carved from here up\n")
	// Only generators keep a refcount; a stub with none would declare it unused.
	if hasSuspendableExports(cfg) {
		sb.WriteString("let _live = 0;      // live iterator regions\n")
	}
	sb.WriteString("const _enc = new TextEncoder();\n")
	sb.WriteString("\n")

	// init() accepts a BufferSource (ArrayBuffer / Buffer / Uint8Array) or a
	// pre-compiled WebAssembly.Module — any value accepted by
	// WebAssembly.instantiate().  The caller chooses how to load the file:
	//
	//   Browser:            await init(await fetch('./merged.wasm').then(r => r.arrayBuffer()))
	//   Node.js:            await init(readFileSync('./merged.wasm'))
	//   Cloudflare Workers: import wasm from './merged.wasm'; await init(wasm)
	sb.WriteString("export async function init(wasm: BufferSource | WebAssembly.Module): Promise<void> {\n")
	// WebAssembly.instantiate resolves to an Instance when handed a Module, but
	// to {module, instance} when handed a BufferSource. The BufferSource cast
	// picks the latter overload for the type-checker, so the instanceof probe
	// (and the assertion on the result) is what keeps the Module path — the
	// Cloudflare Workers flow promised in the comment above — working at
	// runtime. Mirrors genJSStubFile.
	sb.WriteString("    const r = await WebAssembly.instantiate(wasm as BufferSource);\n")
	sb.WriteString("    const instance = (r instanceof WebAssembly.Instance ? r : r.instance) as WebAssembly.Instance;\n")
	sb.WriteString("    _exp = instance.exports;\n")
	sb.WriteString("    const _m = _exp.memory as WebAssembly.Memory;\n")
	sb.WriteString("    _staticTop = _m.buffer.byteLength; // first byte after DFA table pages\n")
	sb.WriteString("    _bump = _staticTop;\n")
	sb.WriteString("    _m.grow(2);                       // 1 page for input, 1 page for output/slots\n")
	sb.WriteString("    _mem = new Uint8Array(_m.buffer); // re-acquire after grow\n")
	sb.WriteString("}\n\n")

	// ── Regions ─────────────────────────────────────────────────────────────
	//
	// Standalone WASM cannot read the JS heap, so an input must be COPIED into
	// linear memory. Copying is not the hazard; SHARING one staging address is.
	// A generator stages its input, yields, and resumes — and anything the
	// caller ran in between had written its own input over the top, so the scan
	// continued across another string's bytes and reported offsets against it.
	// Silently: no exception, plausible output.
	//
	// The merged-mode targets never had this. Rust passes `input.as_ptr()` and
	// Go `unsafe.SliceData(input)`, so each live input already sits at its own
	// address and nothing relocates it. That — distinct, stable addresses — is
	// what makes them safe, not the absence of a copy. So this reproduces it:
	// every call carves its OWN region and keeps it, which gives TS the same
	// contract with a copy still in the middle.
	//
	// A bump allocator with a live-iterator refcount is enough. There is no
	// free list because there is nothing to reclaim piecemeal: when the last
	// iterator finishes the whole arena resets, which for ordinary code is
	// between every loop.
	sb.WriteString("function _align(x: number): number { return (x + 7) & ~7; }\n\n")
	sb.WriteString("function _grow(top: number): void {\n")
	sb.WriteString("    if (top > _mem.buffer.byteLength) {\n")
	sb.WriteString("        (_exp.memory as WebAssembly.Memory).grow(Math.ceil((top - _mem.buffer.byteLength) / 65536));\n")
	sb.WriteString("        _mem = new Uint8Array((_exp.memory as WebAssembly.Memory).buffer); // grow DETACHES the old one\n")
	sb.WriteString("    }\n")
	sb.WriteString("}\n\n")
	sb.WriteString("function _inCap(input: string | Uint8Array): number {\n")
	sb.WriteString("    // Worst-case UTF-8 expansion of a JS string is 3 bytes per UTF-16 code\n")
	sb.WriteString("    // unit (an astral char is 2 units and encodes to 4, so 3x still bounds\n")
	sb.WriteString("    // it), so encodeInto cannot truncate inside the reservation.\n")
	sb.WriteString("    return typeof input === 'string' ? input.length * 3 : input.length;\n")
	sb.WriteString("}\n\n")
	sb.WriteString("function _write(input: string | Uint8Array, at: number): number {\n")
	sb.WriteString("    // encodeInto writes straight into WASM memory, avoiding both the\n")
	sb.WriteString("    // intermediate array TextEncoder.encode allocates and the second copy\n")
	sb.WriteString("    // _mem.set would then make.\n")
	// lib.dom.d.ts declares TextEncoderEncodeIntoResult.written as optional, so
	// strict-mode consumers need the non-null assertion; it is always present at
	// runtime per the Encoding spec.
	sb.WriteString("    if (typeof input === 'string') return _enc.encodeInto(input, _mem.subarray(at)).written!;\n")
	sb.WriteString("    _mem.set(input, at);\n")
	sb.WriteString("    return input.length;\n")
	sb.WriteString("}\n\n")
	// Emitted only when something uses them: a stub is a file the caller
	// compiles, and TypeScript under --noUnusedLocals rejects a declared
	// helper nothing calls. A match-only config has no generator, and a
	// generator-only config has no one-shot call.
	if hasOneShotExports(cfg) {
		sb.WriteString("function _stage(input: string | Uint8Array, outBytes: number): [number, number, number] {\n")
		sb.WriteString("    // For calls that CANNOT suspend. They run to completion before anything\n")
		sb.WriteString("    // else can allocate, so they may reuse the space above the bump without\n")
		sb.WriteString("    // reserving it — which is what stops a one-shot call inside a loop over a\n")
		sb.WriteString("    // live iterator from allocating a region per iteration.\n")
		sb.WriteString("    const at = _bump, out = _align(at + _inCap(input));\n")
		sb.WriteString("    _grow(out + (outBytes > 0 ? outBytes : 65536));\n")
		sb.WriteString("    return [at, out, _write(input, at)];\n")
		sb.WriteString("}\n\n")
	}
	if hasSuspendableExports(cfg) {
		sb.WriteString("function _open(input: string | Uint8Array, outBytes: number): [number, number, number] {\n")
		sb.WriteString("    // For generators, which DO suspend. The region is reserved for the\n")
		sb.WriteString("    // iterator's whole lifetime, so no other call can land on its input or\n")
		sb.WriteString("    // its scratch. Release with _close() from a finally.\n")
		sb.WriteString("    const at = _bump, out = _align(at + _inCap(input));\n")
		sb.WriteString("    _bump = out + (outBytes > 0 ? outBytes : 65536);\n")
		sb.WriteString("    _grow(_bump);\n")
		sb.WriteString("    _live++;\n")
		sb.WriteString("    return [at, out, _write(input, at)];\n")
		sb.WriteString("}\n\n")
		sb.WriteString("function _close(): void { if (--_live === 0) _bump = _staticTop; }\n\n")
		// Generic over the view type rather than typed as a union: _att must hand
		// back the SAME kind of array it was given, or every indexed read after a
		// re-attach would widen to Int32Array | Uint32Array.
		sb.WriteString("function _att<T extends Int32Array | Uint32Array>(\n")
		sb.WriteString("        view: T, Ctor: new (buf: ArrayBufferLike, at: number, len: number) => T,\n")
		sb.WriteString("        at: number, len: number): T {\n")
		sb.WriteString("    // A view survives its own iterator's lifetime EXCEPT across a grow, which\n")
		sb.WriteString("    // detaches every view in the module no matter whose region it points at —\n")
		sb.WriteString("    // the one hazard the merged-mode targets have no analogue for, since they\n")
		sb.WriteString("    // hold native pointers rather than views. A detached view reports\n")
		sb.WriteString("    // length 0 and reads as undefined SILENTLY, so re-attach on that. The\n")
		sb.WriteString("    // offset is still ours, so rebuilding at the same place is correct.\n")
		sb.WriteString("    return view.length === 0 ? new Ctor(_mem.buffer, at, len) : view;\n")
		sb.WriteString("}\n\n")

	}
	for _, re := range cfg.Regexps {
		if re.MatchFunc != "" {
			sb.WriteString(genTSMatchFunc(re.MatchFunc))
		}
		if re.FindFunc != "" {
			sb.WriteString(genTSFindFunc(re.FindFunc))
		}
		if re.GroupsFunc != "" {
			numGroups, namedGroups, err := extractGroupInfo(re.Pattern)
			if err != nil {
				return "", fmt.Errorf("pattern %q: %w", re.Pattern, err)
			}
			sb.WriteString(genTSGroupsFunc(re.GroupsFunc, numGroups))
			sb.WriteString(genTSGroupIndices(re.GroupsFunc, numGroups, namedGroups))
		}
	}

	sb.WriteString(genTSSetSection(cfg))
	return sb.String(), nil
}

// genTSSetSection generates TypeScript set wrappers.
func genTSSetSection(cfg config.BuildConfig) string {
	if !hasSetExports(cfg) {
		return ""
	}
	var out strings.Builder
	out.WriteString("\n// ---- set composition wrappers ----\n")
	out.WriteString("//\n")
	out.WriteString("// Calling other stub functions while an iterator is suspended is SAFE: each\n")
	out.WriteString("// live iterator owns its input and scratch region for its whole lifetime,\n")
	out.WriteString("// the same guarantee the Rust and Go stubs get from passing a host pointer.\n")
	out.WriteString("\n")
	out.WriteString("export interface SetMatch { patternId: number; start: number; end: number; }\n")
	for _, s := range cfg.Sets {
		n := patternsInSet(s, cfg)
		konst := camelSet(s.Name) + "PatternCount"
		idN := idSpaceSize(s, cfg)
		idKonst := camelSet(s.Name) + "IdSpace"
		wide := wideAllForm(s, cfg)
		// Standalone layout: tuples (12 x pattern count), gate array
		// (4 x ID SPACE), >64-pattern bitmap (ceil(idSpace/8)). The two counts
		// differ for a named-subset set.
		reserve := 12*n + 4*idN + bitmapBytes(s, cfg)
		gateBase := fmt.Sprintf("_outBase + 12*%s", konst)
		bitmapBase := fmt.Sprintf("_outBase + 12*%s + 4*%s", konst, idKonst)

		// Argument ORDER comes from the R12 descriptor, not from the templates
		// below — the one place the compiler's ABI is written down
		//. Only the SPELLING of each parameter is decided
		// here; `args` names the list for one capability.
		caps := setCapabilities(s, cfg)
		spell := jsArgSpelling{
			inPtr: "_inBase", inLen: "len", from: "from",
			gate: gateBase, bitmap: "bitmapBase",
			tuple: "_outBase", outCap: konst, cursor: "cursor",
		}
		args := func(kind string) string { return spellJSArgs(capByKind(caps, kind), spell) }

		fmt.Fprintf(&out, "// Number of patterns in set %q. Sizes the match buffer: the find generator\n// can receive at most this many matches at one position.\nexport const %s: number = %d;\n\n", s.Name, konst, n)
		fmt.Fprintf(&out, "// One past the largest pattern id set %q can report. Pattern ids are global\n// indices into regexps:, so a set holding a few late-declared patterns has a\n// small count and a large id space. Everything indexed BY an id \u2014 the gate\n// array, the _all bitmask \u2014 is sized from this.\nexport const %s: number = %d;\n\n", s.Name, idKonst, idN)

		if s.BatchFind() {
			fmt.Fprintf(&out, "// Largest batchSize %s accepts for set %q. It is the cursor layout's\n// limit, not a policy: one i64 carries the resume position in its top 32\n// bits and splits the low 32 between the intra-position index and the count.\n// It never binds in practice — this many tuples is a multi-megabyte buffer.\nexport const %s: number = %d;\n\n",
				s.Find, s.Name, camelSet(s.Name)+"BatchMaxSize", cursorMaxCount(s, cfg))
		}

		if s.MatchAny != "" {
			fmt.Fprintf(&out, `export function %s(input: string | Uint8Array): number | null {
    const [_inBase, _outBase, len] = _stage(input, 0);
    const id = (_exp['%s'] as Function)(%s) as number;
    // Tested EXACTLY, not as "negative": -1 is a real answer (nothing matched)
    // and the sentinel means the engine gave up. Folding the two — which this
    // did — turns "unknown" into a confident null.
    if (id === %d) throw new Error("%s");
    return id < 0 ? null : id;
}
`, s.MatchAny, s.MatchAny, args("match_any"), btOverflow, btOverflowMsg(s.MatchAny))
		}
		if s.MatchAll != "" {
			if wide {
				fmt.Fprintf(&out, `export function %s(input: string | Uint8Array): number[] {
    const [_inBase, _outBase, len] = _stage(input, %d);
    const bitmapBase = %s;
    new Uint8Array(_mem.buffer, bitmapBase, (%s+7)>>3).fill(0);
    // The wide form returns a count; the bitmap carries the answer. The count
    // is read only for the sentinel, which means unknown, not "matched none".
    const n = (_exp['%s'] as Function)(%s) as number;
    if (n === %d) throw new Error("%s");
    const bits = new Uint8Array(_mem.buffer, bitmapBase, (%s+7)>>3);
    const out: number[] = [];
    for (let k = 0; k < %s; k++) if (bits[k>>3] & (1 << (k & 7))) out.push(k);
    return out;
}
`, s.MatchAll, reserve, bitmapBase, idKonst, s.MatchAll, args("match_all"), btOverflow, btOverflowMsg(s.MatchAll), idKonst, idKonst)
			} else {
				// No overflow check in the narrow form, and none is possible: the
				// i64 return IS the bitmask, so every value is a legal answer —
				// a -2 test here would misfire whenever pattern 63 matches. The
				// narrow form is only chosen when no member can overflow.
				fmt.Fprintf(&out, `export function %s(input: string | Uint8Array): number[] {
    const [_inBase, _outBase, len] = _stage(input, 0);
    // The export returns an i64, which surfaces as a BigInt; it is decomposed
    // here and never reaches the caller.
    const mask = (_exp['%s'] as Function)(%s) as bigint;
    // NO overflow sentinel here: the narrow form's return IS the bitmask, so
    // every 64-bit value is a legal answer. -2n means ids 1..63 matched and id
    // 0 did not, which a sentinel test would report as an engine failure. The
    // real sentinel cannot reach this form — a Backtracking member forces the
    // wide one.
    const out: number[] = [];
    for (let k = 0; k < %s; k++) if ((mask >> BigInt(k)) & 1n) out.push(k);
    return out;
}
`, s.MatchAll, s.MatchAll, args("match_all"), idKonst)
			}
		}
		if s.ScanAny != "" {
			fmt.Fprintf(&out, `export function %s(input: string | Uint8Array, from: number = 0): number | null {
    const [_inBase, _outBase, len] = _stage(input, 0);
    const id = (_exp['%s'] as Function)(%s) as number;
    // Tested against the sentinel exactly, not "< 0": -1 is a legitimate
    // no-match, while -2 means the result is unknown.
    if (id === %d) throw new Error("%s");
    return id < 0 ? null : id;
}
`, s.ScanAny, s.ScanAny, args("scan_any"), btOverflow, btOverflowMsg(s.ScanAny))
		}
		if s.ScanAll != "" {
			if wide {
				fmt.Fprintf(&out, `export function %s(input: string | Uint8Array, from: number = 0): number[] {
    const [_inBase, _outBase, len] = _stage(input, %d);
    const bitmapBase = %s;
    new Uint8Array(_mem.buffer, bitmapBase, (%s+7)>>3).fill(0);
    // The wide form returns a count; the bitmap carries the answer. The count
    // is read only for the sentinel, which means unknown, not "matched none".
    const n = (_exp['%s'] as Function)(%s) as number;
    if (n === %d) throw new Error("%s");
    const bits = new Uint8Array(_mem.buffer, bitmapBase, (%s+7)>>3);
    const out: number[] = [];
    for (let k = 0; k < %s; k++) if (bits[k>>3] & (1 << (k & 7))) out.push(k);
    return out;
}
`, s.ScanAll, reserve, bitmapBase, idKonst, s.ScanAll, args("scan_all"), btOverflow, btOverflowMsg(s.ScanAll), idKonst, idKonst)
			} else {
				// Narrow form: see match_all above — the i64 return IS the
				// bitmask, so there is no value left to spend on a sentinel.
				fmt.Fprintf(&out, `export function %s(input: string | Uint8Array, from: number = 0): number[] {
    const [_inBase, _outBase, len] = _stage(input, 0);
    const mask = (_exp['%s'] as Function)(%s) as bigint;
    // NO overflow sentinel here: the narrow form's return IS the bitmask, so
    // every 64-bit value is a legal answer. -2n means ids 1..63 matched and id
    // 0 did not, which a sentinel test would report as an engine failure. The
    // real sentinel cannot reach this form — a Backtracking member forces the
    // wide one.
    const out: number[] = [];
    for (let k = 0; k < %s; k++) if ((mask >> BigInt(k)) & 1n) out.push(k);
    return out;
}
`, s.ScanAll, s.ScanAll, args("scan_all"), idKonst)
			}
		}
		if s.Find != "" {
			// Every set with `find` owns a gate array, overlapping included
			//, so this is unconditional.
			gateSetup := fmt.Sprintf(`    const gateBase = %s;
    new Uint32Array(_mem.buffer, gateBase, %s).fill(0);
`, gateBase, idKonst)
			gateArg := "gateBase, "
			if !s.BatchFind() {
				// Without the hint there is no batchSize parameter at all, so
				// TypeScript rejects find(input, 0, 64) at build time and no
				// runtime check is needed.
				fmt.Fprintf(&out, `export function* %s(input: string | Uint8Array, offset: number = 0): Generator<SetMatch> {
    // The region is this iterator's own for its whole lifetime, so another
    // stub call cannot land on its input, its tuple buffer or its gates.
    const [_inBase, _outBase, len] = _open(input, %d);
    try {
%s    let pos = offset;
    // Hoisted rather than rebuilt per position, which allocated one typed
    // array per matching position. _att re-attaches it if an interleaved
    // call grew memory while this generator was suspended.
    let buf = new Int32Array(_mem.buffer, _outBase, 3*%s);
    while (true) {
        const n = (_exp['%s'] as Function)(%s) as number;
        // Before the "scan finished" test: -2 is the engine abandoning the
        // search, so ending the generator here would report success.
        if (n === %d) throw new Error("%s");
        if (n <= 0) break;
        buf = _att(buf, Int32Array, _outBase, 3*%s);
        // Every tuple in one call shares a start; resume one past it.
        const next = buf[1] + 1;
        for (let i = 0; i < n; i++) {
            // Re-checked each step: the yield below hands control back, and
            // whatever runs there may grow memory and detach this view.
            buf = _att(buf, Int32Array, _outBase, 3*%s);
            yield { patternId: buf[i*3], start: buf[i*3+1], end: buf[i*3+2] };
        }
        pos = next;
    }
    } finally { _close(); }
}
`, s.Find, reserve, gateSetup, konst, s.Find,
					spellJSArgs(capByKind(caps, "find"), jsArgSpelling{
						inPtr: "_inBase", inLen: "len", from: "pos",
						gate: gateBase, tuple: "_outBase", outCap: konst,
					}),
					btOverflow, btOverflowMsg(s.Find), konst, konst)
			} else {
				// The BATCH entry's argument order stays spelled out here:
				// setCapabilities describes the five DECLARED capabilities,
				// and batching is a hint rather than one, so it has no
				// descriptor entry to derive from. Its
				// signature is pinned instead by
				// compile/set_emit.go's setTypeBatchGated and the goldens.
				batchGateSetup := fmt.Sprintf(`    const gateBase = _outBase + 12*batchSize;
    new Uint32Array(_mem.buffer, gateBase, %s).fill(0);
`, idKonst)
				// The overlapping answer cache. An OVERLAPPING drive reports
				// every start position, so a pattern whose automaton never
				// dies is quadratic: each position walks to the end of the
				// input. Handing the engine a cache lets it sweep once,
				// backwards, and serve every later call by copying out of it.
				//
				// Offered only for `overlapping: true`, because that is the
				// only policy whose drive the sweep can answer. The engine
				// may still decline — the sweep refuses shapes it cannot
				// reproduce exactly — and declining costs nothing but speed.
				//
				// The gate array and the >64-pattern bitmap sit between the
				// tuple buffer and the cache, and the bitmap's width is
				// ceil(ID_SPACE/8) — not a multiple of 4. The cache header is
				// read through a Uint32Array, and a typed-array view whose
				// byte offset is not a multiple of its element size THROWS, so
				// the gap is rounded up to the same 8 _align uses.
				batchGateRegion := 4*idN + bitmapBytes(s, cfg)
				cachePre, cacheReserve, cachePost, cacheArgs := "", "", "", "0, 0"
				if s.Overlapping {
					batchGateRegion = (batchGateRegion + 7) &^ 7
					cachePre = fmt.Sprintf(`    // Twelve bytes per tuple, and the worst case really is one tuple per
    // pattern per start: a pattern that never dies matches from nearly
    // every position, which is the case this exists for. Past the ceiling
    // the engine is offered nothing and walks position by position, which
    // is what it did before this existed.
    const cacheNeeded = %d + (_inCap(input) + 1) * %s * 12;
    const cacheBytes = cacheNeeded <= %d ? cacheNeeded : 0;
`, config.SetOverlapCacheHeaderBytes, konst, config.SetOverlapCacheMaxBytes)
					cacheReserve = " + cacheBytes"
					cachePost = fmt.Sprintf(`    const cacheBase = cacheBytes > 0 ? gateBase + %d : 0;
    if (cacheBase !== 0) new Uint32Array(_mem.buffer, cacheBase, %d).fill(0);
`, batchGateRegion, config.SetOverlapCacheHeaderBytes/4)
					cacheArgs = "cacheBase, cacheBytes"
				}
				fmt.Fprintf(&out, `// batchSize is how many tuples one WASM call may fill: 1 is a call per
// matching position, larger values amortise the host crossing over a
// bufferful. The matches and their order are identical either way — the only
// difference is how much work you have paid for if you stop early. Clamped
// into [1, %s].
export function* %s(input: string | Uint8Array, offset: number = 0, batchSize: number = %d): Generator<SetMatch> {
    batchSize = Math.min(Math.max(batchSize | 0, 1), %s);
%s    // This iterator's own region, held until it finishes — see _open.
    const [_inBase, _outBase, len] = _open(input, 12*batchSize + %d%s);
    try {
%s%s    let cursor = BigInt(offset) << 32n;
    // Hoisted for the same reason the per-position shape hoists its view, and
    // re-attached by _att when an interleaved call grows memory.
    let buf = new Int32Array(_mem.buffer, _outBase, 3*batchSize);
    while (true) {
        const packed = (_exp['%s'] as Function)(_inBase, len, cursor, %s_outBase, batchSize, %s) as bigint;
        // The cursor is opaque: hand it back unchanged. Only its top 32 bits
        // are public — all ones means the scan is finished, and that arrives
        // on the same call as the last matches.
        const n = Number(packed & %dn);
        // Overflow travels in the resume-position word, beside "done": the
        // packed cursor has no spare value of its own, and a done cursor
        // already has bit 63 set. It must be read before the done test —
        // it means the scan's result is unknown, not that it finished.
        if ((BigInt.asUintN(64, packed) >> 32n) === 0x%Xn) throw new Error("%s");
        const done = (BigInt.asUintN(64, packed) >> 32n) === 0xFFFFFFFFn;
        for (let i = 0; i < n; i++) {
            // Re-checked each step: the yield hands control back, and whatever
            // runs there may grow memory and detach this view.
            buf = _att(buf, Int32Array, _outBase, 3*batchSize);
            yield { patternId: buf[i*3], start: buf[i*3+1], end: buf[i*3+2] };
        }
        // A call reports at least one match unless the scan is over.
        if (done || n === 0) break;
        cursor = packed;
    }
    } finally { _close(); }
}
`, camelSet(s.Name)+"BatchMaxSize", s.Find, defaultBatchCap(s, cfg),
					camelSet(s.Name)+"BatchMaxSize", cachePre, batchGateRegion, cacheReserve,
					batchGateSetup, cachePost,
					config.SetBatchExportName(s.Find), gateArg, cacheArgs, cursorCountMask(s, cfg),
					config.SetCursorOverflowPos, btOverflowMsg(s.Find))
			}
		}
		out.WriteString("\n")
	}
	if hasEmitNameMap(cfg) {
		out.WriteString("const _patternNames: string[] = [")
		for i, re := range cfg.Regexps {
			if i > 0 {
				out.WriteString(", ")
			}
			fmt.Fprintf(&out, "%q", re.Name)
		}
		out.WriteString("];\nexport function patternName(id: number): string { return _patternNames[id] ?? ''; }\n")
	}
	return out.String()
}

func genTSMatchFunc(funcName string) string {
	return fmt.Sprintf(`// %s — anchored match; returns the end position, or null if no match.
//
// null rather than a [pos, ok] tuple: that shape is Go's comma-ok written in
// TypeScript, and "a value or nothing" is null here — which is also what
// match_any in this same file returns.
export function %s(input: string | Uint8Array): number | null {
    const [_inBase, _outBase, len] = _stage(input, 0);
    const r = (_exp['%s'] as CallableFunction)(_inBase, len) as number;
    if (r === %d) throw new Error("%s");
    return r < 0 ? null : r;
}

`, funcName, funcName, funcName, btOverflow, btOverflowMsg(funcName))
}

// genTSFindFunc generates a TS generator for non-anchored find.
// Yields [start, end] absolute byte positions for each non-overlapping match.
//
// Prefers the batch export (funcName+"_batch", requested via the
// "batch-find" hint) when the loaded WASM provides one — draining
// lm2BatchCap matches per host call instead of one — and
// falls back to the standard one-call-per-match loop otherwise. Ported from
// genJSFindFunc (generate/js_stub.go) — see its doc comment for the full
// rationale; TS uses the same `_exp['<name>']` dynamic lookup, so the
// feature-detect carries over unchanged.
func genTSFindFunc(funcName string) string {
	return fmt.Sprintf(`// %[1]s — yields [start, end] for each non-overlapping match.
export function* %[1]s(input: string | Uint8Array, offset: number = 0): Generator<[number, number]> {
    const _batched = typeof _exp['%[1]s_batch'] === 'function';
    // One region for whichever path runs, held for this iterator's lifetime so
    // an interleaved stub call cannot overwrite the staged input mid-scan.
    const [_inBase, _outBase, len] = _open(input, _batched ? %[2]d * 8 : 0);
    try {
    if (_batched) {
        let outBuf = new Uint32Array(_mem.buffer, _outBase, %[2]d * 2);
        let startPos = offset;
        let prevEnd = -1;
        while (true) {
            const n = (_exp['%[1]s_batch'] as CallableFunction)(_inBase, len, _outBase, %[2]d, startPos) as number;
            if (n === %[3]d) throw new Error("%[4]s");
            if (n <= 0) break;
            for (let i = 0; i < n; i++) {
                // Re-attached each step: the yield below hands control back,
                // and a grow there detaches every view in the module.
                outBuf = _att(outBuf, Uint32Array, _outBase, %[2]d * 2);
                const s = outBuf[i * 2], e = outBuf[i * 2 + 1];
                // Go's FindAllIndex rule: suppress an EMPTY match beginning
                // exactly where the previous reported match ended.
                if (s === e && s === prevEnd) continue;
                prevEnd = e;
                yield [s, e];
            }
            if (n < %[2]d) break;
            outBuf = _att(outBuf, Uint32Array, _outBase, %[2]d * 2);
            const lastStart = outBuf[(n - 1) * 2], lastEnd = outBuf[(n - 1) * 2 + 1];
            startPos = lastEnd > lastStart ? lastEnd : lastStart + 1;
        }
        return;
    }
    let off = offset;
    let prevEnd2 = -1;
    while (off <= len) {
        // Whole input plus a start position: offset bounds where the search
        // begins, it does not truncate what the engine sees behind it.
        const r = (_exp['%[1]s'] as CallableFunction)(_inBase, len, off) as bigint;
        if (r === %[3]dn) throw new Error("%[4]s");
        if (r < 0n) break;
        const absStart = Number(r >> 32n);
        const absEnd   = Number(r & 0xFFFFFFFFn);
        const relStart = absStart - off, relEnd = absEnd - off;
        // See the batch path: Go suppresses an empty match adjacent to the
        // previous one. The advance below is unchanged.
        if (!(absStart === absEnd && absStart === prevEnd2)) {
            prevEnd2 = absEnd;
            yield [absStart, absEnd];
        }
        off += relEnd > relStart ? relEnd : relStart + 1;
    }
    } finally { _close(); }
}

`, funcName, lm2BatchCap, btOverflow, btOverflowMsg(funcName))
}

// genTSGroupsFunc generates a TS generator for capture groups.
// Yields an array per match, index 0 = full match, null for unmatched groups.
//
// Prefers the batch export (funcName+"_batch", requested via the
// "batch-find" hint) when the loaded WASM provides one, same as
// genTSFindFunc. Ported from genJSGroupsFunc
// (generate/js_stub.go) — see compile/compile.go's buildBatchGroupsWrapperBody
// for the record layout: [start, end, group0_start, group0_end, ...].
func genTSGroupsFunc(funcName string, numGroups int) string {
	slotCount := numGroups * 2
	recSize := 2 + slotCount // ints per batch record
	recBytes := recSize * 4  // bytes per batch record
	return fmt.Sprintf(`// %[1]s — yields capture group arrays per match.
// Each element is [start, end] (absolute) or null for unmatched groups.
// Index 0 is the full match.
export function* %[1]s(input: string | Uint8Array, offset: number = 0): Generator<Array<[number, number] | null>> {
    const _batched = typeof _exp['%[1]s_batch'] === 'function';
    // One region for whichever path runs, held for this iterator's lifetime so
    // an interleaved stub call cannot overwrite the staged input mid-scan.
    const [_inBase, _outBase, len] = _open(input, _batched ? %[2]d * %[4]d : 0);
    try {
    if (_batched) {
        let outBuf = new Int32Array(_mem.buffer, _outBase, %[2]d * %[3]d);
        let startPos = offset;
        // Kept ACROSS calls, exactly as the find batch loop does. The in-WASM
        // wrapper suppresses empty-adjacent matches only within one call, so a
        // batch that fills ending on a non-empty match at p resumes at p and
        // would report an empty match at p that Go suppresses.
        let prevEnd = -1;
        while (true) {
            const n = (_exp['%[1]s_batch'] as CallableFunction)(_inBase, len, _outBase, %[2]d, startPos) as number;
            if (n === %[7]d) throw new Error("%[8]s");
            if (n <= 0) break;
            for (let i = 0; i < n; i++) {
                // Re-attached each step: the yield below hands control back,
                // and a grow there detaches every view in the module.
                outBuf = _att(outBuf, Int32Array, _outBase, %[2]d * %[3]d);
                const base = i * %[3]d;
                const ms = outBuf[base], me = outBuf[base + 1];
                if (ms === me && ms === prevEnd) continue;
                prevEnd = me;
                const result: Array<[number, number] | null> = [];
                for (let g = 0; g < %[5]d; g++) {
                    const s = outBuf[base + 2 + g * 2], e = outBuf[base + 2 + g * 2 + 1];
                    result.push(s < 0 ? null : [s, e]);
                }
                yield result;
            }
            if (n < %[2]d) break;
            outBuf = _att(outBuf, Int32Array, _outBase, %[2]d * %[3]d);
            const lastBase = (n - 1) * %[3]d;
            const lastStart = outBuf[lastBase], lastEnd = outBuf[lastBase + 1];
            startPos = lastEnd > lastStart ? lastEnd : lastStart + 1;
        }
        return;
    }
    // Hoisted out of the loop rather than rebuilt per match, and re-attached
    // by _att when an interleaved call grew memory while suspended.
    let slots = new Int32Array(_mem.buffer, _outBase, %[6]d);
    let off = offset;
    let prevEnd = -1;
    while (off <= len) {
        slots = _att(slots, Int32Array, _outBase, %[6]d);
        slots.fill(-1);
        const r = (_exp['%[1]s'] as CallableFunction)(_inBase, len, _outBase, off) as number;
        if (r === %[7]d) throw new Error("%[8]s");
        if (r < 0) {
            // Terminal, not "try the next position": the groups
            // export has SCAN-FROM semantics in both wrapper arms, so a
            // negative result means there is no match at or after off. The
            // advance-by-one retry this replaced re-scanned the tail once per
            // remaining byte.
            break;
        }
        const matchEnd = slots[1] >= 0 ? slots[1] : slots[0];
        const result: Array<[number, number] | null> = [];
        for (let i = 0; i < %[5]d; i++) {
            const s = slots[i * 2], e = slots[i * 2 + 1];
            result.push(s < 0 ? null : [s, e]); // absolute already
        }
        const absStart = slots[0], absEnd = matchEnd;
        off = absEnd > absStart ? absEnd : absStart + 1;
        // Go's FindAllSubmatchIndex rule: suppress an EMPTY match beginning
        // exactly where the previous reported match ended. The advance above
        // is unchanged.
        if (absStart === absEnd && absStart === prevEnd) continue;
        prevEnd = absEnd;
        yield result;
    }
    } finally { _close(); }
}

`, funcName, lm2BatchCap, recSize, recBytes, numGroups, slotCount, btOverflow, btOverflowMsg(funcName))
}

// genTSGroupIndices emits the name→index object for a groups function.
// Replaces the retired `named_groups_func`. Same shape as the
// JS generator's, plus `as const` so the values carry literal types and
// indexing the yielded array with one is checked.
func genTSGroupIndices(funcName string, numGroups int, namedGroups map[string]int) string {
	if len(namedGroups) == 0 {
		return ""
	}
	names := groupNameSlots(numGroups, namedGroups)

	var out strings.Builder
	fmt.Fprintf(&out, `// Index of each NAMED capture group of %s. Index 0 is the whole match;
// unnamed groups are absent and are addressed by number. Object.keys() gives
// you the names, and the yielded array's length is always %d whether or not a
// group participated.
export const %s = {
`, funcName, numGroups, derivedConstName(funcName, "indices"))
	for idx, name := range names {
		if name == "" {
			continue
		}
		// QUOTED. Go's regexp/syntax accepts digit-leading group names —
		// `(?P<1a>x)` parses — and a bare `1a:` key is a SyntaxError that
		// takes the whole generated module down with it. %q is valid for
		// every key, keeps Object.keys() behaviour, and leaves TS's `as const`
		// literal types intact.
		fmt.Fprintf(&out, "    %q: %d,\n", name, idx)
	}
	out.WriteString("} as const;\n\n")
	return out.String()
}
