package generate

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/qrdl/regexped/config"
)

// tsStub generates a TypeScript ES module stub file for all regex entries in cfg.
// out is the full output path or "-" for stdout.
func tsStub(cfg config.BuildConfig, out string) error {
	content, err := genTSStubFile(cfg)
	if err != nil {
		return fmt.Errorf("generate TS stub: %w", err)
	}
	if out == "-" {
		_, err := os.Stdout.WriteString(content)
		return err
	}
	return writeStub(out, []byte(content))
}

// genTSStubFile generates the content of a TypeScript ES module stub that
// exports typed wrapper functions for every regex entry in cfg.
// The caller is responsible for loading the WASM file and passing the bytes
// (or a WebAssembly.Module) to the exported init() function.
func genTSStubFile(cfg config.BuildConfig) (string, error) {
	var sb strings.Builder
	sb.WriteString("// Auto-generated by regexped. Do not edit.\n\n")

	sb.WriteString("let _exp: WebAssembly.Exports;\n")
	sb.WriteString("let _mem: Uint8Array;\n")
	sb.WriteString("let _inBase = 0;  // byte offset where input is written (after DFA table pages)\n")
	sb.WriteString("let _outBase = 0; // byte offset for output buffers and capture slots\n")
	sb.WriteString("const _enc = new TextEncoder();\n")
	sb.WriteString("\n")

	// init() accepts a BufferSource (ArrayBuffer / Buffer / Uint8Array) or a
	// pre-compiled WebAssembly.Module — any value accepted by
	// WebAssembly.instantiate().  The caller chooses how to load the file:
	//
	//   Browser:            await init(await fetch('./merged.wasm').then(r => r.arrayBuffer()))
	//   Node.js:            await init(readFileSync('./merged.wasm'))
	//   Cloudflare Workers: import wasm from './merged.wasm'; await init(wasm)
	sb.WriteString("export async function init(wasm: BufferSource | WebAssembly.Module): Promise<void> {\n")
	sb.WriteString("    const { instance } = await WebAssembly.instantiate(wasm as BufferSource);\n")
	sb.WriteString("    _exp = instance.exports;\n")
	sb.WriteString("    const _m = _exp.memory as WebAssembly.Memory;\n")
	sb.WriteString("    _inBase = _m.buffer.byteLength; // first byte after DFA table pages\n")
	sb.WriteString("    _m.grow(2);                     // 1 page for input, 1 page for output/slots\n")
	sb.WriteString("    _outBase = _inBase + 65536;\n")
	sb.WriteString("    _mem = new Uint8Array(_m.buffer); // re-acquire after grow\n")
	sb.WriteString("}\n\n")

	sb.WriteString("function _b(input: string | Uint8Array): Uint8Array {\n")
	sb.WriteString("    return typeof input === 'string' ? _enc.encode(input) : input;\n")
	sb.WriteString("}\n\n")

	for _, re := range cfg.Regexes {
		if re.MatchFunc != "" {
			sb.WriteString(genTSMatchFunc(re.MatchFunc))
		}
		if re.FindFunc != "" {
			sb.WriteString(genTSFindFunc(re.FindFunc))
		}
		if re.GroupsFunc != "" {
			numGroups, _, err := extractGroupInfo(re.Pattern)
			if err != nil {
				return "", fmt.Errorf("pattern %q: %w", re.Pattern, err)
			}
			sb.WriteString(genTSGroupsFunc(re.GroupsFunc, numGroups))
		}
		if re.NamedGroupsFunc != "" {
			numGroups, namedGroups, err := extractGroupInfo(re.Pattern)
			if err != nil {
				return "", fmt.Errorf("pattern %q: %w", re.Pattern, err)
			}
			sb.WriteString(genTSNamedGroupsFunc(re.NamedGroupsFunc, re.GroupsExportName(), numGroups, namedGroups))
		}
	}

	sb.WriteString(genTSSetSection(cfg))
	return sb.String(), nil
}

// genTSSetSection generates TypeScript set wrappers.
func genTSSetSection(cfg config.BuildConfig) string {
	if !hasSetExports(cfg) {
		return ""
	}
	var out strings.Builder
	out.WriteString("\n// ---- set composition wrappers ----\n\n")
	out.WriteString("export interface SetMatch { patternId: number; start: number; end: number; }\n\n")
	for _, s := range cfg.Sets {
		bs := batchSize(s)
		if s.FindAll != "" || s.FindAny != "" {
			wasmExport := s.FindAll
			if wasmExport == "" {
				wasmExport = s.FindAny
			}
			if s.FindAll != "" {
				fmt.Fprintf(&out, `export function* %s(input: string | Uint8Array): Generator<SetMatch> {
    const b = _b(input);
    const outBuf = new Int32Array(_mem.buffer, _outBase, %d*3);
    _mem.set(b, _inBase);
    let startPos = 0;
    while (true) {
        const n = (_exp['%s'] as Function)(_inBase, b.length, _outBase, %d, startPos) as number;
        if (n <= 0) break;
        for (let i = 0; i < n; i++) {
            yield { patternId: outBuf[i*3], start: outBuf[i*3+1], end: outBuf[i*3+1]+outBuf[i*3+2] };
        }
        const l = outBuf[(n-1)*3+2]; startPos = outBuf[(n-1)*3+1] + (l > 0 ? l : 1);
    }
}
`, s.FindAll, bs, wasmExport, bs)
			}
			if s.FindAny != "" {
				fmt.Fprintf(&out, `export function %s(input: string | Uint8Array): SetMatch | null {
    const b = _b(input);
    const outBuf = new Int32Array(_mem.buffer, _outBase, 3);
    _mem.set(b, _inBase);
    if ((_exp['%s'] as Function)(_inBase, b.length, _outBase, 1, 0) <= 0) return null;
    return { patternId: outBuf[0], start: outBuf[1], end: outBuf[1]+outBuf[2] };
}
`, s.FindAny, wasmExport)
			}
		}
		if s.Match != "" {
			fmt.Fprintf(&out, `export function %s(input: string | Uint8Array): SetMatch | null {
    const b = _b(input);
    const outBuf = new Int32Array(_mem.buffer, _outBase, 2);
    _mem.set(b, _inBase);
    if ((_exp['%s'] as Function)(_inBase, b.length, _outBase, 1) <= 0) return null;
    return { patternId: outBuf[0], start: 0, end: outBuf[1] };
}
`, s.Match, s.Match)
		}
	}
	if hasEmitNameMap(cfg) {
		out.WriteString("const _patternNames: string[] = [")
		for i, re := range cfg.Regexes {
			if i > 0 {
				out.WriteString(", ")
			}
			fmt.Fprintf(&out, "%q", re.Name)
		}
		out.WriteString("];\nexport function patternName(id: number): string { return _patternNames[id] ?? ''; }\n")
	}
	return out.String()
}

func genTSMatchFunc(funcName string) string {
	return fmt.Sprintf(`// %s — anchored match; returns [endPos, true] on match or [0, false] if no match.
export function %s(input: string | Uint8Array): [number, boolean] {
    const b = _b(input);
    _mem.set(b, _inBase);
    const r = (_exp['%s'] as CallableFunction)(_inBase, b.length) as number;
    if (r < 0) return [0, false];
    return [r, true];
}

`, funcName, funcName, funcName)
}

func genTSFindFunc(funcName string) string {
	return fmt.Sprintf(`// %s — yields [start, end] for each non-overlapping match.
export function* %s(input: string | Uint8Array): Generator<[number, number]> {
    const b = _b(input);
    let off = 0;
    while (off <= b.length) {
        _mem.set(b.subarray(off), _inBase);
        const r = (_exp['%s'] as CallableFunction)(_inBase, b.length - off) as bigint;
        if (r < 0n) break;
        const relStart = Number(r >> 32n);
        const relEnd   = Number(r & 0xFFFFFFFFn);
        yield [off + relStart, off + relEnd];
        off += relEnd > relStart ? relEnd : relStart + 1;
    }
}

`, funcName, funcName, funcName)
}

func genTSGroupsFunc(funcName string, numGroups int) string {
	slotCount := numGroups * 2
	return fmt.Sprintf(`// %s — yields capture group arrays per match.
// Each element is [start, end] (absolute) or null for unmatched groups.
// Index 0 is the full match.
export function* %s(input: string | Uint8Array): Generator<Array<[number, number] | null>> {
    const b = _b(input);
    let off = 0;
    while (off <= b.length) {
        _mem.set(b.subarray(off), _inBase);
        const slots = new Int32Array(_mem.buffer, _outBase, %d);
        slots.fill(-1);
        if ((_exp['%s'] as CallableFunction)(_inBase, b.length - off, _outBase) < 0) {
            if (off === b.length) break;
            off++;
            continue;
        }
        const matchEnd = slots[1] >= 0 ? slots[1] : 0;
        const result: Array<[number, number] | null> = [];
        for (let i = 0; i < %d; i++) {
            const s = slots[i * 2], e = slots[i * 2 + 1];
            result.push(s < 0 ? null : [off + s, off + e]);
        }
        off += matchEnd > 0 ? matchEnd : 1;
        yield result;
    }
}

`, funcName, funcName, slotCount, funcName, numGroups)
}

func genTSNamedGroupsFunc(funcName, exportName string, numGroups int, namedGroups map[string]int) string {
	slotCount := numGroups * 2

	type entry struct {
		name  string
		index int
	}
	var entries []entry
	for name, idx := range namedGroups {
		entries = append(entries, entry{name, idx})
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].index < entries[j].index })

	var inserts strings.Builder
	for _, e := range entries {
		fmt.Fprintf(&inserts,
			"        if (slots[%d] >= 0) result['%s'] = [off + slots[%d], off + slots[%d]];\n",
			e.index*2, e.name, e.index*2, e.index*2+1)
	}

	return fmt.Sprintf(`// %s — yields named capture group objects per match.
// Each object maps name → [start, end] (absolute) for participating groups.
export function* %s(input: string | Uint8Array): Generator<Record<string, [number, number]>> {
    const b = _b(input);
    let off = 0;
    while (off <= b.length) {
        _mem.set(b.subarray(off), _inBase);
        const slots = new Int32Array(_mem.buffer, _outBase, %d);
        slots.fill(-1);
        if ((_exp['%s'] as CallableFunction)(_inBase, b.length - off, _outBase) < 0) {
            if (off === b.length) break;
            off++;
            continue;
        }
        const matchEnd = slots[1] >= 0 ? slots[1] : 0;
        const result: Record<string, [number, number]> = {};
%s        off += matchEnd > 0 ? matchEnd : 1;
        yield result;
    }
}

`, funcName, funcName, slotCount, exportName, inserts.String())
}
