package generate

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/qrdl/regexped/config"
)

// WIT generation for `wasm_format: component`.
//
// One config is one WIT package is one component. The function names come from
// the config's own `_func` values, mapped to kebab case; the package and world
// names come from `wit_package` / `wit_world` (config/names.go).
//
// Names are REJECTED rather than mangled when they cannot be represented. Two
// config names that map to the same kebab identifier are a hard error naming
// both, because silently renaming one of them would change which WASM export a
// caller reaches.

// witFunc is one emitted WIT function.
type witFunc struct {
	kebab  string // WIT name
	origin string // the config value it came from, for error messages
	field  string // match_func / find_func / groups_func
	doc    string
	sig    string
}

// witParts validates and derives, in ONE place, everything the WIT and the
// canonical export names are built from. Every caller goes through it, so a
// naming rule is enforced once and no caller carries an error branch that
// another caller has already made unreachable.
func witParts(cfg config.BuildConfig) (pkg, world string, funcs []witFunc, err error) {
	if pkg, err = cfg.WitPackageName(); err != nil {
		return "", "", nil, err
	}
	if world, err = cfg.WitWorldName(); err != nil {
		return "", "", nil, err
	}
	if funcs, err = witFuncs(cfg); err != nil {
		return "", "", nil, err
	}
	return pkg, world, funcs, nil
}

// WitText renders the .wit file for cfg.
func WitText(cfg config.BuildConfig) (string, error) {
	pkg, world, funcs, err := witParts(cfg)
	if err != nil {
		return "", err
	}
	return renderWit(cfg, pkg, world, funcs), nil
}

// renderWit is the text itself, with nothing left to validate.
func renderWit(cfg config.BuildConfig, pkg, world string, funcs []witFunc) string {
	var b strings.Builder
	pkgLine := "package regexped:" + pkg
	// The version is part of the package name and therefore of every export
	// name. Unset means no version at all — see config.BuildConfig.WitVersion.
	if cfg.WitVersion != "" {
		pkgLine += "@" + cfg.WitVersion
	}
	fmt.Fprintf(&b, "// Auto-generated by regexped. Do not edit.\n\n%s;\n\n", pkgLine)

	b.WriteString("interface matcher {\n")
	if len(funcs) > 0 {
		// Emitted whenever the interface has any function: every return type
		// carries it, DFA-only patterns included. A uniform ABI beats a
		// per-pattern one and the adapter costs one compare.
		b.WriteString("    /// The Backtracking engine exhausted its frame budget; the answer is unknown.\n")
		b.WriteString("    enum error-code { backtrack-overflow }\n")
	}
	for _, f := range funcs {
		b.WriteString("\n")
		for _, line := range strings.Split(f.doc, "\n") {
			fmt.Fprintf(&b, "    /// %s\n", line)
		}
		fmt.Fprintf(&b, "    %s: %s;\n", f.kebab, f.sig)
	}
	b.WriteString("}\n\n")

	fmt.Fprintf(&b, "world %s {\n    export matcher;\n}\n", world)
	return b.String()
}

// witFuncs maps the config's export names to WIT functions, in config order.
func witFuncs(cfg config.BuildConfig) ([]witFunc, error) {
	var out []witFunc
	// Collisions are reported against the FIRST name that claimed the kebab
	// form, so the message can name both originals.
	claimed := map[string]witFunc{}

	for _, re := range cfg.Regexps {
		for _, c := range []struct{ field, name, doc, sig string }{
			{"match_func", re.MatchFunc,
				"Anchored match against the whole input. some(end) on a match.",
				"func(input: list<u8>) -> result<option<u32>, error-code>"},
			{"find_func", re.FindFunc,
				"Leftmost match starting at or after `start`. Positions are absolute.",
				"func(input: list<u8>, start: u32) -> result<option<tuple<u32, u32>>, error-code>"},
			{"groups_func", re.GroupsFunc,
				"Captures of the leftmost match at or after `start`; index 0 is the whole\nmatch, an unset group is none. The list length is fixed per pattern.",
				"func(input: list<u8>, start: u32) -> result<option<list<option<tuple<u32, u32>>>>, error-code>"},
		} {
			if c.name == "" {
				continue
			}
			kebab, err := config.KebabIdent(c.name)
			if err != nil {
				return nil, fmt.Errorf("%s %q cannot be used as a WIT function name (%v): rename it, or use wasm_format: module",
					c.field, c.name, err)
			}
			f := witFunc{kebab: kebab, origin: c.name, field: c.field, doc: c.doc, sig: c.sig}
			if prev, dup := claimed[kebab]; dup {
				return nil, fmt.Errorf("%s %q and %s %q both map to the WIT name %q: rename one of them",
					prev.field, prev.origin, c.field, c.name, kebab)
			}
			claimed[kebab] = f
			out = append(out, f)
		}
	}
	return out, nil
}

// witStub writes the .wit file. `-` streams to stdout, like every other stub.
func witStub(cfg config.BuildConfig, out string) error {
	text, err := WitText(cfg)
	if err != nil {
		return fmt.Errorf("generate WIT: %w", err)
	}
	if out == "-" {
		_, err := os.Stdout.WriteString(text)
		return err
	}
	return writeStub(out, []byte(text))
}

// ComponentArtifacts derives everything a component build needs from ONE place:
// the WIT text, the canonical export name per configured func name, and the
// interface prefix those names are built from.
//
// One call rather than three because the three derivations share every failure
// mode — an unrepresentable package name, a func name that is not a WIT
// identifier, two names colliding — so three separate calls would give a caller
// two error branches that the first call has already made unreachable.
func ComponentArtifacts(cfg config.BuildConfig) (witText string, exportNames map[string]string, prefix string, err error) {
	pkg, world, funcs, err := witParts(cfg)
	if err != nil {
		return "", nil, "", err
	}
	prefix = interfacePrefix(pkg, cfg.WitVersion)
	return renderWit(cfg, pkg, world, funcs), exportNamesFrom(prefix, funcs), prefix, nil
}

// witExportNames returns the canonical-ABI export name for each emitted
// function, keyed by the config's own func name. compile/ needs exactly this
// mapping to name its adapter exports, and deriving it in one place keeps the
// .wit and the core module from disagreeing.
//
//	regexped:<pkg>[@<ver>]/matcher#<kebab>
func witExportNames(cfg config.BuildConfig) (map[string]string, error) {
	pkg, _, funcs, err := witParts(cfg)
	if err != nil {
		return nil, err
	}
	return exportNamesFrom(interfacePrefix(pkg, cfg.WitVersion), funcs), nil
}

// exportNamesFrom keys the canonical name by the config's own func name.
func exportNamesFrom(prefix string, funcs []witFunc) map[string]string {
	names := make(map[string]string, len(funcs))
	for _, f := range funcs {
		names[f.origin] = prefix + "#" + f.kebab
	}
	return names
}

// WitInterfacePrefix is `regexped:<pkg>[@<ver>]/matcher` — everything before
// the `#` in a canonical export name.
func WitInterfacePrefix(cfg config.BuildConfig) (string, error) {
	pkg, err := cfg.WitPackageName()
	if err != nil {
		return "", err
	}
	return interfacePrefix(pkg, cfg.WitVersion), nil
}

// interfacePrefix builds the prefix from an ALREADY VALIDATED package name. The
// version is part of it, and therefore part of every export name — see
// config.BuildConfig.WitVersion.
func interfacePrefix(pkg, version string) string {
	prefix := "regexped:" + pkg
	if version != "" {
		prefix += "@" + version
	}
	return prefix + "/matcher"
}

// sortedNames is a small helper for deterministic error output in tests.
func sortedNames(m map[string]string) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
