package generate

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/qrdl/regexped/config"
)

// WIT generation for `wasm_format: component`.
//
// One config is one WIT package is one component. The function names come from
// the config's own `_func` values, mapped to kebab case; the package and world
// names come from `wit_package` / `wit_world` (config/names.go).
//
// Names are REJECTED rather than mangled when they cannot be represented. Two
// config names that map to the same kebab identifier are a hard error naming
// both, because silently renaming one of them would change which WASM export a
// caller reaches.

// witFunc is one emitted WIT function.
type witFunc struct {
	kebab  string // WIT name
	origin string // the config value it came from, for error messages
	field  string // match_func / find_func / groups_func
	doc    string
	sig    string
}

// witParts validates and derives, in ONE place, everything the WIT and the
// canonical export names are built from. Every caller goes through it, so a
// naming rule is enforced once and no caller carries an error branch that
// another caller has already made unreachable.
func witParts(cfg config.BuildConfig) (pkg, world string, funcs []witFunc, sets []witSet, err error) {
	if pkg, err = cfg.WitPackageName(); err != nil {
		return "", "", nil, nil, err
	}
	if world, err = cfg.WitWorldName(); err != nil {
		return "", "", nil, nil, err
	}
	if funcs, err = witFuncs(cfg); err != nil {
		return "", "", nil, nil, err
	}
	// The set names are checked against the ones the matcher interface already
	// claimed: a kebab form used by both interfaces is legal WIT but a
	// duplicate symbol in every generated stub.
	claimed := make(map[string]witFunc, len(funcs))
	for _, f := range funcs {
		claimed[f.kebab] = f
	}
	if sets, err = witSets(cfg, claimed); err != nil {
		return "", "", nil, nil, err
	}
	return pkg, world, funcs, sets, nil
}

// WitText renders the .wit file for cfg.
func WitText(cfg config.BuildConfig) (string, error) {
	pkg, world, funcs, sets, err := witParts(cfg)
	if err != nil {
		return "", err
	}
	return renderWit(cfg, pkg, world, funcs, sets), nil
}

// renderWit is the text itself, with nothing left to validate.
func renderWit(cfg config.BuildConfig, pkg, world string, funcs []witFunc, sets []witSet) string {
	var b strings.Builder
	pkgLine := "package regexped:" + pkg
	// The version is part of the package name and therefore of every export
	// name. Unset means no version at all — see config.BuildConfig.WitVersion.
	if cfg.WitVersion != "" {
		pkgLine += "@" + cfg.WitVersion
	}
	fmt.Fprintf(&b, "// Auto-generated by regexped. Do not edit.\n\n%s;\n\n", pkgLine)

	if len(funcs) > 0 {
		b.WriteString("interface matcher {\n")
		// Emitted whenever the interface has any function: every return type
		// carries it, DFA-only patterns included. A uniform ABI beats a
		// per-pattern one and the adapter costs one compare.
		b.WriteString("    /// The Backtracking engine exhausted its frame budget; the answer is unknown.\n")
		// A single-pattern export cannot return the second case — the answer
		// cache belongs to sets — but the two interfaces share the error type's
		// NAME, and a consumer that used both would see one enum with two
		// different shapes. One spelling, both interfaces.
		b.WriteString("    enum error-code { backtrack-overflow, malformed-cache }\n")
		for _, f := range funcs {
			b.WriteString("\n")
			for _, line := range strings.Split(f.doc, "\n") {
				fmt.Fprintf(&b, "    /// %s\n", line)
			}
			fmt.Fprintf(&b, "    %s: %s;\n", f.kebab, f.sig)
		}
		b.WriteString("}\n\n")
	}
	b.WriteString(renderWitSets(sets))

	// The world exports only the interfaces that exist. A config with sets and
	// no single-pattern funcs gets no empty `matcher`, and vice versa.
	fmt.Fprintf(&b, "world %s {\n", world)
	if len(funcs) > 0 {
		b.WriteString("    export matcher;\n")
	}
	if len(sets) > 0 {
		b.WriteString("    export sets;\n")
	}
	b.WriteString("}\n")
	return b.String()
}

// witFuncs maps the config's export names to WIT functions, in config order.
func witFuncs(cfg config.BuildConfig) ([]witFunc, error) {
	var out []witFunc
	// Collisions are reported against the FIRST name that claimed the kebab
	// form, so the message can name both originals.
	claimed := map[string]witFunc{}

	for _, re := range cfg.Regexps {
		for _, c := range []struct{ field, name, doc, sig string }{
			{"match_func", re.MatchFunc,
				"Anchored match against the whole input. some(end) on a match.",
				"func(input: list<u8>) -> result<option<u32>, error-code>"},
			{"find_func", re.FindFunc,
				"Leftmost match starting at or after `start`. Positions are absolute.",
				"func(input: list<u8>, start: u32) -> result<option<tuple<u32, u32>>, error-code>"},
			{"groups_func", re.GroupsFunc,
				"Captures of the leftmost match at or after `start`; index 0 is the whole\nmatch, an unset group is none. The list length is fixed per pattern.",
				"func(input: list<u8>, start: u32) -> result<option<list<option<tuple<u32, u32>>>>, error-code>"},
		} {
			if c.name == "" {
				continue
			}
			kebab, err := config.KebabIdent(c.name)
			if err != nil {
				return nil, fmt.Errorf("%s %q cannot be used as a WIT function name (%v): rename it, or use wasm_format: module",
					c.field, c.name, err)
			}
			f := witFunc{kebab: kebab, origin: c.name, field: c.field, doc: c.doc, sig: c.sig}
			if prev, dup := claimed[kebab]; dup {
				return nil, fmt.Errorf("%s %q and %s %q both map to the WIT name %q: rename one of them",
					prev.field, prev.origin, c.field, c.name, kebab)
			}
			claimed[kebab] = f
			out = append(out, f)
		}
	}
	return out, nil
}

// witStub writes the .wit file. `-` streams to stdout, like every other stub.
func witStub(cfg config.BuildConfig, out string) error {
	text, err := WitText(cfg)
	if err != nil {
		return fmt.Errorf("generate WIT: %w", err)
	}
	if out == "-" {
		_, err := os.Stdout.WriteString(text)
		return err
	}
	return writeStub(out, []byte(text))
}

// kebabNames maps each configured func name to its WIT (kebab) identifier — the
// name a WASM import_name must carry verbatim.
//
// It takes the ALREADY VALIDATED functions rather than the config, so it cannot
// fail. Deriving them from the config again meant re-running KebabIdent on names
// witFuncs had already checked, and the error branch that came with it was
// unreachable — which is the thing witParts exists to prevent.
func kebabNames(funcs []witFunc) map[string]string {
	out := make(map[string]string, len(funcs))
	for _, f := range funcs {
		out[f.origin] = f.kebab
	}
	return out
}

// snakeNames is kebabNames in the form wit-bindgen's Rust macro produces: it
// lowercases the kebab identifier and joins with underscores, so
// `find-github-token` becomes `find_github_token`.
func snakeNames(funcs []witFunc) map[string]string {
	out := make(map[string]string, len(funcs))
	for _, f := range funcs {
		out[f.origin] = strings.ReplaceAll(f.kebab, "-", "_")
	}
	return out
}

// ComponentArtifacts derives everything a component build needs from ONE place:
// the WIT text, the canonical export name per configured func name, and the
// interface prefix those names are built from.
//
// One call rather than three because the three derivations share every failure
// mode — an unrepresentable package name, a func name that is not a WIT
// identifier, two names colliding — so three separate calls would give a caller
// two error branches that the first call has already made unreachable.
func ComponentArtifacts(cfg config.BuildConfig) (witText string, exportNames map[string]string, prefix string, err error) {
	text, names, _, prefix, err := ComponentArtifactsWithSets(cfg)
	return text, names, prefix, err
}

// ComponentArtifactsWithSets is ComponentArtifacts plus the per-set name table.
//
// Kept as a separate entry point so the pattern-only callers — and there are
// several, including the tests that predate sets — are not made to thread a nil
// map they never read.
func ComponentArtifactsWithSets(cfg config.BuildConfig) (
	witText string, exportNames map[string]string, setNames map[string]SetExportNames, prefix string, err error,
) {
	pkg, world, funcs, sets, err := witParts(cfg)
	if err != nil {
		return "", nil, nil, "", err
	}
	prefix = interfacePrefix(pkg, cfg.WitVersion)
	return renderWit(cfg, pkg, world, funcs, sets),
		exportNamesFrom(prefix, funcs),
		setExportNames(setsInterfacePrefix(pkg, cfg.WitVersion), sets),
		prefix, nil
}

// witExportNames returns the canonical-ABI export name for each emitted
// function, keyed by the config's own func name. compile/ needs exactly this
// mapping to name its adapter exports, and deriving it in one place keeps the
// .wit and the core module from disagreeing.
//
//	regexped:<pkg>[@<ver>]/matcher#<kebab>
func witExportNames(cfg config.BuildConfig) (map[string]string, error) {
	pkg, _, funcs, _, err := witParts(cfg)
	if err != nil {
		return nil, err
	}
	return exportNamesFrom(interfacePrefix(pkg, cfg.WitVersion), funcs), nil
}

// exportNamesFrom keys the canonical name by the config's own func name.
func exportNamesFrom(prefix string, funcs []witFunc) map[string]string {
	names := make(map[string]string, len(funcs))
	for _, f := range funcs {
		names[f.origin] = prefix + "#" + f.kebab
	}
	return names
}

// WitInterfacePrefix is `regexped:<pkg>[@<ver>]/matcher` — everything before
// the `#` in a canonical export name.
func WitInterfacePrefix(cfg config.BuildConfig) (string, error) {
	pkg, err := cfg.WitPackageName()
	if err != nil {
		return "", err
	}
	return interfacePrefix(pkg, cfg.WitVersion), nil
}

// interfacePrefix builds the prefix from an ALREADY VALIDATED package name. The
// version is part of it, and therefore part of every export name — see
// config.BuildConfig.WitVersion.
func interfacePrefix(pkg, version string) string {
	// The version sits AFTER the interface name, not after the package:
	//   regexped:secrets/matcher@2.3.0        correct
	//   regexped:secrets@2.3.0/matcher        REJECTED by wasm-tools with
	//                                         "failed to find export of interface"
	// This was wrong when wit_version shipped, and the unit test asserted the
	// wrong form too, so nothing caught it until a versioned component was
	// actually built. §3.1's proof-of-concept had it right all along.
	prefix := "regexped:" + pkg + "/matcher"
	if version != "" {
		prefix += "@" + version
	}
	return prefix
}

// sortedNames is a small helper for deterministic error output in tests.
func sortedNames(m map[string]string) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
