package generate

import (
	"fmt"
	"os"
	"strings"

	"github.com/qrdl/regexped/config"
)

// WIT generation for `wasm_format: component`.
//
// One config is one WIT package is one component. The function names come from
// the config's own `_func` values, mapped to kebab case; the package and world
// names come from `wit_package` / `wit_world` (config/names.go).
//
// Names are REJECTED rather than mangled when they cannot be represented. Two
// config names that map to the same kebab identifier are a hard error naming
// both, because silently renaming one of them would change which WASM export a
// caller reaches.

// witKind says which SHAPE a configured export takes in the interface.
//
// `match_func` is a plain function: one call, one answer, nothing to carry
// between calls. `find_func` and `groups_func` ITERATE, and an iterating
// function has to be handed the input again on every step — which the
// canonical ABI copies. So they are RESOURCES: the constructor takes the input
// once, `next` takes only the handle, and `[dtor]` releases it. That is the
// same reason a set's `find` is a resource, and the cost it removes was
// measured there at 2,800 ns per stateless call against 230-400 ns for a
// resource `next` over 4 KB.
type witKind int

const (
	witKindMatch witKind = iota
	witKindFind
	witKindGroups
)

// iterates reports whether this export is a resource rather than a function.
func (k witKind) iterates() bool { return k != witKindMatch }

// witFunc is one emitted WIT item: a function, or a resource when it iterates.
type witFunc struct {
	kebab  string // WIT name — of the function, or of the resource
	origin string // the config value it came from, for error messages
	field  string // match_func / find_func / groups_func
	kind   witKind
	doc    string
	// sig is the function's signature for witKindMatch, and the RETURN type of
	// `next` for a resource.
	sig string
}

// witParts validates and derives, in ONE place, everything the WIT and the
// canonical export names are built from. Every caller goes through it, so a
// naming rule is enforced once and no caller carries an error branch that
// another caller has already made unreachable.
func witParts(cfg config.BuildConfig) (pkg, world string, funcs []witFunc, sets []witSet, err error) {
	if pkg, err = cfg.WitPackageName(); err != nil {
		return "", "", nil, nil, err
	}
	if world, err = cfg.WitWorldName(); err != nil {
		return "", "", nil, nil, err
	}
	if funcs, err = witFuncs(cfg); err != nil {
		return "", "", nil, nil, err
	}
	// The set names are checked against the ones the matcher interface already
	// claimed: a kebab form used by both interfaces is legal WIT but a
	// duplicate symbol in every generated stub.
	claimed := make(map[string]witFunc, len(funcs))
	for _, f := range funcs {
		claimed[f.kebab] = f
	}
	if sets, err = witSets(cfg, claimed); err != nil {
		return "", "", nil, nil, err
	}
	return pkg, world, funcs, sets, nil
}

// WitText renders the .wit file for cfg.
func WitText(cfg config.BuildConfig) (string, error) {
	pkg, world, funcs, sets, err := witParts(cfg)
	if err != nil {
		return "", err
	}
	return renderWit(cfg, pkg, world, funcs, sets), nil
}

// renderWit is the text itself, with nothing left to validate.
func renderWit(cfg config.BuildConfig, pkg, world string, funcs []witFunc, sets []witSet) string {
	var b strings.Builder
	pkgLine := "package regexped:" + pkg
	// The version is part of the package name and therefore of every export
	// name. Unset means no version at all — see config.BuildConfig.WitVersion.
	if cfg.WitVersion != "" {
		pkgLine += "@" + cfg.WitVersion
	}
	fmt.Fprintf(&b, "// Auto-generated by regexped. Do not edit.\n\n%s;\n\n", pkgLine)

	if len(funcs) > 0 {
		b.WriteString("interface matcher {\n")
		// Emitted whenever the interface has any function: every return type
		// carries it, DFA-only patterns included. A uniform ABI beats a
		// per-pattern one and the adapter costs one compare.
		b.WriteString("    /// Why an answer is unknown. backtrack-overflow: the Backtracking engine\n")
		b.WriteString("    /// exhausted its frame budget. malformed-cache and out-of-order are never\n")
		b.WriteString("    /// returned by these functions — they belong to a set's overlapping find —\n")
		b.WriteString("    /// and are listed so both interfaces share one error type.\n")
		// A single-pattern export cannot return the second or third case — the
		// answer cache belongs to sets — but the two interfaces share the error type's
		// NAME, and a consumer that used both would see one enum with two
		// different shapes. One spelling, both interfaces.
		b.WriteString("    enum error-code { backtrack-overflow, malformed-cache, out-of-order }\n")
		for _, f := range funcs {
			b.WriteString("\n")
			for _, line := range strings.Split(f.doc, "\n") {
				if line == "" {
					b.WriteString("    ///\n")
					continue
				}
				fmt.Fprintf(&b, "    /// %s\n", line)
			}
			if !f.kind.iterates() {
				fmt.Fprintf(&b, "    %s: %s;\n", f.kebab, f.sig)
				continue
			}
			// An iterating export is a RESOURCE: the constructor takes the
			// input, `next` takes only the handle, and dropping it ends the
			// scan. The constructor's `start` bounds where the FIRST step
			// searches from; it never truncates what the engine can see behind
			// that point, so a leading \b or (?m:^) still judges a real
			// preceding byte.
			fmt.Fprintf(&b, `    resource %s {
        constructor(input: list<u8>, start: u32);
        next: func() -> %s;
    }
`, f.kebab, f.sig)
		}
		b.WriteString("}\n\n")
	}
	b.WriteString(renderWitSets(sets))

	// The world exports only the interfaces that exist. A config with sets and
	// no single-pattern funcs gets no empty `matcher`, and vice versa.
	fmt.Fprintf(&b, "world %s {\n", world)
	if len(funcs) > 0 {
		b.WriteString("    export matcher;\n")
	}
	if len(sets) > 0 {
		b.WriteString("    export sets;\n")
	}
	b.WriteString("}\n")
	return b.String()
}

// witFuncs maps the config's export names to WIT functions, in config order.
func witFuncs(cfg config.BuildConfig) ([]witFunc, error) {
	var out []witFunc
	// Collisions are reported against the FIRST name that claimed the kebab
	// form, so the message can name both originals.
	claimed := map[string]witFunc{}

	for _, re := range cfg.Regexps {
		for _, c := range []struct {
			field, name, doc, sig string
			kind                  witKind
		}{
			{"match_func", re.MatchFunc,
				"Anchored match against the whole input. some(end) on a match.",
				"func(input: list<u8>) -> result<option<u32>, error-code>", witKindMatch},
			{"find_func", re.FindFunc,
				"A scan in progress. `next` answers the leftmost match at or after the\nposition the scan has reached, and none means it is finished. Positions\nare absolute.\n\nA resource rather than a function because the scan needs state between\ncalls — the input and the position — and a function would be handed the\ninput again on every step, which the canonical ABI copies. Constructed\nonce, the input crosses once.",
				"result<option<tuple<u32, u32>>, error-code>", witKindFind},
			{"groups_func", re.GroupsFunc,
				"A scan in progress, reporting each match's capture groups. Index 0 is\nthe whole match and an unset group is none, so the list length is fixed\nper pattern. An empty list means the scan is finished.\n\nA resource for the same reason find is: the input crosses once.",
				"result<list<option<tuple<u32, u32>>>, error-code>", witKindGroups},
		} {
			if c.name == "" {
				continue
			}
			kebab, err := config.KebabIdent(c.name)
			if err != nil {
				return nil, fmt.Errorf("%s %q cannot be used as a WIT function name (%v): rename it, or use wasm_format: module",
					c.field, c.name, err)
			}
			f := witFunc{kebab: kebab, origin: c.name, field: c.field, kind: c.kind, doc: c.doc, sig: c.sig}
			if prev, dup := claimed[kebab]; dup {
				return nil, fmt.Errorf("%s %q and %s %q both map to the WIT name %q: rename one of them",
					prev.field, prev.origin, c.field, c.name, kebab)
			}
			claimed[kebab] = f
			out = append(out, f)
		}
	}
	return out, nil
}

// witStub writes the .wit file. `-` streams to stdout, like every other stub.
func witStub(cfg config.BuildConfig, out string) error {
	text, err := WitText(cfg)
	if err != nil {
		return fmt.Errorf("generate WIT: %w", err)
	}
	if out == "-" {
		_, err := os.Stdout.WriteString(text)
		return err
	}
	return writeStub(out, []byte(text))
}

// kebabNames maps each configured func name to its WIT (kebab) identifier — the
// name a WASM import_name must carry verbatim.
//
// It takes the ALREADY VALIDATED functions rather than the config, so it cannot
// fail. Deriving them from the config again meant re-running KebabIdent on names
// witFuncs had already checked, and the error branch that came with it was
// unreachable — which is the thing witParts exists to prevent.
func kebabNames(funcs []witFunc) map[string]string {
	out := make(map[string]string, len(funcs))
	for _, f := range funcs {
		out[f.origin] = f.kebab
	}
	return out
}

// dropWorld returns the lines of generated WIT without its `world … { … }`
// block. A dependency package supplies the interfaces only, and an exporting
// world left in one makes the document describe something else. The block is
// brace-balanced; a world that opens and closes on its own line is dropped
// alone. The Rust stub nests what remains and the C stub writes it to a deps
// directory, and each used to carry its own copy of this walk.
func dropWorld(witText string) []string {
	var out []string
	depth, inWorld := 0, false
	for _, l := range strings.Split(witText, "\n") {
		t := strings.TrimSpace(l)
		if !inWorld && strings.HasPrefix(t, "world ") {
			depth = strings.Count(t, "{") - strings.Count(t, "}")
			inWorld = depth > 0
			continue
		}
		if inWorld {
			depth += strings.Count(t, "{") - strings.Count(t, "}")
			inWorld = depth > 0
			continue
		}
		out = append(out, l)
	}
	return out
}

// ComponentArtifactsWithSets derives everything a component build needs from ONE
// place: the WIT text, the canonical export name per configured func name, the
// per-set name table, and the interface prefix those names are built from.
//
// One call rather than three because the three derivations share every failure
// mode — an unrepresentable package name, a func name that is not a WIT
// identifier, two names colliding — so three separate calls would give a caller
// two error branches that the first call has already made unreachable.
func ComponentArtifactsWithSets(cfg config.BuildConfig) (
	witText string, exportNames map[string]string, resourceNames map[string]PatternResourceNames,
	setNames map[string]SetExportNames, prefix string, err error,
) {
	pkg, world, funcs, sets, err := witParts(cfg)
	if err != nil {
		return "", nil, nil, nil, "", err
	}
	prefix = interfacePrefix(pkg, cfg.WitVersion)
	return renderWit(cfg, pkg, world, funcs, sets),
		exportNamesFrom(prefix, funcs),
		resourceNamesFrom(prefix, funcs),
		setExportNames(setsInterfacePrefix(pkg, cfg.WitVersion), sets),
		prefix, nil
}

// witExportNames returns the canonical-ABI export name for each emitted
// function, keyed by the config's own func name. compile/ needs exactly this
// mapping to name its adapter exports, and deriving it in one place keeps the
// .wit and the core module from disagreeing.
//
//	regexped:<pkg>[@<ver>]/matcher#<kebab>
func witExportNames(cfg config.BuildConfig) (map[string]string, error) {
	pkg, _, funcs, _, err := witParts(cfg)
	if err != nil {
		return nil, err
	}
	return exportNamesFrom(interfacePrefix(pkg, cfg.WitVersion), funcs), nil
}

// exportNamesFrom keys the canonical name by the config's own func name.
//
// Only the FUNCTION-shaped exports appear here. An iterating export is a
// resource and contributes three names plus an imported builtin, which
// PatternResourceNames carries — see resourceNamesFrom.
func exportNamesFrom(prefix string, funcs []witFunc) map[string]string {
	names := make(map[string]string, len(funcs))
	for _, f := range funcs {
		if f.kind.iterates() {
			continue
		}
		names[f.origin] = prefix + "#" + f.kebab
	}
	return names
}

// PatternResourceNames is every canonical name ONE iterating pattern export
// contributes, keyed so compile/ can stamp its adapters without re-deriving a
// single one.
//
// It is the single-pattern twin of SetExportNames, and deliberately the same
// shape: the two resources differ in what `next` answers, not in how they are
// named, imported or destroyed.
type PatternResourceNames struct {
	// Groups marks the groups shape, whose `next` returns a list of capture
	// spans where find's returns one span pair. The adapters differ only
	// there, and compile/ needs to know which body to emit.
	Groups      bool
	Constructor string
	Next        string
	Dtor        string
	// ResourceImport is the synthetic module the canon builtins come from:
	// "[export]regexped:<pkg>/matcher[@<ver>]". ResourceNew is the field name
	// of the resource.new builtin within it.
	ResourceImport string
	ResourceNew    string
}

// resourceNamesFrom builds the per-resource name table for the iterating
// exports, keyed by the config's own func name.
func resourceNamesFrom(prefix string, funcs []witFunc) map[string]PatternResourceNames {
	var out map[string]PatternResourceNames
	for _, f := range funcs {
		if !f.kind.iterates() {
			continue
		}
		if out == nil {
			out = map[string]PatternResourceNames{}
		}
		out[f.origin] = PatternResourceNames{
			Groups:         f.kind == witKindGroups,
			Constructor:    prefix + "#[constructor]" + f.kebab,
			Next:           prefix + "#[method]" + f.kebab + ".next",
			Dtor:           prefix + "#[dtor]" + f.kebab,
			ResourceImport: "[export]" + prefix,
			ResourceNew:    "[resource-new]" + f.kebab,
		}
	}
	return out
}

// WitInterfacePrefix is `regexped:<pkg>[@<ver>]/matcher` — everything before
// the `#` in a canonical export name.
func WitInterfacePrefix(cfg config.BuildConfig) (string, error) {
	pkg, err := cfg.WitPackageName()
	if err != nil {
		return "", err
	}
	return interfacePrefix(pkg, cfg.WitVersion), nil
}

// interfacePrefix builds the prefix from an ALREADY VALIDATED package name. The
// version is part of it, and therefore part of every export name — see
// config.BuildConfig.WitVersion.
func interfacePrefix(pkg, version string) string {
	// The version sits AFTER the interface name, not after the package:
	//   regexped:secrets/matcher@2.3.0        correct
	//   regexped:secrets@2.3.0/matcher        REJECTED by wasm-tools with
	//                                         "failed to find export of interface"
	// This was wrong when wit_version shipped, and the unit test asserted the
	// wrong form too, so nothing caught it until a versioned component was
	// actually built. The original proof of concept had it right all along.
	prefix := "regexped:" + pkg + "/matcher"
	if version != "" {
		prefix += "@" + version
	}
	return prefix
}
