package generate

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/qrdl/regexped/config"
)

func componentCfg() config.BuildConfig {
	return config.BuildConfig{
		WasmFormat:   "component",
		ImportModule: "url_ipv6",
		Regexps: []config.RegexEntry{
			{Pattern: `a`, MatchFunc: "email_match"},
			{Pattern: `b`, FindFunc: "email_find"},
			{Pattern: `c`, GroupsFunc: "urlGroups"},
		},
	}
}

const wantWit = `// Auto-generated by regexped. Do not edit.

package regexped:url-ipv6;

interface matcher {
    /// The Backtracking engine exhausted its frame budget; the answer is unknown.
    enum error-code { backtrack-overflow }

    /// Anchored match against the whole input. some(end) on a match.
    email-match: func(input: list<u8>) -> result<option<u32>, error-code>;

    /// Leftmost match starting at or after ` + "`start`" + `. Positions are absolute.
    email-find: func(input: list<u8>, start: u32) -> result<option<tuple<u32, u32>>, error-code>;

    /// Captures of the leftmost match at or after ` + "`start`" + `; index 0 is the whole
    /// match, an unset group is none. The list length is fixed per pattern.
    url-groups: func(input: list<u8>, start: u32) -> result<option<list<option<tuple<u32, u32>>>>, error-code>;
}

world url-ipv6 {
    export matcher;
}
`

func TestWitTextGolden(t *testing.T) {
	got, err := WitText(componentCfg())
	if err != nil {
		t.Fatal(err)
	}
	if got != wantWit {
		t.Errorf("WIT mismatch.\n--- got ---\n%s\n--- want ---\n%s", got, wantWit)
	}
}

// The version is part of the package name, and therefore of every export name.
func TestWitVersionAppears(t *testing.T) {
	cfg := componentCfg()
	cfg.WitVersion = "2.3.0"
	got, err := WitText(cfg)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(got, "package regexped:url-ipv6@2.3.0;") {
		t.Errorf("versioned package line missing:\n%s", got)
	}
	prefix, err := WitInterfacePrefix(cfg)
	if err != nil || prefix != "regexped:url-ipv6@2.3.0/matcher" {
		t.Errorf("prefix = %q, %v", prefix, err)
	}
	names, err := witExportNames(cfg)
	if err != nil {
		t.Fatal(err)
	}
	if got := names["email_find"]; got != "regexped:url-ipv6@2.3.0/matcher#email-find" {
		t.Errorf("export name = %q", got)
	}
	// Unset, no @version anywhere.
	cfg.WitVersion = ""
	names, _ = witExportNames(cfg)
	for _, k := range sortedNames(names) {
		if strings.Contains(names[k], "@") {
			t.Errorf("unversioned export name carries @: %q", names[k])
		}
	}
}

// wit_world names the world independently of the package.
func TestWitWorldOverride(t *testing.T) {
	cfg := componentCfg()
	cfg.WitWorld = "scanner"
	got, err := WitText(cfg)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(got, "world scanner {") {
		t.Errorf("wit_world not honoured:\n%s", got)
	}
	// ...and it does not leak into the package or the export names.
	if !strings.Contains(got, "package regexped:url-ipv6;") {
		t.Errorf("wit_world must not change the package:\n%s", got)
	}
}

// Names are rejected, never mangled: a silent rename would change which WASM
// export a caller reaches.
func TestWitNameErrors(t *testing.T) {
	cfg := componentCfg()
	cfg.Regexps = []config.RegexEntry{{Pattern: "a", MatchFunc: "_bad"}}
	if _, err := WitText(cfg); err == nil || !strings.Contains(err.Error(), "match_func") {
		t.Errorf("err = %v, want one naming match_func", err)
	}

	// Two config names that kebab to the same identifier: an error naming both.
	cfg.Regexps = []config.RegexEntry{
		{Pattern: "a", MatchFunc: "url_match"},
		{Pattern: "b", FindFunc: "urlMatch"},
	}
	_, err := WitText(cfg)
	if err == nil {
		t.Fatal("want a collision error")
	}
	for _, want := range []string{"url_match", "urlMatch", "url-match"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("collision error %v does not mention %q", err, want)
		}
	}
}

// An entry with no _func fields contributes nothing, exactly as it compiles to
// nothing.
func TestWitSkipsEntriesWithoutFuncs(t *testing.T) {
	cfg := componentCfg()
	cfg.Regexps = append(cfg.Regexps, config.RegexEntry{Pattern: "z"})
	got, err := WitText(cfg)
	if err != nil {
		t.Fatal(err)
	}
	if got != wantWit {
		t.Errorf("a func-less entry changed the WIT:\n%s", got)
	}
}

// The generated text must be WIT that the real toolchain accepts, not merely
// plausible. Skipped rather than failed when wasm-tools is absent, per the
// compile package's convention.
func TestWitRoundTripsThroughWasmTools(t *testing.T) {
	tool, err := exec.LookPath("wasm-tools")
	if err != nil {
		t.Skip("wasm-tools not in PATH; skipping WIT round-trip")
	}
	for _, version := range []string{"", "2.3.0"} {
		cfg := componentCfg()
		cfg.WitVersion = version
		text, err := WitText(cfg)
		if err != nil {
			t.Fatal(err)
		}
		path := filepath.Join(t.TempDir(), "gen.wit")
		if err := os.WriteFile(path, []byte(text), 0o644); err != nil {
			t.Fatal(err)
		}
		out, err := exec.Command(tool, "component", "wit", path).CombinedOutput()
		if err != nil {
			t.Fatalf("wasm-tools rejected the generated WIT (version %q): %v\n%s\n--- generated ---\n%s",
				version, err, out, text)
		}
	}
}

// stub_type: wit routes to the WIT generator, and .wit infers it.
func TestWitStubDispatch(t *testing.T) {
	dir := t.TempDir()
	out := filepath.Join(dir, "out.wit")
	cfg := componentCfg()
	cfg.StubFile = out
	st, err := config.ResolveStubType(cfg)
	if err != nil || st != "wit" {
		t.Fatalf("ResolveStubType = %q, %v; want wit", st, err)
	}
	if err := CmdGenerateStub(cfg, out); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(out)
	if err != nil {
		t.Fatal(err)
	}
	if string(data) != wantWit {
		t.Errorf("written stub differs from WitText")
	}
}
