package generate

import (
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/qrdl/regexped/config"
)

func componentCfg() config.BuildConfig {
	return config.BuildConfig{
		WasmFormat:   "component",
		ImportModule: "url_ipv6",
		Regexps: []config.RegexEntry{
			{Pattern: `a`, MatchFunc: "email_match"},
			{Pattern: `b`, FindFunc: "email_find"},
			{Pattern: `c`, GroupsFunc: "urlGroups"},
		},
	}
}

const wantWit = `// Auto-generated by regexped. Do not edit.

package regexped:url-ipv6;

interface matcher {
    /// Why an answer is unknown. backtrack-overflow: the Backtracking engine
    /// exhausted its frame budget. malformed-cache and out-of-order are never
    /// returned by these functions — they belong to a set's overlapping find —
    /// and are listed so both interfaces share one error type.
    enum error-code { backtrack-overflow, malformed-cache, out-of-order }

    /// Anchored match against the whole input. some(end) on a match.
    email-match: func(input: list<u8>) -> result<option<u32>, error-code>;

    /// Leftmost match starting at or after ` + "`start`" + `. Positions are absolute.
    email-find: func(input: list<u8>, start: u32) -> result<option<tuple<u32, u32>>, error-code>;

    /// Captures of the leftmost match at or after ` + "`start`" + `; index 0 is the whole
    /// match, an unset group is none. The list length is fixed per pattern.
    url-groups: func(input: list<u8>, start: u32) -> result<option<list<option<tuple<u32, u32>>>>, error-code>;
}

world url-ipv6 {
    export matcher;
}
`

func TestWitTextGolden(t *testing.T) {
	got, err := WitText(componentCfg())
	if err != nil {
		t.Fatal(err)
	}
	if got != wantWit {
		t.Errorf("WIT mismatch.\n--- got ---\n%s\n--- want ---\n%s", got, wantWit)
	}
}

// The version is part of the package name, and therefore of every export name.
func TestWitVersionAppears(t *testing.T) {
	cfg := componentCfg()
	cfg.WitVersion = "2.3.0"
	got, err := WitText(cfg)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(got, "package regexped:url-ipv6@2.3.0;") {
		t.Errorf("versioned package line missing:\n%s", got)
	}
	// The version goes after the INTERFACE name; wasm-tools rejects the other
	// placement with "failed to find export of interface".
	prefix, err := WitInterfacePrefix(cfg)
	if err != nil || prefix != "regexped:url-ipv6/matcher@2.3.0" {
		t.Errorf("prefix = %q, %v", prefix, err)
	}
	names, err := witExportNames(cfg)
	if err != nil {
		t.Fatal(err)
	}
	// EXACTLY one placement: the version after the INTERFACE name. The other
	// spellings build plausible-looking names and fail `component new`.
	if got := names["email_find"]; got != "regexped:url-ipv6/matcher@2.3.0#email-find" {
		t.Errorf("export name = %q, want regexped:url-ipv6/matcher@2.3.0#email-find", got)
	}
	for k, v := range names {
		if i := strings.Index(v, "#"); i >= 0 && strings.Contains(v[i:], "@") {
			t.Errorf("export %s = %q carries the version after the function name", k, v)
		}
		if strings.Contains(v, "regexped:url-ipv6@") {
			t.Errorf("export %s = %q carries the version on the package path", k, v)
		}
	}
	if strings.Contains(got, "regexped:url-ipv6@2.3.0/") {
		t.Errorf("the WIT text places the version on the package path:\n%s", got)
	}
	// Unset, no @version anywhere.
	cfg.WitVersion = ""
	names, _ = witExportNames(cfg)
	for _, k := range sortedNames(names) {
		if strings.Contains(names[k], "@") {
			t.Errorf("unversioned export name carries @: %q", names[k])
		}
	}
}

// wit_world names the world independently of the package.
func TestWitWorldOverride(t *testing.T) {
	cfg := componentCfg()
	cfg.WitWorld = "scanner"
	got, err := WitText(cfg)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(got, "world scanner {") {
		t.Errorf("wit_world not honoured:\n%s", got)
	}
	// ...and it does not leak into the package or the export names.
	if !strings.Contains(got, "package regexped:url-ipv6;") {
		t.Errorf("wit_world must not change the package:\n%s", got)
	}
}

// Names are rejected, never mangled: a silent rename would change which WASM
// export a caller reaches.
func TestWitNameErrors(t *testing.T) {
	cfg := componentCfg()
	cfg.Regexps = []config.RegexEntry{{Pattern: "a", MatchFunc: "_bad"}}
	if _, err := WitText(cfg); err == nil || !strings.Contains(err.Error(), "match_func") {
		t.Errorf("err = %v, want one naming match_func", err)
	}

	// Two config names that kebab to the same identifier: an error naming both.
	cfg.Regexps = []config.RegexEntry{
		{Pattern: "a", MatchFunc: "url_match"},
		{Pattern: "b", FindFunc: "urlMatch"},
	}
	_, err := WitText(cfg)
	if err == nil {
		t.Fatal("want a collision error")
	}
	for _, want := range []string{"url_match", "urlMatch", "url-match"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("collision error %v does not mention %q", err, want)
		}
	}
}

// An entry with no _func fields contributes nothing, exactly as it compiles to
// nothing.
func TestWitSkipsEntriesWithoutFuncs(t *testing.T) {
	cfg := componentCfg()
	cfg.Regexps = append(cfg.Regexps, config.RegexEntry{Pattern: "z"})
	got, err := WitText(cfg)
	if err != nil {
		t.Fatal(err)
	}
	if got != wantWit {
		t.Errorf("a func-less entry changed the WIT:\n%s", got)
	}
}

// The generated text must be WIT that the real toolchain accepts, not merely
// plausible. Skipped rather than failed when wasm-tools is absent, per the
// compile package's convention.
func TestWitRoundTripsThroughWasmTools(t *testing.T) {
	tool, err := exec.LookPath("wasm-tools")
	if err != nil {
		t.Skip("wasm-tools not in PATH; skipping WIT round-trip")
	}
	for _, version := range []string{"", "2.3.0"} {
		cfg := componentCfg()
		cfg.WitVersion = version
		text, err := WitText(cfg)
		if err != nil {
			t.Fatal(err)
		}
		path := filepath.Join(t.TempDir(), "gen.wit")
		if err := os.WriteFile(path, []byte(text), 0o644); err != nil {
			t.Fatal(err)
		}
		out, err := exec.Command(tool, "component", "wit", path).CombinedOutput()
		if err != nil {
			t.Fatalf("wasm-tools rejected the generated WIT (version %q): %v\n%s\n--- generated ---\n%s",
				version, err, out, text)
		}
	}
}

// stub_type: wit routes to the WIT generator, and .wit infers it.
func TestWitStubDispatch(t *testing.T) {
	dir := t.TempDir()
	out := filepath.Join(dir, "out.wit")
	cfg := componentCfg()
	cfg.StubFile = out
	st, err := config.ResolveStubType(cfg)
	if err != nil || st != "wit" {
		t.Fatalf("ResolveStubType = %q, %v; want wit", st, err)
	}
	if err := CmdGenerateStub(cfg, out); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(out)
	if err != nil {
		t.Fatal(err)
	}
	if string(data) != wantWit {
		t.Errorf("written stub differs from WitText")
	}
}

// The naming rules are enforced in ONE place (witParts), so every entry point
// must report the same failure for the same config — otherwise a caller could
// slip past a rule by choosing a different door.
func TestEveryWitEntryPointEnforcesTheSameRules(t *testing.T) {
	bad := map[string]func(config.BuildConfig) config.BuildConfig{
		"wit_package": func(c config.BuildConfig) config.BuildConfig {
			c.WitPackage = "Not_Kebab"
			return c
		},
		"wit_world": func(c config.BuildConfig) config.BuildConfig {
			c.WitWorld = "Bad World"
			return c
		},
		"match_func": func(c config.BuildConfig) config.BuildConfig {
			c.Regexps = []config.RegexEntry{{Pattern: "a", MatchFunc: "_bad"}}
			return c
		},
	}
	for want, mutate := range bad {
		cfg := mutate(componentCfg())
		if _, err := WitText(cfg); err == nil || !strings.Contains(err.Error(), want) {
			t.Errorf("WitText: err = %v, want one naming %s", err, want)
		}
		if _, err := witExportNames(cfg); err == nil || !strings.Contains(err.Error(), want) {
			t.Errorf("witExportNames: err = %v, want one naming %s", err, want)
		}
		if _, _, _, err := componentArtifacts(cfg); err == nil || !strings.Contains(err.Error(), want) {
			t.Errorf("ComponentArtifacts: err = %v, want one naming %s", err, want)
		}
		if err := witStub(cfg, filepath.Join(t.TempDir(), "o.wit")); err == nil ||
			!strings.Contains(err.Error(), want) {
			t.Errorf("witStub: err = %v, want one naming %s", err, want)
		}
	}
	// wit_world is NOT part of any export name, so a bad one must not be
	// reported by the prefix builder — that would be a rule applied where it
	// does not belong.
	cfg := componentCfg()
	cfg.WitWorld = "Bad World"
	if _, err := WitInterfacePrefix(cfg); err != nil {
		t.Errorf("WitInterfacePrefix must not care about wit_world: %v", err)
	}
	cfg = componentCfg()
	cfg.WitPackage = "Not_Kebab"
	if _, err := WitInterfacePrefix(cfg); err == nil {
		t.Error("WitInterfacePrefix must reject a bad wit_package")
	}
}

// ComponentArtifacts must agree with the individual entry points; it exists to
// avoid three derivations, not to become a fourth one.
func TestComponentArtifactsAgreesWithItsParts(t *testing.T) {
	for _, version := range []string{"", "2.3.0"} {
		cfg := componentCfg()
		cfg.WitVersion = version
		text, names, prefix, err := componentArtifacts(cfg)
		if err != nil {
			t.Fatal(err)
		}
		wantText, err := WitText(cfg)
		if err != nil {
			t.Fatal(err)
		}
		if text != wantText {
			t.Errorf("version %q: text differs from WitText", version)
		}
		wantPrefix, err := WitInterfacePrefix(cfg)
		if err != nil {
			t.Fatal(err)
		}
		if prefix != wantPrefix {
			t.Errorf("version %q: prefix %q != %q", version, prefix, wantPrefix)
		}
		wantNames, err := witExportNames(cfg)
		if err != nil {
			t.Fatal(err)
		}
		if len(names) != len(wantNames) {
			t.Fatalf("version %q: %d names, want %d", version, len(names), len(wantNames))
		}
		for k, v := range wantNames {
			if names[k] != v {
				t.Errorf("version %q: name[%s] = %q, want %q", version, k, names[k], v)
			}
		}
	}
}

// `-` streams the WIT, like every other stub type.
func TestWitStubToStdout(t *testing.T) {
	r, w, err := os.Pipe()
	if err != nil {
		t.Fatal(err)
	}
	saved := os.Stdout
	os.Stdout = w
	done := make(chan string, 1)
	go func() {
		buf := make([]byte, 1<<16)
		n, _ := r.Read(buf)
		done <- string(buf[:n])
	}()
	err = witStub(componentCfg(), "-")
	w.Close()
	os.Stdout = saved
	if err != nil {
		t.Fatal(err)
	}
	if got := <-done; got != wantWit {
		t.Errorf("stdout WIT differs from WitText:\n%s", got)
	}
}

// An unwritable destination must surface, not be swallowed.
func TestWitStubWriteFailure(t *testing.T) {
	dir := t.TempDir()
	blocker := filepath.Join(dir, "blocker")
	if err := os.WriteFile(blocker, nil, 0o644); err != nil {
		t.Fatal(err)
	}
	if err := witStub(componentCfg(), filepath.Join(blocker, "o.wit")); err == nil {
		t.Error("want an error writing under a regular file")
	}
}

// writeStub's write failure, distinct from its mkdir failure: the parent
// directory is created fine, and the destination itself is what cannot be
// written.
func TestWriteStubWriteFailure(t *testing.T) {
	dir := t.TempDir()
	if err := writeStub(dir, []byte("x")); err == nil ||
		!strings.Contains(err.Error(), "write") {
		t.Errorf("writing over a directory: err = %v", err)
	}
}

// componentArtifacts is ComponentArtifactsWithSets without the set table, for
// the tests that predate sets.
func componentArtifacts(cfg config.BuildConfig) (string, map[string]string, string, error) {
	text, names, _, prefix, err := ComponentArtifactsWithSets(cfg)
	return text, names, prefix, err
}

// sortedNames is a small helper for deterministic error output in tests.
func sortedNames(m map[string]string) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
