// Stubs are auto-generated by: regexped stub --rust
// Each is wrapped in its own module to avoid FFI name collisions (all three
// export a WASM function named "find" from different import modules).
mod github { include!("github_stub.rs"); }
mod jwt    { include!("jwt_stub.rs");    }
mod aws    { include!("aws_stub.rs");    }

fn report(label: &str, input: &[u8], result: Option<(usize, usize)>) {
    match result {
        Some((start, end)) => {
            let s = std::str::from_utf8(&input[start..end]).unwrap_or("?");
            println!("{}: found at {}..{}: {}", label, start, end, s);
        }
        None => println!("{}: not found", label),
    }
}

fn main() {
    let args: Vec<String> = std::env::args().collect();
    if args.len() < 2 {
        eprintln!("Usage: secrets <input>");
        std::process::exit(1);
    }
    let input = args[1].as_bytes();

    report("GitHub token", input, github::find_github_token(input));
    report("JWT",          input, jwt::find_jwt_token(input));
    report("AWS key",      input, aws::find_aws_key(input));
}
