// Stubs are auto-generated by: regexped generate --rust
// stubs.rs contains pub mod blocks for each pattern (github, jwt, aws).
include!("stubs.rs");

fn main() {
    let args: Vec<String> = std::env::args().collect();
    if args.len() < 2 {
        eprintln!("Usage: secrets <input>");
        std::process::exit(1);
    }
    let input = args[1].as_bytes();

    let mut found = false;

    for (start, end) in github::find_github_token(input) {
        let s = std::str::from_utf8(&input[start..end]).unwrap_or("?");
        println!("GitHub token at {}..{}: {}", start, end, s);
        found = true;
    }
    for (start, end) in jwt::find_jwt_token(input) {
        let s = std::str::from_utf8(&input[start..end]).unwrap_or("?");
        println!("JWT at {}..{}: {}", start, end, s);
        found = true;
    }
    for (start, end) in aws::find_aws_key(input) {
        let s = std::str::from_utf8(&input[start..end]).unwrap_or("?");
        println!("AWS key at {}..{}: {}", start, end, s);
        found = true;
    }

    if !found {
        println!("No secrets found");
    }
}
