// Stubs are auto-generated by: regexped generate
// All patterns are compiled into one module: regexps.
include!("stubs.rs");

use proxy_wasm::traits::*;
use proxy_wasm::types::*;

#[derive(serde::Deserialize)]
struct RequestParams {
    email: String,
    url: String,
    descr: String,
}

const INVALID_REQUEST: u32 = 400;

proxy_wasm::main! {{
    proxy_wasm::set_log_level(LogLevel::Trace);
    proxy_wasm::set_root_context(|_| -> Box<dyn RootContext> { Box::new(HttpHeadersRoot) });
}}

struct HttpHeadersRoot;

impl Context for HttpHeadersRoot {}

impl RootContext for HttpHeadersRoot {
    fn create_http_context(&self, _context_id: u32) -> Option<Box<dyn HttpContext>> {
        Some(Box::new(HttpReqBody {}))
    }
    fn get_type(&self) -> Option<ContextType> {
        Some(ContextType::HttpContext)
    }
}

struct HttpReqBody {}

impl Context for HttpReqBody {}

impl HttpContext for HttpReqBody {
    fn on_http_request_body(&mut self, size: usize, end_of_stream: bool) -> Action {
        if !end_of_stream {
            return Action::Pause;
        }

        match self.get_property(vec!["request.method"]) {
            Some(method) if method == b"POST" => (),
            _ => {
                self.send_http_response(INVALID_REQUEST, vec![], Some("Invalid request method".as_bytes()));
                return Action::Pause;
            }
        }

        match self.get_http_request_header("Content-Type") {
            Some(content_type) if content_type == "application/json" => (),
            _ => {
                self.send_http_response(INVALID_REQUEST, vec![], Some("Unsupported Content-Type".as_bytes()));
                return Action::Pause;
            }
        }

        let Some(body) = self.get_http_request_body(0, size) else {
            // no body - error
            self.send_http_response(INVALID_REQUEST, vec![], Some("Missing request body".as_bytes()));
            return Action::Pause;
        };

        let Ok(p) = serde_json::from_slice::<RequestParams>(&body) else {
            // malformed body
            self.send_http_response(INVALID_REQUEST, vec![], Some("Invalid request body".as_bytes()));
            return Action::Pause;
        };

        println!("Received request: email={}, url={}, descr={}", p.email, p.url, p.descr);

        // Every matcher returns a Result. Err means the engine could not
        // ANSWER — not that the input failed validation — so it is a 500, not
        // a 400: rejecting the request would report "unknown" as "invalid".
        let validation_failed = |reason: &str| println!("{reason}");

        // validate the e-mail address
        match regexps::match_email(p.email.as_bytes()) {
            Ok(Some(_)) => {}
            Ok(None) => {
                validation_failed(&format!("Invalid email address: {}", p.email));
                self.send_http_response(INVALID_REQUEST, vec![], Some("Invalid email address".as_bytes()));
                return Action::Pause;
            }
            Err(err) => return self.cannot_validate(err),
        }

        // validate the URL
        match regexps::url_match(p.url.as_bytes()) {
            Ok(Some(_)) => {}
            Ok(None) => {
                validation_failed(&format!("Invalid URL: {}", p.url));
                self.send_http_response(INVALID_REQUEST, vec![], Some("Invalid URL".as_bytes()));
                return Action::Pause;
            }
            Err(err) => return self.cannot_validate(err),
        }

        // check for XSS in the description
        match regexps::find_xss(p.descr.as_bytes(), 0).next() {
            Some(Ok(_)) => {
                validation_failed(&format!("Description contains potential XSS: {}", p.descr));
                self.send_http_response(INVALID_REQUEST, vec![], Some("Description contains potential XSS".as_bytes()));
                return Action::Pause;
            }
            None => {}
            Some(Err(err)) => return self.cannot_validate(err),
        }

        Action::Continue // checks passed
    }
}

impl HttpReqBody {
    /// The engine could not decide. That is a SERVER failure, not a rejected
    /// request: answering 400 here would report "unknown" as "invalid".
    fn cannot_validate(&mut self, err: regexps::Error) -> Action {
        println!("Cannot validate request: {err}");
        self.send_http_response(500, vec![], Some("Cannot validate request".as_bytes()));
        Action::Pause
    }
}
