// url-ipv6 example: find IPv6-addressed URLs in arbitrary text.
// stub.rs is auto-generated by: regexped stub --rust
include!("stub.rs");

fn main() {
    let args: Vec<String> = std::env::args().collect();
    if args.len() < 2 {
        eprintln!("Usage: url_ipv6 <input>");
        std::process::exit(1);
    }
    let input = args[1].as_bytes();

    match find_ipv6_url(input) {
        Some((start, end)) => {
            let url = std::str::from_utf8(&input[start..end]).unwrap_or("<invalid utf8>");
            println!("Found IPv6 URL at bytes {}..{}: {}", start, end, url);
        }
        None => println!("No IPv6 URL found"),
    }
}
