//go:build wasip1

// secret-scanner: scan text for known secret patterns using a regexped set.
// stub.go is auto-generated by: regexped generate --config=regexped.yaml
package main

import (
	"fmt"
	"io"
	"os"
)

func main() {
	input, err := io.ReadAll(os.Stdin)
	if err != nil {
		fmt.Fprintln(os.Stderr, "error reading input:", err)
		os.Exit(1)
	}

	count := 0
	scanIter := scan_secrets(input, 0)
	for match := range scanIter.Matches() {
		matched := string(input[match.Start:match.End])
		fmt.Printf("[%s] at %d..%d: %s\n", PatternName(match.PatternID), match.Start, match.End, matched)
		count++
	}
	// Check Err() after the loop: an engine that gave up ends iteration the
	// same way exhausting the input does.
	if err := scanIter.Err(); err != nil {
		fmt.Fprintln(os.Stderr, "scan_secrets:", err)
		os.Exit(2)
	}

	if count == 0 {
		fmt.Println("No secrets found.")
	} else {
		fmt.Printf("\n%d secret(s) found.\n", count)
	}
}
