//go:build wasip1

// secret-scanner: scan text for known secret patterns using a regexped set.
// stub.go is auto-generated by: regexped generate --config=regexped.yaml
package main

import (
	"fmt"
	"io"
	"os"
)

func main() {
	input, err := io.ReadAll(os.Stdin)
	if err != nil {
		fmt.Fprintln(os.Stderr, "error reading input:", err)
		os.Exit(1)
	}

	count := 0
	for m := range ScanSecrets(input) {
		matched := string(input[m.Start:m.End])
		fmt.Printf("[%s] at %d..%d: %s\n", PatternName(m.PatternID), m.Start, m.End, matched)
		count++
	}

	if count == 0 {
		fmt.Println("No secrets found.")
	} else {
		fmt.Printf("\n%d secret(s) found.\n", count)
	}
}
