// url-parts example: parse a URL into named components using OnePass engine.
// The pattern is anchored — pass the URL itself, not surrounding text.
// stub.rs is auto-generated by: regexped stub --rust
include!("stub.rs");

fn main() {
    let args: Vec<String> = std::env::args().collect();
    if args.len() < 2 {
        eprintln!("Usage: url_parts <url>");
        std::process::exit(1);
    }
    let url = &args[1];
    let input = url.as_bytes();

    match parse_url(input) {
        None => println!("Not a valid URL"),
        Some(parts) => {
            for name in &["scheme", "host", "port", "path", "query", "fragment"] {
                match parts.get(*name) {
                    Some((start, end)) => println!("{:10} = {}", name, &url[*start..*end]),
                    None               => println!("{:10} = (absent)", name),
                }
            }
        }
    }
}
