// url-parts example: find and parse all URLs in text using OnePass engine.
// stub.rs is auto-generated by: regexped stub --rust
include!("stub.rs");

fn main() {
    let args: Vec<String> = std::env::args().collect();
    if args.len() < 2 {
        eprintln!("Usage: url_parts <text>");
        std::process::exit(1);
    }
    let text = &args[1];
    let input = text.as_bytes();

    let mut found = false;
    for parts in parse_url(input) {
        found = true;
        println!("URL:");
        for name in &["scheme", "host", "port", "path", "query", "fragment"] {
            match parts.get(*name) {
                Some((start, end)) => println!("  {:10} = {}", name, &text[*start..*end]),
                None               => println!("  {:10} = (absent)", name),
            }
        }
    }
    if !found {
        println!("No URLs found");
    }
}
