// Auto-generated by regexped. Do not edit.

let _exp, _mem;
const _enc = new TextEncoder();

export async function init(wasm) {
    const { instance } = await WebAssembly.instantiate(wasm);
    _exp = instance.exports;
    _mem = new Uint8Array(_exp.memory.buffer);
}

function _b(input) {
    return typeof input === 'string' ? _enc.encode(input) : input;
}

// find_github_token — yields [start, end] for each non-overlapping match.
export function* find_github_token(input) {
    const b = _b(input);
    let off = 0;
    while (off <= b.length) {
        _mem.set(b.subarray(off), 0);
        const r = _exp['find_github_token'](0, b.length - off);
        if (r < 0n) break;
        const relStart = Number(r >> 32n);
        const relEnd   = Number(r & 0xFFFFFFFFn);
        yield [off + relStart, off + relEnd];
        off += relEnd > relStart ? relEnd : relStart + 1;
    }
}

// find_jwt_token — yields [start, end] for each non-overlapping match.
export function* find_jwt_token(input) {
    const b = _b(input);
    let off = 0;
    while (off <= b.length) {
        _mem.set(b.subarray(off), 0);
        const r = _exp['find_jwt_token'](0, b.length - off);
        if (r < 0n) break;
        const relStart = Number(r >> 32n);
        const relEnd   = Number(r & 0xFFFFFFFFn);
        yield [off + relStart, off + relEnd];
        off += relEnd > relStart ? relEnd : relStart + 1;
    }
}

// find_aws_key — yields [start, end] for each non-overlapping match.
export function* find_aws_key(input) {
    const b = _b(input);
    let off = 0;
    while (off <= b.length) {
        _mem.set(b.subarray(off), 0);
        const r = _exp['find_aws_key'](0, b.length - off);
        if (r < 0n) break;
        const relStart = Number(r >> 32n);
        const relEnd   = Number(r & 0xFFFFFFFFn);
        yield [off + relStart, off + relEnd];
        off += relEnd > relStart ? relEnd : relStart + 1;
    }
}

